"""Les paires de mots du jeu.

Chaque paire est écrite à la main. C'est le remplacement d'un système
par groupes de dix où l'on tirait deux mots au hasard : sur 45
combinaisons possibles par groupe, certaines étaient bonnes et d'autres
non, sans moyen de trier. Ici, **chaque tirage est une paire validée**.

Ce qui fait une bonne paire :

1. **Même nature.** Deux fruits, deux métiers, deux instruments — pas
   « gare » et « piscine », dont les indices n'ont rien en commun.
2. **Une seule différence saillante.** « courgette » et « concombre » se
   ressemblent, mais l'un se cuit et l'autre se croque. C'est cette
   unique différence qui permet de démasquer l'Undercover.
3. **Aucun synonyme.** « développeur » et « programmeur » se décrivent
   identiquement : les civils ne peuvent structurellement pas gagner.
4. **Aucun hyperonyme.** Pas de « chaussure » face à « botte » : le
   joueur qui a le mot général ne peut rien dire qui ne s'applique pas
   aussi à l'autre.
5. **Pas de différence de taille seule.** « lac » et « étang », c'est la
   même chose en plus petit — indécidable en un indice.
6. **Que des mots connus, et un seul mot par carte.** Un joueur qui
   reçoit « caracal » ne joue pas, il se tait. Rien qui contienne un
   espace non plus, sinon l'indice unique porterait sur deux idées.
7. **Aucun duo réflexe.** « bain » et « douche » vont par deux dans la
   tête de tout le monde : celui qui tire l'un sait aussitôt ce qu'a
   l'autre camp, et l'Undercover se fond sans effort. Il faut que le mot
   reçu laisse plusieurs voisins possibles.

Les contraires tombent sous la règle 7 autant que les duos d'usage :
« généreux » appelle « avare » aussi sûrement que « bain » appelle
« douche ». Les traits de caractère sont donc croisés sans rapport entre
eux plutôt qu'opposés deux à deux.

C'est encore la règle 7 qui explique **qu'un mot serve dans plusieurs
paires**, trois au maximum. « pomme » tombe tantôt avec « coing »,
tantôt avec « pêche » : le tenir ne renseigne sur rien. Un dictionnaire
où chaque mot n'aurait qu'un seul partenaire serait entièrement
prévisible dès qu'on le connaît — défaut supportable à 257 paires,
rédhibitoire à 2500.

Les règles 3, 4 et 7 ne se vérifient pas automatiquement : elles portent
sur ce que deux mots évoquent, pas sur leur forme. Elles s'appliquent à
la relecture, thème par thème. `tools/audit_words.py` couvre le reste —
doublons, mots trop sollicités, mots à espace — et signale les paires
proches de forme, qui sont des points à relire, pas un verdict.
"""

from __future__ import annotations

import random
from typing import Sequence

WordPair = tuple[str, str]

# Les themes servent a la relecture et a l'audit ; le tirage, lui, pioche
# uniformement dans WORD_PAIRS.
PAIRS_BY_THEME: dict[str, tuple[WordPair, ...]] = {
    "Ferme": (
        ("vache", "chèvre"), ("vache", "brebis"), ("chèvre", "truie"),
        ("mouton", "cochon"), ("mouton", "veau"), ("agneau", "veau"),
        ("agneau", "chevreau"), ("taureau", "bélier"), ("taureau", "étalon"),
        ("bélier", "bouc"), ("bouc", "verrat"), ("cheval", "âne"),
        ("cheval", "mulet"), ("poney", "âne"), ("poney", "mulet"),
        ("jument", "truie"), ("poule", "pintade"), ("poule", "oie"),
        ("coq", "paon"), ("canard", "oie"), ("canard", "dinde"),
        ("dinde", "pintade"), ("poussin", "caneton"), ("lapin", "cochon"),
        ("étable", "bergerie"), ("étable", "poulailler"), ("grange", "silo"),
        ("grange", "hangar"), ("enclos", "pâturage"), ("clôture", "haie"),
        ("blé", "orge"), ("blé", "seigle"), ("avoine", "orge"),
        ("maïs", "seigle"), ("tracteur", "moissonneuse"), ("charrue", "herse"),
        ("ruche", "poulailler"), ("berger", "vacher"),
    ),
    "Animaux sauvages": (
        ("lion", "tigre"), ("lion", "guépard"), ("tigre", "panthère"),
        ("guépard", "léopard"), ("panthère", "lynx"), ("lynx", "puma"),
        ("loup", "renard"), ("loup", "chacal"), ("renard", "blaireau"),
        ("hyène", "chacal"), ("ours", "sanglier"), ("ours", "panda"),
        ("panda", "koala"), ("koala", "paresseux"), ("singe", "gorille"),
        ("gorille", "chimpanzé"), ("chimpanzé", "babouin"), ("éléphant", "rhinocéros"),
        ("rhinocéros", "hippopotame"), ("hippopotame", "buffle"), ("girafe", "zèbre"),
        ("zèbre", "antilope"), ("antilope", "gazelle"), ("gazelle", "impala"),
        ("cerf", "élan"), ("cerf", "chevreuil"), ("chevreuil", "daim"),
        ("renne", "élan"), ("bison", "buffle"), ("sanglier", "phacochère"),
        ("kangourou", "wallaby"), ("kangourou", "autruche"), ("chameau", "lama"),
        ("dromadaire", "lama"), ("écureuil", "marmotte"), ("souris", "musaraigne"),
        ("rat", "mulot"), ("hérisson", "taupe"), ("taupe", "blaireau"),
        ("castor", "loutre"), ("loutre", "phoque"), ("phoque", "morse"),
        ("morse", "otarie"), ("chauve-souris", "hibou"), ("belette", "furet"),
        ("furet", "martre"), ("raton", "opossum"), ("suricate", "marmotte"),
        ("gnou", "buffle"), ("okapi", "antilope"), ("lion", "ours"),
        ("loup", "lynx"), ("tigre", "hyène"), ("girafe", "chameau"),
        ("éléphant", "bison"), ("singe", "koala"), ("cerf", "sanglier"),
        ("renard", "belette"), ("castor", "marmotte"), ("hérisson", "opossum"),
        ("morse", "loutre"), ("kangourou", "paresseux"), ("zèbre", "gnou"),
        ("puma", "chacal"), ("écureuil", "furet"), ("gazelle", "renne"),
        ("panda", "suricate"),
    ),
    "Oiseaux": (
        ("aigle", "faucon"), ("aigle", "vautour"), ("faucon", "épervier"),
        ("buse", "épervier"), ("vautour", "condor"), ("corbeau", "pie"),
        ("corbeau", "choucas"), ("pie", "geai"), ("moineau", "mésange"),
        ("moineau", "rouge-gorge"), ("mésange", "chardonneret"), ("merle", "grive"),
        ("merle", "étourneau"), ("rossignol", "alouette"), ("hirondelle", "martinet"),
        ("pinson", "linotte"), ("pigeon", "tourterelle"), ("pigeon", "mouette"),
        ("mouette", "goéland"), ("goéland", "cormoran"), ("cygne", "oie"),
        ("cygne", "flamant"), ("héron", "cigogne"), ("cigogne", "grue"),
        ("grue", "flamant"), ("pélican", "cormoran"), ("manchot", "autruche"),
        ("autruche", "émeu"), ("émeu", "casoar"), ("paon", "faisan"),
        ("faisan", "perdrix"), ("perdrix", "caille"), ("perroquet", "toucan"),
        ("perroquet", "ara"), ("perruche", "canari"), ("canari", "chardonneret"),
        ("colibri", "martinet"), ("pivert", "sittelle"), ("coucou", "grive"),
        ("albatros", "condor"), ("nid", "terrier"), ("plume", "écaille"),
        ("aile", "nageoire"), ("aigle", "cygne"), ("corbeau", "moineau"),
        ("hibou", "paon"), ("mouette", "héron"), ("perroquet", "canari"),
        ("pigeon", "faisan"), ("hirondelle", "merle"), ("cigogne", "vautour"),
        ("colibri", "toucan"), ("caille", "grive"), ("flamant", "pélican"),
        ("geai", "pinson"), ("buse", "coucou"), ("plume", "nid"),
    ),
    "Mer et rivière": (
        ("dauphin", "marsouin"), ("dauphin", "requin"), ("requin", "raie"),
        ("baleine", "cachalot"), ("baleine", "orque"), ("orque", "narval"),
        ("thon", "saumon"), ("thon", "maquereau"), ("saumon", "truite"),
        ("truite", "carpe"), ("carpe", "brochet"), ("brochet", "perche"),
        ("sardine", "anchois"), ("hareng", "maquereau"), ("morue", "colin"),
        ("sole", "turbot"), ("anguille", "murène"), ("murène", "congre"),
        ("poulpe", "seiche"), ("seiche", "calmar"), ("méduse", "anémone"),
        ("étoile", "oursin"), ("oursin", "anémone"), ("crabe", "homard"),
        ("homard", "langouste"), ("crevette", "écrevisse"), ("écrevisse", "langoustine"),
        ("moule", "huître"), ("huître", "coquille"), ("palourde", "coque"),
        ("bulot", "bigorneau"), ("corail", "algue"), ("algue", "plancton"),
        ("hippocampe", "poisson-clown"), ("tortue", "crocodile"), ("otarie", "phoque"),
        ("récif", "banc"), ("marée", "courant"),
    ),
    "Insectes et petites bêtes": (
        ("abeille", "guêpe"), ("abeille", "bourdon"), ("guêpe", "frelon"),
        ("papillon", "libellule"), ("papillon", "mite"), ("libellule", "éphémère"),
        ("fourmi", "termite"), ("fourmi", "cloporte"), ("termite", "cafard"),
        ("cafard", "punaise"), ("puce", "pou"), ("pou", "tique"),
        ("tique", "acarien"), ("moustique", "moucheron"), ("taon", "moustique"),
        ("criquet", "sauterelle"), ("sauterelle", "grillon"), ("grillon", "cigale"),
        ("coccinelle", "scarabée"), ("scarabée", "hanneton"), ("lucane", "hanneton"),
        ("araignée", "scorpion"), ("scorpion", "mille-pattes"), ("limace", "ver"),
        ("ver", "chenille"), ("toile", "nid"), ("crapaud", "salamandre"),
        ("salamandre", "triton"), ("lézard", "gecko"), ("gecko", "caméléon"),
        ("caméléon", "iguane"), ("serpent", "orvet"), ("cobra", "python"),
        ("python", "boa"), ("boa", "anaconda"),
    ),
    "Fruits": (
        ("pomme", "coing"), ("poire", "prune"), ("pêche", "abricot"),
        ("abricot", "prune"), ("cerise", "groseille"), ("cerise", "prune"),
        ("fraise", "framboise"), ("framboise", "mûre"), ("mûre", "myrtille"),
        ("myrtille", "groseille"), ("cassis", "groseille"), ("raisin", "figue"),
        ("figue", "datte"), ("datte", "pruneau"), ("banane", "mangue"),
        ("mangue", "papaye"), ("papaye", "goyave"), ("ananas", "mangue"),
        ("orange", "mandarine"), ("citron", "pamplemousse"), ("pamplemousse", "orange"),
        ("kiwi", "litchi"), ("litchi", "grenade"), ("grenade", "kaki"),
        ("melon", "pastèque"), ("melon", "courge"), ("noix", "noisette"),
        ("noisette", "amande"), ("amande", "pistache"), ("cacahuète", "pistache"),
        ("olive", "câpre"), ("avocat", "olive"), ("peau", "écorce"),
        ("verger", "vigne"), ("panier", "cageot"), ("abricot", "figue"),
        ("fraise", "cassis"), ("banane", "datte"), ("citron", "kaki"),
        ("noix", "cacahuète"), ("pastèque", "courge"), ("mandarine", "litchi"),
        ("ananas", "goyave"), ("coing", "pruneau"), ("avocat", "kiwi"),
        ("papaye", "pamplemousse"), ("pêche", "raisin"),
    ),
    "Légumes": (
        ("carotte", "navet"), ("carotte", "panais"), ("navet", "radis"),
        ("radis", "betterave"), ("betterave", "céleri"), ("tomate", "poivron"),
        ("poivron", "piment"), ("piment", "paprika"), ("courgette", "concombre"),
        ("courgette", "aubergine"), ("aubergine", "poivron"), ("courge", "potiron"),
        ("oignon", "échalote"), ("échalote", "ail"), ("ail", "poireau"),
        ("poireau", "asperge"), ("asperge", "haricot"), ("salade", "épinard"),
        ("épinard", "blette"), ("blette", "chou"), ("chou", "brocoli"),
        ("brocoli", "chou-fleur"), ("artichaut", "chou-fleur"), ("endive", "fenouil"),
        ("fenouil", "céleri"), ("champignon", "truffe"), ("champignon", "cèpe"),
        ("cèpe", "girolle"), ("maïs", "quinoa"), ("riz", "semoule"),
        ("semoule", "boulgour"), ("potager", "serre"), ("carotte", "poireau"),
        ("tomate", "aubergine"), ("radis", "endive"), ("betterave", "artichaut"),
        ("navet", "fenouil"), ("chou-fleur", "haricot"), ("épinard", "asperge"),
        ("céleri", "panais"), ("oignon", "piment"), ("courgette", "potiron"),
        ("blette", "brocoli"), ("maïs", "riz"),
    ),
    "Plats": (
        ("pizza", "quiche"), ("quiche", "tourte"), ("burger", "sandwich"),
        ("sandwich", "wrap"), ("wrap", "kebab"), ("hot-dog", "kebab"),
        ("sushi", "maki"), ("maki", "nem"), ("nem", "samoussa"),
        ("raviolis", "gnocchis"), ("gnocchis", "spaghettis"), ("spaghettis", "tagliatelles"),
        ("lasagnes", "cannellonis"), ("risotto", "paella"), ("paella", "couscous"),
        ("couscous", "tajine"), ("tajine", "curry"), ("curry", "chili"),
        ("ragoût", "pot-au-feu"), ("pot-au-feu", "blanquette"), ("blanquette", "bourguignon"),
        ("gratin", "clafoutis"), ("purée", "écrasé"), ("frites", "chips"),
        ("chips", "beignets"), ("beignet", "croquette"), ("croquette", "nugget"),
        ("soupe", "velouté"), ("velouté", "bouillon"), ("bouillon", "consommé"),
        ("salade", "taboulé"), ("taboulé", "coleslaw"), ("omelette", "brouillade"),
        ("crêpe", "galette"), ("galette", "gaufre"), ("fondue", "tartiflette"),
        ("choucroute", "cassoulet"), ("cassoulet", "chili"), ("rôti", "grillade"),
        ("grillade", "brochette"), ("brochette", "kebab"), ("steak", "escalope"),
        ("escalope", "côtelette"), ("saucisse", "merguez"), ("merguez", "chipolata"),
        ("pizza", "lasagnes"), ("sushi", "samoussa"), ("couscous", "risotto"),
        ("soupe", "salade"), ("omelette", "gratin"), ("crêpe", "gaufre"),
        ("frites", "purée"), ("steak", "saucisse"), ("brochette", "croquette"),
        ("blanquette", "ragoût"), ("chips", "nugget"), ("velouté", "consommé"),
    ),
    "Desserts et sucreries": (
        ("gâteau", "tarte"), ("gâteau", "cake"), ("tarte", "flan"),
        ("éclair", "religieuse"), ("religieuse", "chou"), ("mille-feuille", "opéra"),
        ("macaron", "meringue"), ("meringue", "guimauve"), ("guimauve", "nougat"),
        ("nougat", "praline"), ("praline", "truffe"), ("bonbon", "sucette"),
        ("sucette", "chewing-gum"), ("caramel", "toffee"), ("chocolat", "praliné"),
        ("glace", "sorbet"), ("sorbet", "granité"), ("granité", "smoothie"),
        ("croissant", "brioche"), ("brioche", "chausson"), ("chausson", "beignet"),
        ("madeleine", "financier"), ("financier", "cannelé"), ("cookie", "biscuit"),
        ("biscuit", "sablé"), ("sablé", "spéculoos"), ("gaufre", "churro"),
        ("crumble", "cobbler"), ("compote", "confiture"), ("confiture", "gelée"),
        ("miel", "sirop"), ("sirop", "mélasse"), ("sucre", "vanille"),
        ("cupcake", "muffin"), ("donut", "beignet"), ("pâte", "glaçage"),
        ("gâteau", "flan"), ("tarte", "crumble"), ("glace", "granité"),
        ("bonbon", "nougat"), ("macaron", "madeleine"), ("cookie", "spéculoos"),
        ("chocolat", "caramel"), ("éclair", "cannelé"), ("muffin", "donut"),
        ("compote", "gelée"), ("sorbet", "milkshake"),
    ),
    "Boissons": (
        ("expresso", "cappuccino"), ("cappuccino", "latte"), ("jus", "nectar"),
        ("nectar", "smoothie"), ("soda", "limonade"), ("limonade", "tonic"),
        ("cola", "tonic"), ("sirop", "grenadine"), ("bière", "cidre"),
        ("cidre", "poiré"), ("vin", "champagne"), ("champagne", "mousseux"),
        ("rosé", "sangria"), ("whisky", "rhum"), ("rhum", "vodka"),
        ("vodka", "gin"), ("gin", "tequila"), ("cocktail", "punch"),
        ("punch", "sangria"), ("milkshake", "smoothie"), ("chope", "gobelet"),
        ("carafe", "pichet"), ("bouteille", "gourde"), ("paille", "touillette"),
        ("glaçon", "rondelle"), ("bar", "terrasse"), ("tonneau", "fût"),
    ),
    "Épicerie": (
        ("pain", "baguette"), ("baguette", "ficelle"), ("farine", "levure"),
        ("levure", "bicarbonate"), ("margarine", "saindoux"), ("moutarde", "mayonnaise"),
        ("mayonnaise", "ketchup"), ("ketchup", "harissa"), ("sel", "sucre"),
        ("poivre", "muscade"), ("muscade", "cannelle"), ("cannelle", "gingembre"),
        ("gingembre", "curcuma"), ("curcuma", "safran"), ("basilic", "persil"),
        ("persil", "coriandre"), ("coriandre", "menthe"), ("thym", "romarin"),
        ("romarin", "laurier"), ("laurier", "origan"), ("camembert", "brie"),
        ("brie", "roquefort"), ("roquefort", "gorgonzola"), ("comté", "gruyère"),
        ("feta", "mozzarella"), ("mozzarella", "burrata"), ("crème", "mascarpone"),
        ("jambon", "saucisson"), ("saucisson", "chorizo"), ("chorizo", "salami"),
        ("pâté", "rillettes"), ("rillettes", "terrine"), ("bocal", "conserve"),
        ("boîte", "sachet"),
    ),
    "Vêtements": (
        ("chemise", "polo"), ("polo", "tee-shirt"), ("tee-shirt", "débardeur"),
        ("pull", "gilet"), ("pull", "sweat"), ("sweat", "hoodie"),
        ("gilet", "cardigan"), ("veste", "blazer"), ("blazer", "smoking"),
        ("manteau", "parka"), ("parka", "doudoune"), ("doudoune", "anorak"),
        ("imperméable", "ciré"), ("cape", "poncho"), ("poncho", "châle"),
        ("robe", "tunique"), ("tunique", "jupe"), ("jupe", "kilt"),
        ("pantalon", "jean"), ("jean", "chino"), ("short", "bermuda"),
        ("bermuda", "corsaire"), ("collant", "bas"), ("pyjama", "peignoir"),
        ("peignoir", "kimono"), ("maillot", "combinaison"), ("combinaison", "salopette"),
        ("uniforme", "livrée"), ("costume", "tailleur"), ("gilet", "brassière"),
        ("caleçon", "boxer"), ("chaussette", "chausson"), ("manche", "col"),
        ("col", "revers"), ("poche", "doublure"), ("ourlet", "pli"),
        ("tissu", "cuir"), ("laine", "coton"), ("coton", "lin"),
        ("lin", "soie"), ("soie", "velours"), ("velours", "satin"),
        ("dentelle", "broderie"), ("chemise", "pull"), ("robe", "salopette"),
        ("jean", "short"), ("manteau", "cape"), ("pyjama", "maillot"),
        ("jupe", "bermuda"), ("costume", "uniforme"), ("kimono", "poncho"),
        ("anorak", "blazer"), ("collant", "chaussette"), ("laine", "dentelle"),
        ("velours", "cuir"), ("coton", "satin"), ("manche", "poche"),
        ("tunique", "débardeur"), ("cardigan", "sweat"),
    ),
    "Chaussures et accessoires": (
        ("basket", "mocassin"), ("mocassin", "derby"), ("escarpin", "ballerine"),
        ("ballerine", "mule"), ("bottine", "santiag"), ("sandale", "tong"),
        ("tong", "claquette"), ("espadrille", "sandale"), ("sabot", "galoche"),
        ("lacet", "boucle"), ("semelle", "talon"), ("casquette", "bonnet"),
        ("bonnet", "cagoule"), ("béret", "turban"), ("turban", "bandana"),
        ("chapeau", "canotier"), ("canotier", "melon"), ("écharpe", "foulard"),
        ("foulard", "châle"), ("gant", "moufle"), ("moufle", "mitaine"),
        ("ceinture", "bretelles"), ("lunettes", "masque"), ("masque", "visière"),
        ("sac", "cabas"), ("cabas", "besace"), ("sacoche", "pochette"),
        ("valise", "malle"), ("malle", "coffre"), ("éventail", "ombrelle"),
        ("mouchoir", "serviette"),
    ),
    "Bijoux et parures": (
        ("bague", "chevalière"), ("bague", "alliance"), ("collier", "sautoir"),
        ("sautoir", "pendentif"), ("pendentif", "médaillon"), ("bracelet", "gourmette"),
        ("gourmette", "jonc"), ("boucle", "créole"), ("créole", "puce"),
        ("broche", "épingle"), ("épingle", "barrette"), ("diadème", "couronne"),
        ("couronne", "tiare"), ("chaîne", "cordon"), ("diamant", "rubis"),
        ("rubis", "saphir"), ("saphir", "émeraude"), ("émeraude", "topaze"),
        ("améthyste", "topaze"), ("argent", "bronze"), ("bronze", "cuivre"),
        ("platine", "titane"), ("maquillage", "fard"),
    ),
    "Corps humain": (
        ("coude", "genou"), ("genou", "cheville"), ("poignet", "cheville"),
        ("épaule", "hanche"), ("hanche", "taille"), ("pouce", "index"),
        ("ongle", "cheveu"), ("cheveu", "poil"), ("front", "menton"),
        ("menton", "joue"), ("joue", "tempe"), ("nez", "oreille"),
        ("œil", "sourcil"), ("lèvre", "paupière"), ("dent", "gencive"),
        ("langue", "palais"), ("gorge", "nuque"), ("nuque", "échine"),
        ("torse", "hanche"), ("cœur", "poumon"), ("poumon", "foie"),
        ("foie", "rein"), ("rein", "estomac"), ("cerveau", "moelle"),
        ("os", "cartilage"), ("muscle", "tendon"), ("tendon", "ligament"),
        ("peau", "ongle"), ("crâne", "mâchoire"), ("côte", "vertèbre"),
        ("talon", "voûte"), ("ride", "cicatrice"), ("genou", "épaule"),
        ("poignet", "nuque"), ("dent", "langue"), ("cœur", "rein"),
        ("foie", "estomac"), ("poumon", "cerveau"), ("os", "muscle"),
        ("tendon", "vertèbre"), ("crâne", "côte"), ("talon", "pouce"),
        ("gorge", "gencive"), ("moelle", "cartilage"),
    ),
    "Santé et soins": (
        ("rhume", "grippe"), ("grippe", "angine"), ("angine", "bronchite"),
        ("toux", "éternuement"), ("fièvre", "frisson"), ("migraine", "vertige"),
        ("nausée", "vertige"), ("bosse", "égratignure"), ("coupure", "brûlure"),
        ("brûlure", "ampoule"), ("entorse", "fracture"), ("fracture", "luxation"),
        ("piqûre", "morsure"), ("allergie", "eczéma"), ("eczéma", "urticaire"),
        ("carie", "abcès"), ("pansement", "bandage"), ("bandage", "attelle"),
        ("plâtre", "attelle"), ("béquille", "canne"), ("canne", "déambulateur"),
        ("seringue", "perfusion"), ("comprimé", "gélule"), ("thermomètre", "tensiomètre"),
        ("stéthoscope", "otoscope"), ("scanner", "échographie"), ("vaccin", "rappel"),
        ("ordonnance", "posologie"), ("infirmerie", "urgences"), ("massage", "étirement"),
    ),
    "Pièces et bâti": (
        ("salon", "véranda"), ("cave", "cellier"), ("chambre", "bureau"),
        ("bureau", "atelier"), ("atelier", "garage"), ("balcon", "terrasse"),
        ("terrasse", "patio"), ("loggia", "véranda"), ("couloir", "palier"),
        ("palier", "vestibule"), ("entrée", "vestibule"), ("escalier", "échelle"),
        ("échelle", "rampe"), ("buanderie", "cellier"), ("dressing", "penderie"),
        ("mansarde", "grenier"), ("mur", "cloison"), ("plancher", "parquet"),
        ("parquet", "carrelage"), ("carrelage", "lino"), ("moquette", "lino"),
        ("portail", "grille"), ("fenêtre", "lucarne"), ("lucarne", "hublot"),
        ("volet", "persienne"), ("store", "rideau"), ("tuile", "ardoise"),
        ("cheminée", "poêle"), ("gouttière", "chéneau"), ("clé", "verrou"),
        ("verrou", "loquet"), ("poignée", "bouton"), ("sonnette", "heurtoir"),
        ("radiateur", "climatiseur"),
    ),
    "Meubles": (
        ("table", "comptoir"), ("table", "console"), ("bureau", "secrétaire"),
        ("chaise", "tabouret"), ("tabouret", "banc"), ("banc", "banquette"),
        ("canapé", "fauteuil"), ("fauteuil", "pouf"), ("pouf", "coussin"),
        ("lit", "hamac"), ("hamac", "matelas"), ("matelas", "sommier"),
        ("berceau", "couffin"), ("armoire", "commode"), ("commode", "buffet"),
        ("buffet", "vaisselier"), ("étagère", "bibliothèque"), ("placard", "penderie"),
        ("tiroir", "casier"), ("casier", "coffre"), ("miroir", "psyché"),
        ("paravent", "cloison"), ("porte-manteau", "patère"), ("guéridon", "console"),
        ("chevet", "commode"), ("parasol", "store"), ("tapis", "paillasson"),
        ("lampadaire", "applique"), ("applique", "suspension"), ("abat-jour", "globe"),
        ("cadre", "toile"), ("table", "étagère"), ("chaise", "coussin"),
        ("canapé", "lit"), ("armoire", "tiroir"), ("bibliothèque", "vaisselier"),
        ("berceau", "banquette"), ("tapis", "paravent"), ("cadre", "globe"),
        ("chevet", "guéridon"), ("placard", "patère"), ("sommier", "couffin"),
        ("parasol", "abat-jour"),
    ),
    "Cuisine : ustensiles": (
        ("assiette", "bol"), ("assiette", "coupelle"), ("bol", "ramequin"),
        ("saladier", "plat"), ("plat", "terrine"), ("tasse", "mug"),
        ("mug", "bol"), ("fourchette", "pique"), ("cuillère", "louche"),
        ("louche", "écumoire"), ("couteau", "éplucheur"), ("éplucheur", "râpe"),
        ("râpe", "mandoline"), ("ciseaux", "pince"), ("pince", "spatule"),
        ("spatule", "maryse"), ("fouet", "batteur"), ("batteur", "mixeur"),
        ("mixeur", "blender"), ("casserole", "poêle"), ("poêle", "wok"),
        ("wok", "sauteuse"), ("cocotte", "marmite"), ("marmite", "faitout"),
        ("passoire", "tamis"), ("tamis", "chinois"), ("planche", "billot"),
        ("rouleau", "pilon"), ("moule", "ramequin"), ("plaque", "grille"),
        ("minuteur", "sablier"), ("torchon", "maniques"), ("tablier", "toque"),
        ("bouchon", "capsule"), ("tire-bouchon", "décapsuleur"), ("essoreuse", "égouttoir"),
        ("bocal", "boîte"), ("moulin", "salière"), ("casserole", "cocotte"),
        ("wok", "faitout"), ("fouet", "écumoire"), ("passoire", "râpe"),
        ("cuillère", "pique"), ("saladier", "terrine"), ("tasse", "ramequin"),
        ("bouchon", "salière"), ("torchon", "tablier"), ("rouleau", "billot"),
        ("plaque", "boîte"),
    ),
    "Salle de bain": (
        ("baignoire", "jacuzzi"), ("douche", "cabine"), ("vasque", "évier"),
        ("robinet", "mitigeur"), ("pommeau", "flexible"), ("mousse", "gel"),
        ("sèche-cheveux", "lisseur"), ("lisseur", "boucleur"), ("rasoir", "tondeuse"),
        ("déodorant", "talc"), ("parfum", "lotion"),
    ),
    "Électroménager": (
        ("four", "rôtissoire"), ("micro-ondes", "vapeur"), ("plaque", "réchaud"),
        ("hotte", "ventilateur"), ("congélateur", "glacière"), ("sèche-linge", "étendoir"),
        ("aspirateur", "balai"), ("balai", "serpillière"), ("robot", "cireuse"),
        ("bouilloire", "cafetière"), ("cafetière", "percolateur"), ("grille-pain", "gaufrier"),
        ("gaufrier", "crêpière"), ("friteuse", "cuiseur"), ("robot", "hachoir"),
        ("presse-agrumes", "centrifugeuse"), ("yaourtière", "sorbetière"), ("télévision", "vidéoprojecteur"),
        ("enceinte", "casque"), ("radio", "réveil"), ("téléphone", "tablette"),
        ("chargeur", "batterie"), ("ampoule", "néon"), ("rallonge", "multiprise"),
        ("pile", "accumulateur"),
    ),
    "Outils et bricolage": (
        ("marteau", "maillet"), ("maillet", "massette"), ("tournevis", "clé"),
        ("clé", "pince"), ("tenaille", "cisaille"), ("scie", "égoïne"),
        ("perceuse", "visseuse"), ("visseuse", "meuleuse"), ("ponceuse", "raboteuse"),
        ("burin", "ciseau"), ("mètre", "équerre"), ("équerre", "compas"),
        ("étau", "serre-joint"), ("établi", "tréteau"), ("échelle", "escabeau"),
        ("escabeau", "échafaudage"), ("vis", "boulon"), ("cheville", "rivet"),
        ("colle", "mastic"), ("mastic", "silicone"), ("ruban", "adhésif"),
        ("peinture", "vernis"), ("vernis", "lasure"), ("pinceau", "rouleau"),
        ("truelle", "spatule"), ("bétonnière", "brouette"), ("ciment", "plâtre"),
        ("plâtre", "enduit"), ("brique", "parpaing"), ("planche", "poutre"),
        ("poutre", "chevron"), ("clou", "agrafe"), ("casque", "gants"),
        ("marteau", "tournevis"), ("scie", "perceuse"), ("tenaille", "burin"),
        ("mètre", "compas"), ("étau", "tréteau"), ("clou", "rivet"),
        ("colle", "silicone"), ("peinture", "lasure"), ("pinceau", "truelle"),
        ("ciment", "parpaing"), ("ruban", "agrafe"), ("meuleuse", "ponceuse"),
    ),
    "Jardin": (
        ("arrosoir", "seau"), ("arrosoir", "pulvérisateur"), ("râteau", "pelle"),
        ("bêche", "fourche"), ("binette", "griffe"), ("sécateur", "cisaille"),
        ("cisaille", "taille-haie"), ("tondeuse", "débroussailleuse"), ("brouette", "chariot"),
        ("hache", "serpe"), ("tronçonneuse", "hache"), ("gant", "genouillère"),
        ("pot", "jardinière"), ("jardinière", "bac"), ("terreau", "compost"),
        ("compost", "paillage"), ("engrais", "fumier"), ("graine", "bulbe"),
        ("bulbe", "bouture"), ("semis", "plant"), ("serre", "châssis"),
        ("tuteur", "treillis"), ("treillis", "pergola"), ("clôture", "barrière"),
        ("portillon", "barrière"), ("allée", "sentier"), ("bassin", "mare"),
        ("fontaine", "cascade"), ("nichoir", "mangeoire"), ("épouvantail", "moulinet"),
        ("barbecue", "plancha"), ("hamac", "balançoire"), ("niche", "clapier"),
        ("arrosoir", "brouette"), ("râteau", "binette"), ("sécateur", "serpe"),
        ("tondeuse", "tronçonneuse"), ("terreau", "fumier"), ("graine", "bouture"),
        ("serre", "pergola"), ("clôture", "portillon"), ("bassin", "fontaine"),
        ("nichoir", "épouvantail"), ("barbecue", "balançoire"), ("allée", "châssis"),
    ),
    "Véhicules": (
        ("voiture", "camionnette"), ("camion", "benne"), ("benne", "citerne"),
        ("bus", "autocar"), ("autocar", "navette"), ("tramway", "trolleybus"),
        ("métro", "funiculaire"), ("funiculaire", "téléphérique"), ("train", "locomotive"),
        ("wagon", "fourgon"), ("moto", "scooter"), ("vélo", "trottinette"),
        ("trottinette", "gyropode"), ("tandem", "tricycle"), ("tricycle", "draisienne"),
        ("skateboard", "roller"), ("roller", "patinette"), ("tracteur", "bulldozer"),
        ("bulldozer", "pelleteuse"), ("grue", "nacelle"), ("ambulance", "taxi"),
        ("taxi", "limousine"), ("corbillard", "fourgon"), ("caravane", "camping-car"),
        ("remorque", "attelage"), ("calèche", "diligence"), ("charrette", "carriole"),
        ("traîneau", "luge"), ("quad", "buggy"), ("pédale", "manette"),
        ("frein", "embrayage"), ("moteur", "batterie"), ("roue", "chenille"),
        ("phare", "clignotant"), ("rétroviseur", "pare-brise"), ("portière", "hayon"),
        ("klaxon", "sirène"), ("péage", "parking"), ("station", "garage"),
        ("camion", "autocar"), ("moto", "quad"), ("vélo", "roller"),
        ("tramway", "funiculaire"), ("train", "métro"), ("tracteur", "pelleteuse"),
        ("caravane", "remorque"), ("traîneau", "charrette"), ("roue", "phare"),
        ("moteur", "klaxon"), ("portière", "rétroviseur"), ("diligence", "carriole"),
        ("skateboard", "tricycle"), ("bus", "trolleybus"),
    ),
    "Bateaux et eau": (
        ("voilier", "goélette"), ("goélette", "caravelle"), ("yacht", "vedette"),
        ("ferry", "paquebot"), ("paquebot", "cargo"), ("cargo", "pétrolier"),
        ("péniche", "chaland"), ("chalutier", "thonier"), ("remorqueur", "brise-glace"),
        ("canoë", "kayak"), ("kayak", "pirogue"), ("pédalo", "barque"),
        ("radeau", "ponton"), ("gondole", "sampan"), ("jet-ski", "hors-bord"),
        ("sous-marin", "bathyscaphe"), ("torpille", "mine"), ("voile", "spinnaker"),
        ("mât", "bôme"), ("gouvernail", "quille"), ("ancre", "amarre"),
        ("bouée", "balise"), ("hublot", "écoutille"), ("pont", "cale"),
        ("cabine", "soute"), ("port", "quai"), ("quai", "jetée"),
        ("digue", "écluse"), ("écluse", "canal"), ("phare", "sémaphore"),
        ("marin", "capitaine"),
    ),
    "Air et espace": (
        ("avion", "jet"), ("jet", "planeur"), ("planeur", "deltaplane"),
        ("deltaplane", "parapente"), ("montgolfière", "dirigeable"), ("parachute", "aile"),
        ("drone", "satellite"), ("fusée", "navette"), ("navette", "capsule"),
        ("sonde", "rover"), ("station", "module"), ("hublot", "cockpit"),
        ("aile", "hélice"), ("hélice", "réacteur"), ("piste", "hangar"),
        ("scaphandre", "combinaison"), ("planète", "astéroïde"), ("astéroïde", "comète"),
        ("comète", "météorite"), ("étoile", "galaxie"), ("galaxie", "nébuleuse"),
        ("cratère", "canyon"), ("orbite", "trajectoire"), ("observatoire", "planétarium"),
    ),
    "Paysages": (
        ("montagne", "colline"), ("colline", "butte"), ("volcan", "geyser"),
        ("falaise", "canyon"), ("gorge", "ravin"), ("vallée", "plaine"),
        ("plaine", "plateau"), ("plage", "crique"), ("crique", "baie"),
        ("baie", "golfe"), ("île", "archipel"), ("atoll", "récif"),
        ("oasis", "mirage"), ("désert", "savane"), ("savane", "steppe"),
        ("steppe", "toundra"), ("forêt", "jungle"), ("jungle", "mangrove"),
        ("bosquet", "clairière"), ("clairière", "lisière"), ("marais", "tourbière"),
        ("lac", "lagune"), ("rivière", "torrent"), ("torrent", "cascade"),
        ("cascade", "rapide"), ("fleuve", "estuaire"), ("source", "puits"),
        ("grotte", "gouffre"), ("gouffre", "crevasse"), ("glacier", "banquise"),
        ("banquise", "iceberg"), ("sentier", "col"), ("éboulis", "moraine"),
        ("colline", "falaise"), ("île", "atoll"), ("désert", "steppe"),
        ("forêt", "marais"), ("lac", "torrent"), ("fleuve", "source"),
        ("grotte", "crevasse"), ("savane", "toundra"), ("ravin", "butte"),
        ("golfe", "lagune"), ("plaine", "moraine"), ("récif", "iceberg"),
    ),
    "Météo et ciel": (
        ("pluie", "bruine"), ("averse", "orage"), ("neige", "grésil"),
        ("rosée", "brume"), ("nuage", "cumulus"), ("vent", "brise"),
        ("brise", "bourrasque"), ("tempête", "ouragan"), ("canicule", "sécheresse"),
        ("inondation", "crue"), ("avalanche", "glissement"), ("arc-en-ciel", "halo"),
        ("éclipse", "solstice"), ("marée", "houle"), ("baromètre", "girouette"),
        ("thermomètre", "pluviomètre"),
    ),
    "Arbres et plantes": (
        ("chêne", "hêtre"), ("hêtre", "frêne"), ("frêne", "orme"),
        ("bouleau", "tremble"), ("peuplier", "saule"), ("saule", "aulne"),
        ("sapin", "épicéa"), ("épicéa", "mélèze"), ("pin", "cèdre"),
        ("cyprès", "if"), ("platane", "marronnier"), ("marronnier", "tilleul"),
        ("érable", "charme"), ("noyer", "châtaignier"), ("olivier", "figuier"),
        ("pommier", "cerisier"), ("cerisier", "prunier"), ("palmier", "bananier"),
        ("baobab", "séquoia"), ("bambou", "roseau"), ("mousse", "fougère"),
        ("fougère", "prêle"), ("cactus", "aloès"), ("tronc", "branche"),
        ("racine", "souche"), ("écorce", "sève"), ("feuille", "aiguille"),
        ("bourgeon", "pousse"), ("gland", "faîne"), ("champignon", "lichen"),
        ("chêne", "bouleau"), ("sapin", "palmier"), ("saule", "olivier"),
        ("pin", "platane"), ("cactus", "bambou"), ("noyer", "figuier"),
        ("érable", "tilleul"), ("cyprès", "séquoia"), ("hêtre", "marronnier"),
        ("pommier", "prunier"), ("baobab", "aloès"), ("racine", "bourgeon"),
        ("tronc", "sève"), ("feuille", "gland"),
    ),
    "Fleurs": (
        ("rose", "pivoine"), ("pivoine", "camélia"), ("tulipe", "jonquille"),
        ("narcisse", "jacinthe"), ("lys", "iris"), ("iris", "glaïeul"),
        ("tournesol", "dahlia"), ("dahlia", "chrysanthème"), ("œillet", "gerbera"),
        ("orchidée", "anthurium"), ("violette", "pensée"), ("pensée", "primevère"),
        ("coquelicot", "bleuet"), ("bleuet", "myosotis"), ("lavande", "bruyère"),
        ("hortensia", "lilas"), ("lilas", "glycine"), ("mimosa", "genêt"),
        ("géranium", "bégonia"), ("nénuphar", "lotus"), ("tige", "pétale"),
        ("pollen", "nectar"), ("bouquet", "couronne"), ("gerbe", "guirlande"),
    ),
    "Sports": (
        ("football", "rugby"), ("basketball", "handball"), ("handball", "waterpolo"),
        ("volley", "badminton"), ("badminton", "squash"), ("tennis", "padel"),
        ("padel", "squash"), ("ping-pong", "badminton"), ("hockey", "crosse"),
        ("golf", "croquet"), ("pétanque", "bowling"), ("bowling", "curling"),
        ("baseball", "cricket"), ("natation", "plongeon"), ("aviron", "canoë"),
        ("surf", "bodyboard"), ("kitesurf", "wakeboard"), ("course", "marche"),
        ("sprint", "marathon"), ("haies", "steeple"), ("perche", "hauteur"),
        ("javelot", "disque"), ("disque", "marteau"), ("poids", "javelot"),
        ("escalade", "randonnée"), ("randonnée", "trekking"), ("alpinisme", "spéléologie"),
        ("ski", "snowboard"), ("patinage", "luge"), ("bobsleigh", "skeleton"),
        ("boxe", "judo"), ("judo", "karaté"), ("karaté", "taekwondo"),
        ("lutte", "sumo"), ("équitation", "polo"), ("cyclisme", "BMX"),
        ("danse", "gymnastique"), ("gymnastique", "trampoline"), ("yoga", "pilates"),
        ("musculation", "crossfit"), ("aérobic", "zumba"), ("parkour", "acrobatie"),
        ("football", "hockey"), ("tennis", "golf"), ("boxe", "lutte"),
        ("natation", "aviron"), ("ski", "patinage"), ("escalade", "spéléologie"),
        ("danse", "trampoline"), ("yoga", "musculation"), ("marathon", "steeple"),
        ("bowling", "croquet"), ("surf", "kitesurf"), ("judo", "sumo"),
        ("cyclisme", "équitation"), ("volley", "baseball"), ("randonnée", "alpinisme"),
        ("curling", "pétanque"), ("acrobatie", "zumba"),
    ),
    "Équipement sportif": (
        ("raquette", "batte"), ("batte", "crosse"), ("filet", "but"),
        ("but", "panier"), ("panier", "poteau"), ("casque", "genouillère"),
        ("coudière", "genouillère"), ("maillot", "dossard"), ("short", "cuissard"),
        ("chronomètre", "sifflet"), ("sifflet", "drapeau"), ("coupe", "ceinture"),
        ("podium", "tribune"), ("vestiaire", "gradin"), ("terrain", "piste"),
        ("piste", "couloir"), ("tapis", "ring"), ("ring", "tatami"),
        ("agrès", "barre"), ("haltère", "kettlebell"), ("corde", "élastique"),
        ("tremplin", "plongeoir"), ("mousqueton", "baudrier"), ("bâton", "fixation"),
        ("arc", "arbalète"), ("selle", "étrier"),
    ),
    "Jeux": (
        ("échecs", "shogi"), ("dames", "othello"), ("go", "backgammon"),
        ("cartes", "tarot"), ("tarot", "belote"), ("poker", "rami"),
        ("dominos", "mahjong"), ("dés", "yams"), ("toupie", "yoyo"),
        ("bille", "osselet"), ("scrabble", "boggle"), ("monopoly", "cluedo"),
        ("cluedo", "risk"), ("puzzle", "labyrinthe"), ("billard", "fléchettes"),
        ("baby-foot", "flipper"), ("console", "manette"), ("borne", "simulateur"),
        ("cerf-volant", "boomerang"), ("frisbee", "boomerang"), ("marelle", "élastique"),
        ("balançoire", "toboggan"), ("bascule", "manège"), ("poupée", "peluche"),
        ("peluche", "marionnette"), ("robot", "figurine"), ("cube", "brique"),
        ("ballon", "cerceau"), ("corde", "diabolo"), ("kaléidoscope", "toupie"),
        ("plateau", "damier"),
    ),
    "Métiers": (
        ("médecin", "infirmier"), ("infirmier", "aide-soignant"), ("chirurgien", "anesthésiste"),
        ("pharmacien", "biologiste"), ("vétérinaire", "zoologiste"), ("opticien", "audioprothésiste"),
        ("sage-femme", "pédiatre"), ("boulanger", "pâtissier"), ("pâtissier", "chocolatier"),
        ("boucher", "charcutier"), ("charcutier", "traiteur"), ("poissonnier", "écailler"),
        ("cuisinier", "commis"), ("serveur", "barman"), ("barman", "sommelier"),
        ("primeur", "épicier"), ("berger", "agriculteur"), ("agriculteur", "maraîcher"),
        ("viticulteur", "brasseur"), ("apiculteur", "pisciculteur"), ("mineur", "carrier"),
        ("pêcheur", "marin"), ("pompier", "secouriste"), ("militaire", "légionnaire"),
        ("douanier", "vigile"), ("juge", "avocat"), ("notaire", "huissier"),
        ("greffier", "procureur"), ("facteur", "livreur"), ("chauffeur", "coursier"),
        ("éboueur", "cantonnier"), ("jardinier", "paysagiste"), ("pilote", "steward"),
        ("aiguilleur", "contrôleur"), ("architecte", "ingénieur"), ("plombier", "électricien"),
        ("électricien", "chauffagiste"), ("maçon", "charpentier"), ("charpentier", "menuisier"),
        ("menuisier", "ébéniste"), ("couvreur", "carreleur"), ("peintre", "plâtrier"),
        ("serrurier", "vitrier"), ("mécanicien", "carrossier"), ("soudeur", "chaudronnier"),
        ("horloger", "bijoutier"), ("cordonnier", "maroquinier"), ("esthéticienne", "manucure"),
        ("photographe", "cameraman"), ("écrivain", "traducteur"), ("libraire", "bibliothécaire"),
        ("éducateur", "animateur"), ("comptable", "banquier"), ("caissier", "vendeur"),
        ("acteur", "figurant"), ("chanteur", "musicien"), ("danseur", "chorégraphe"),
        ("clown", "acrobate"), ("arbitre", "entraîneur"), ("guide", "réceptionniste"),
        ("archéologue", "géologue"), ("astronome", "météorologue"), ("boulanger", "boucher"),
        ("cuisinier", "serveur"), ("médecin", "pharmacien"), ("dentiste", "opticien"),
        ("pompier", "douanier"), ("juge", "notaire"), ("facteur", "chauffeur"),
        ("jardinier", "éboueur"), ("pilote", "marin"), ("architecte", "comptable"),
        ("plombier", "serrurier"), ("maçon", "couvreur"), ("peintre", "vitrier"),
        ("horloger", "cordonnier"), ("coiffeur", "manucure"), ("photographe", "écrivain"),
        ("acteur", "danseur"), ("libraire", "épicier"), ("berger", "apiculteur"),
        ("mineur", "bûcheron"), ("astronome", "géologue"), ("vétérinaire", "biologiste"),
        ("guide", "arbitre"), ("clown", "musicien"),
    ),
    "Instruments": (
        ("piano", "clavecin"), ("clavecin", "orgue"), ("orgue", "harmonium"),
        ("guitare", "banjo"), ("banjo", "mandoline"), ("ukulélé", "mandoline"),
        ("violon", "alto"), ("alto", "violoncelle"), ("violoncelle", "contrebasse"),
        ("harpe", "cithare"), ("tambour", "timbale"), ("cymbale", "gong"),
        ("triangle", "maracas"), ("xylophone", "marimba"), ("marimba", "vibraphone"),
        ("saxophone", "clarinette"), ("clarinette", "hautbois"), ("hautbois", "basson"),
        ("flûte", "piccolo"), ("trompette", "cornet"), ("cornet", "bugle"),
        ("trombone", "tuba"), ("cor", "tuba"), ("accordéon", "bandonéon"),
        ("harmonica", "mélodica"), ("synthétiseur", "sampler"), ("archet", "médiator"),
        ("corde", "anche"), ("touche", "pédale"), ("partition", "tablature"),
        ("métronome", "diapason"), ("pupitre", "étui"), ("piano", "guitare"),
        ("violon", "trompette"), ("harpe", "tambour"), ("flûte", "cymbale"),
        ("orgue", "banjo"), ("saxophone", "xylophone"), ("accordéon", "harmonica"),
        ("tuba", "contrebasse"), ("clarinette", "gong"), ("archet", "partition"),
        ("métronome", "étui"), ("clavecin", "ukulélé"), ("basson", "piccolo"),
        ("trombone", "vibraphone"),
    ),
    "Musique et spectacle": (
        ("rock", "punk"), ("punk", "metal"), ("metal", "grunge"),
        ("jazz", "blues"), ("blues", "soul"), ("soul", "funk"),
        ("rap", "slam"), ("pop", "disco"), ("disco", "house"),
        ("techno", "trance"), ("reggae", "ska"), ("folk", "country"),
        ("country", "bluegrass"), ("classique", "baroque"), ("opéra", "opérette"),
        ("symphonie", "concerto"), ("concerto", "sonate"), ("chorale", "orchestre"),
        ("orchestre", "fanfare"), ("mélodie", "harmonie"), ("concert", "festival"),
        ("festival", "tournée"), ("cirque", "cabaret"), ("cabaret", "revue"),
        ("théâtre", "opéra"), ("mime", "marionnette"), ("magie", "hypnose"),
        ("jonglage", "équilibrisme"), ("chapiteau", "estrade"), ("projecteur", "micro"),
        ("rideau", "décor"), ("costume", "maquillage"), ("répétition", "générale"),
        ("applaudissement", "rappel"), ("billet", "programme"),
    ),
    "Arts et loisirs créatifs": (
        ("peinture", "aquarelle"), ("aquarelle", "gouache"), ("gouache", "acrylique"),
        ("huile", "pastel"), ("fusain", "sanguine"), ("encre", "lavis"),
        ("sculpture", "modelage"), ("céramique", "faïence"), ("porcelaine", "grès"),
        ("gravure", "sérigraphie"), ("mosaïque", "vitrail"), ("fresque", "graffiti"),
        ("collage", "origami"), ("tricot", "crochet"), ("crochet", "macramé"),
        ("couture", "broderie"), ("broderie", "patchwork"), ("tissage", "tapisserie"),
        ("montage", "retouche"), ("caricature", "portrait"), ("toile", "chevalet"),
        ("palette", "godet"), ("crayon", "feutre"), ("moule", "empreinte"),
        ("galerie", "atelier"), ("vernissage", "exposition"),
    ),
    "École": (
        ("gomme", "correcteur"), ("règle", "équerre"), ("compas", "rapporteur"),
        ("cahier", "classeur"), ("classeur", "chemise"), ("agenda", "carnet"),
        ("colle", "scotch"), ("agrafeuse", "perforatrice"), ("ciseaux", "cutter"),
        ("cartable", "trousse"), ("calculatrice", "abaque"), ("tableau", "ardoise"),
        ("craie", "marqueur"), ("pupitre", "estrade"), ("cantine", "internat"),
        ("maths", "physique"), ("chimie", "biologie"), ("géologie", "astronomie"),
        ("histoire", "philosophie"), ("géographie", "économie"), ("anglais", "espagnol"),
        ("allemand", "italien"), ("latin", "grec"), ("grammaire", "orthographe"),
        ("conjugaison", "vocabulaire"), ("rédaction", "dictée"), ("exposé", "mémoire"),
        ("examen", "concours"), ("note", "moyenne"), ("bulletin", "carnet"),
        ("leçon", "chapitre"), ("manuel", "dictionnaire"), ("dictionnaire", "encyclopédie"),
        ("bibliothèque", "médiathèque"), ("diplôme", "certificat"), ("cahier", "trousse"),
        ("cartable", "agenda"), ("tableau", "estrade"), ("maths", "géographie"),
        ("chimie", "philosophie"), ("latin", "italien"), ("dictée", "exposé"),
        ("note", "bulletin"), ("manuel", "encyclopédie"), ("grammaire", "conjugaison"),
        ("internat", "médiathèque"), ("scotch", "agrafeuse"), ("marqueur", "cutter"),
    ),
    "Bureau et informatique": (
        ("ordinateur", "tablette"), ("imprimante", "scanner"), ("photocopieuse", "fax"),
        ("serveur", "routeur"), ("routeur", "modem"), ("câble", "adaptateur"),
        ("fichier", "dossier"), ("document", "tableur"), ("diaporama", "affiche"),
        ("site", "blog"), ("virus", "pare-feu"), ("corbeille", "archive"),
        ("raccourci", "menu"), ("onglet", "fenêtre"), ("classeur", "parapheur"),
        ("tampon", "signature"), ("facture", "devis"), ("contrat", "avenant"),
        ("réunion", "entretien"), ("planning", "échéance"), ("badge", "pointeuse"),
    ),
    "Ville et commerces": (
        ("boulangerie", "pâtisserie"), ("épicerie", "supérette"), ("librairie", "papeterie"),
        ("kiosque", "tabac"), ("institut", "spa"), ("banque", "assurance"),
        ("poste", "pressing"), ("marché", "brocante"), ("brocante", "vide-grenier"),
        ("fleuriste", "jardinerie"), ("restaurant", "brasserie"), ("cantine", "self"),
        ("bijouterie", "parfumerie"), ("quincaillerie", "droguerie"), ("garage", "concession"),
        ("station-service", "lavage"), ("mairie", "préfecture"), ("commissariat", "caserne"),
        ("tribunal", "prison"), ("collège", "lycée"), ("théâtre", "cinéma"),
        ("musée", "galerie"), ("stade", "gymnase"), ("piscine", "patinoire"),
        ("impasse", "ruelle"), ("rond-point", "carrefour"), ("feu", "panneau"),
        ("lampadaire", "borne"), ("parking", "aire"), ("boulangerie", "quincaillerie"),
        ("pharmacie", "papeterie"), ("banque", "poste"), ("restaurant", "self"),
        ("musée", "cinéma"), ("stade", "piscine"), ("mairie", "tribunal"),
        ("caserne", "prison"), ("collège", "gymnase"), ("fleuriste", "bijouterie"),
        ("parking", "carrefour"), ("feu", "rond-point"), ("spa", "pressing"),
        ("galerie", "patinoire"),
    ),
    "Bâtiments et monuments": (
        ("château", "palais"), ("palais", "manoir"), ("manoir", "villa"),
        ("chaumière", "cabane"), ("chalet", "bungalow"), ("immeuble", "gratte-ciel"),
        ("tour", "beffroi"), ("basilique", "abbaye"), ("chapelle", "oratoire"),
        ("mosquée", "synagogue"), ("temple", "pagode"), ("donjon", "rempart"),
        ("douve", "pont-levis"), ("moulin", "silo"), ("aqueduc", "viaduc"),
        ("colonne", "obélisque"), ("obélisque", "stèle"), ("statue", "buste"),
        ("pyramide", "mausolée"), ("fresque", "bas-relief"), ("voûte", "arcade"),
        ("fondation", "charpente"),
    ),
    "Voyage": (
        ("bagage", "colis"), ("passeport", "visa"), ("billet", "réservation"),
        ("hôtel", "auberge"), ("auberge", "gîte"), ("camping", "bivouac"),
        ("tente", "caravane"), ("croisière", "circuit"), ("séjour", "escale"),
        ("guichet", "comptoir"), ("douane", "contrôle"), ("carte", "boussole"),
        ("boussole", "GPS"), ("itinéraire", "détour"), ("étape", "halte"),
        ("guide", "brochure"), ("devise", "change"), ("pourboire", "taxe"),
        ("chambre", "dortoir"), ("réception", "conciergerie"), ("plage", "station"),
        ("gourde", "thermos"), ("lampe", "frontale"), ("duvet", "matelas"),
        ("réchaud", "popote"),
    ),
    "Fêtes et célébrations": (
        ("mariage", "fiançailles"), ("baptême", "communion"), ("noces", "banquet"),
        ("banquet", "buffet"), ("réception", "cocktail"), ("bal", "soirée"),
        ("carnaval", "défilé"), ("guirlande", "banderole"), ("confetti", "serpentin"),
        ("ballon", "lampion"), ("bougie", "cierge"), ("emballage", "ruban"),
        ("carte", "invitation"), ("discours", "toast"), ("masque", "perruque"),
        ("sapin", "crèche"), ("cloche", "trompette"), ("vœux", "résolution"),
        ("manège", "stand"), ("tirage", "récompense"),
    ),
    "Temps et calendrier": (
        ("seconde", "minute"), ("heure", "journée"), ("matin", "après-midi"),
        ("midi", "goûter"), ("soirée", "veillée"), ("semaine", "quinzaine"),
        ("mois", "trimestre"), ("saison", "semestre"), ("année", "décennie"),
        ("décennie", "siècle"), ("siècle", "millénaire"), ("printemps", "automne"),
        ("été", "hiver"), ("veille", "surlendemain"), ("montre", "chronomètre"),
        ("calendrier", "almanach"), ("agenda", "planning"), ("date", "échéance"),
        ("délai", "attente"),
    ),
    "Communication": (
        ("lettre", "carte"), ("colis", "recommandé"), ("timbre", "cachet"),
        ("enveloppe", "étiquette"), ("appel", "message"), ("sonnerie", "vibreur"),
        ("affiche", "panneau"), ("journal", "magazine"), ("article", "chronique"),
        ("titre", "légende"), ("interview", "reportage"), ("émission", "podcast"),
        ("insulte", "moquerie"), ("blague", "anecdote"), ("code", "signal"),
        ("geste", "mimique"),
    ),
    "Contenants": (
        ("caisse", "cageot"), ("corbeille", "hotte"), ("bocal", "pot"),
        ("fiole", "ampoule"), ("bouteille", "carafe"), ("bidon", "jerrican"),
        ("enveloppe", "pochette"), ("tube", "cartouche"), ("cornet", "gobelet"),
        ("plateau", "corbeille"), ("filet", "sacoche"), ("valise", "cantine"),
        ("urne", "tirelire"), ("coffre-fort", "casier"),
    ),
    "Matières": (
        ("chêne", "contreplaqué"), ("marbre", "granit"), ("granit", "ardoise"),
        ("sable", "gravier"), ("gravier", "galet"), ("brique", "torchis"),
        ("fer", "fonte"), ("aluminium", "zinc"), ("cuivre", "laiton"),
        ("plomb", "étain"), ("plastique", "résine"), ("caoutchouc", "latex"),
        ("papier", "carton"), ("carton", "parchemin"), ("tissu", "feutre"),
        ("cuir", "daim"), ("fourrure", "peau"), ("laine", "cachemire"),
        ("nylon", "polyester"), ("mousse", "ouate"), ("liège", "paille"),
        ("cire", "résine"), ("charbon", "tourbe"), ("pétrole", "goudron"),
    ),
    "Formes et couleurs": (
        ("rouge", "bordeaux"), ("bordeaux", "grenat"), ("rose", "fuchsia"),
        ("orange", "corail"), ("jaune", "moutarde"), ("moutarde", "ocre"),
        ("olive", "kaki"), ("bleu", "indigo"), ("indigo", "marine"),
        ("marron", "beige"), ("beige", "taupe"), ("noir", "anthracite"),
        ("carré", "losange"), ("losange", "trapèze"), ("cercle", "ovale"),
        ("sphère", "cylindre"), ("cylindre", "cône"), ("cube", "prisme"),
        ("rayure", "carreau"), ("pois", "damier"), ("motif", "arabesque"),
    ),
    "Argent et commerce": (
        ("euro", "dollar"), ("caisse", "tirelire"), ("facture", "ticket"),
        ("reçu", "quittance"), ("vente", "enchère"), ("épargne", "placement"),
        ("intérêt", "dividende"), ("salaire", "prime"), ("prime", "pourboire"),
        ("budget", "dépense"), ("fortune", "héritage"), ("banque", "coffre"),
        ("guichet", "distributeur"), ("stock", "inventaire"), ("étal", "vitrine"),
    ),
    "Récits et imaginaire": (
        ("conte", "fable"), ("poème", "chanson"), ("épopée", "saga"),
        ("intrigue", "péripétie"), ("héros", "aventurier"), ("chevalier", "écuyer"),
        ("roi", "empereur"), ("reine", "impératrice"), ("prince", "duc"),
        ("duc", "comte"), ("seigneur", "vassal"), ("sorcière", "fée"),
        ("fée", "nymphe"), ("géant", "ogre"), ("dragon", "hydre"),
        ("licorne", "pégase"), ("griffon", "sphinx"), ("vampire", "loup-garou"),
        ("zombie", "momie"), ("détective", "espion"), ("bouffon", "ménestrel"),
        ("baguette", "grimoire"), ("quête", "épreuve"),
    ),
    "Objets du quotidien": (
        ("porte-clés", "breloque"), ("bougie", "lanterne"), ("aiguille", "épingle"),
        ("trombone", "agrafe"), ("punaise", "aimant"), ("crochet", "clou"),
        ("chiffon", "lingette"), ("balai", "plumeau"), ("éponge", "brosse"),
        ("gant", "tablier"), ("nappe", "set"), ("thermos", "glacière"),
        ("réveil", "minuteur"), ("télécommande", "manette"), ("cintre", "portant"),
        ("fer", "planche"), ("miroir", "loupe"), ("loupe", "jumelles"),
    ),
    "Sons et bruits": (
        ("tintement", "carillon"), ("sifflement", "bourdonnement"), ("ronflement", "râle"),
        ("gargouillis", "clapotis"), ("miaulement", "ronronnement"), ("hennissement", "braiment"),
        ("meuglement", "bêlement"), ("gazouillis", "pépiement"), ("croassement", "caquètement"),
        ("sifflet", "cor"), ("chuchotement", "soupir"), ("applaudissement", "huée"),
        ("mélodie", "berceuse"), ("hymne", "marche"),
    ),
    "Mouvements": (
        ("chute", "glissade"), ("nage", "plongeon"), ("valse", "tango"),
        ("pirouette", "entrechat"), ("virage", "demi-tour"), ("galop", "trot"),
    ),
    "Armes et défense": (
        ("épée", "sabre"), ("sabre", "rapière"), ("rapière", "fleuret"),
        ("hache", "hallebarde"), ("fléau", "masse"), ("flèche", "carreau"),
        ("fronde", "lance-pierre"), ("catapulte", "baliste"), ("bélier", "trébuchet"),
        ("gantelet", "brassard"), ("fourreau", "carquois"), ("canon", "mortier"),
        ("grenade", "obus"), ("rempart", "meurtrière"), ("tranchée", "abri"),
    ),
    "Histoire et société": (
        ("royaume", "empire"), ("empire", "république"), ("colonie", "comptoir"),
        ("traité", "alliance"), ("siège", "assaut"), ("noble", "bourgeois"),
        ("paysan", "serf"), ("artisan", "marchand"), ("marché", "foire"),
        ("expédition", "conquête"), ("vestige", "fouille"), ("manuscrit", "parchemin"),
        ("sceau", "blason"), ("trône", "sceptre"), ("loi", "décret"),
        ("tribunal", "assemblée"), ("vote", "scrutin"), ("citoyen", "sujet"),
        ("frontière", "province"),
    ),
    "Enfance": (
        ("berceau", "landau"), ("bavoir", "body"), ("hochet", "mobile"),
        ("parc", "trotteur"), ("toboggan", "tourniquet"), ("cerceau", "quilles"),
        ("craie", "gommette"), ("déguisement", "grimage"), ("goûter", "compote"),
        ("cour", "préau"), ("récré", "sieste"),
    ),
    "Nettoyage et entretien": (
        ("seau", "chariot"), ("aspirateur", "souffleur"), ("lessive", "assouplissant"),
        ("repassage", "pliage"), ("moisissure", "calcaire"), ("désodorisant", "encens"),
        ("compost", "recyclage"), ("conteneur", "benne"),
    ),
    "Traits de caractère": (
        ("bavard", "gourmand"), ("timide", "distrait"), ("généreux", "drôle"),
        ("avare", "râleur"), ("courageux", "patient"), ("peureux", "coquet"),
        ("paresseux", "naïf"), ("travailleur", "discret"), ("menteur", "moqueur"),
        ("honnête", "économe"), ("gentil", "ordonné"), ("sévère", "ponctuel"),
        ("curieux", "maladroit"), ("habile", "solitaire"), ("têtu", "rêveur"),
        ("modeste", "sociable"), ("nerveux", "dépensier"), ("prudent", "brouillon"),
        ("audacieux", "bienveillant"), ("méfiant", "bruyant"), ("orgueilleux", "frileux"),
        ("indulgent", "impulsif"), ("posé", "négligé"), ("attentif", "conciliant"),
    ),
    "Cinéma et télévision": (
        ("film", "série"), ("épisode", "saison"), ("bande-annonce", "générique"),
        ("scénario", "storyboard"), ("réalisateur", "producteur"), ("caméra", "perche"),
        ("figurant", "cascadeur"), ("doublure", "cascadeur"), ("comédie", "thriller"),
        ("western", "péplum"), ("horreur", "fantastique"), ("animation", "marionnette"),
        ("court-métrage", "clip"), ("montage", "mixage"), ("sous-titre", "doublage"),
        ("salle", "écran"), ("séance", "avant-première"), ("critique", "palmarès"),
        ("prix", "nomination"), ("acteur", "réalisateur"), ("costumier", "maquilleur"),
        ("décor", "accessoire"), ("perruque", "prothèse"),
    ),
    "Livres et écriture": (
        ("roman", "essai"), ("chapitre", "paragraphe"), ("sommaire", "index"),
        ("couverture", "jaquette"), ("marge", "interligne"), ("virgule", "tiret"),
        ("parenthèse", "guillemet"), ("accent", "cédille"), ("rime", "vers"),
        ("strophe", "refrain"), ("métaphore", "comparaison"), ("narrateur", "personnage"),
        ("brouillon", "manuscrit"), ("éditeur", "imprimeur"), ("tirage", "édition"),
        ("plume", "encrier"), ("papyrus", "tablette"),
    ),
    "Croyances et rites": (
        ("prière", "chant"), ("messe", "office"), ("sermon", "prêche"),
        ("pèlerinage", "procession"), ("jeûne", "abstinence"), ("offrande", "sacrifice"),
        ("autel", "reliquaire"), ("icône", "statuette"), ("encens", "myrrhe"),
        ("chapelet", "amulette"), ("talisman", "amulette"), ("prophète", "apôtre"),
        ("moine", "ermite"), ("prêtre", "rabbin"), ("imam", "pasteur"),
        ("nonne", "novice"), ("croyant", "pèlerin"), ("miracle", "révélation"),
        ("légende", "parabole"), ("rite", "coutume"), ("superstition", "présage"),
        ("horoscope", "tarot"), ("boule", "pendule"),
    ),
    "Camping et plein air": (
        ("tente", "tipi"), ("sardine", "piquet"), ("duvet", "couverture"),
        ("réchaud", "brasero"), ("gamelle", "assiette"), ("couteau", "multitool"),
        ("boussole", "altimètre"), ("gourde", "filtre"), ("lampe", "bougie"),
        ("trousse", "attelle"), ("feu", "braise"), ("fumée", "étincelle"),
        ("sac", "bâche"), ("moustiquaire", "répulsif"), ("jumelles", "longue-vue"),
        ("nœud", "boucle"), ("sentier", "balise"), ("refuge", "bivouac"),
    ),
    "Pêche et chasse": (
        ("canne", "moulinet"), ("hameçon", "leurre"), ("appât", "amorce"),
        ("flotteur", "plomb"), ("épuisette", "nasse"), ("harpon", "foène"),
        ("cuissarde", "waders"), ("vivier", "seau"), ("truite", "gardon"),
        ("gardon", "goujon"), ("silure", "sandre"), ("étang", "réservoir"),
        ("berge", "ponton"), ("affût", "battue"), ("meute", "chien"),
        ("cor", "trompe"), ("gibecière", "carnier"), ("cartouche", "douille"),
        ("piège", "collet"), ("perdreau", "bécasse"), ("lièvre", "lapin"),
        ("chevreuil", "marcassin"), ("permis", "quota"), ("saison", "ouverture"),
    ),
    "Coiffure et beauté": (
        ("mèche", "frange"), ("chignon", "tresse"), ("tresse", "natte"),
        ("queue", "couette"), ("raie", "épi"), ("teinture", "mèches"),
        ("balayage", "coloration"), ("permanente", "lissage"), ("gel", "laque"),
        ("ciseaux", "rasoir"), ("cape", "serviette"), ("bac", "fauteuil"),
        ("crème", "sérum"), ("blush", "highlighter"), ("crayon", "khôl"),
        ("pinceau", "éponge"), ("manucure", "pédicure"), ("lime", "polissoir"),
        ("épilation", "rasage"),
    ),
    "Justice et administration": (
        ("plainte", "recours"), ("procès", "audience"), ("verdict", "sentence"),
        ("peine", "sanction"), ("preuve", "témoignage"), ("témoin", "juré"),
        ("accusé", "prévenu"), ("plaidoirie", "réquisitoire"), ("appel", "cassation"),
        ("dossier", "pièce"), ("acte", "titre"), ("attestation", "justificatif"),
        ("formulaire", "questionnaire"), ("timbre", "vignette"), ("registre", "cadastre"),
        ("permis", "licence"), ("licence", "agrément"), ("mandat", "procuration"),
        ("caution", "garantie"), ("bail", "location"), ("expulsion", "saisie"),
        ("prison", "détention"), ("cellule", "parloir"), ("gardien", "surveillant"),
    ),
    "Cuisine du monde": (
        ("tapas", "mezzé"), ("antipasti", "tapas"), ("ramen", "pho"),
        ("bibimbap", "donburi"), ("falafel", "houmous"), ("shawarma", "gyros"),
        ("empanada", "arepa"), ("burrito", "quesadilla"), ("guacamole", "salsa"),
        ("ceviche", "tartare"), ("goulash", "borchtch"), ("moussaka", "parmigiana"),
        ("gaspacho", "vichyssoise"), ("bortsch", "minestrone"), ("polenta", "semoule"),
        ("naan", "pita"), ("tortilla", "galette"), ("bagel", "bretzel"),
        ("scone", "muffin"), ("baklava", "loukoum"), ("mochi", "dorayaki"),
        ("wasabi", "raifort"), ("kimchi", "pickles"),
    ),
    "Bébés animaux et groupes": (
        ("chaton", "chiot"), ("poulain", "ânon"), ("veau", "cabri"),
        ("porcelet", "agnelet"), ("faon", "marcassin"), ("ourson", "louveteau"),
        ("lionceau", "tigreau"), ("éléphanteau", "girafon"), ("têtard", "alevin"),
        ("larve", "nymphe"), ("troupeau", "harde"), ("meute", "horde"),
        ("nuée", "essaim"), ("volée", "nichée"), ("portée", "couvée"),
        ("terrier", "tanière"), ("gîte", "hutte"), ("ruche", "guêpier"),
        ("aquarium", "volière"), ("écurie", "chenil"), ("chenil", "clapier"),
    ),
    "Photographie": (
        ("objectif", "zoom"), ("flash", "réflecteur"), ("trépied", "monopode"),
        ("pellicule", "capteur"), ("obturateur", "diaphragme"), ("netteté", "profondeur"),
        ("contraste", "luminosité"), ("filtre", "gélatine"), ("portrait", "paysage"),
        ("selfie", "autoportrait"), ("album", "tirage"), ("négatif", "diapositive"),
        ("pose", "instantané"),
    ),
    "Roches et minéraux": (
        ("basalte", "obsidienne"), ("calcaire", "craie"), ("silex", "quartz"),
        ("schiste", "gneiss"), ("grès", "meulière"), ("gypse", "albâtre"),
        ("mica", "feldspath"), ("agate", "onyx"), ("jade", "turquoise"),
        ("ambre", "jais"), ("opale", "lapis"), ("pyrite", "galène"),
        ("filon", "veine"), ("carrière", "mine"), ("fossile", "empreinte"),
        ("cristal", "géode"), ("lave", "magma"), ("sédiment", "alluvion"),
    ),
    "Astronomie": (
        ("lune", "croissant"), ("éclipse", "transit"), ("constellation", "zodiaque"),
        ("mercure", "vénus"), ("mars", "jupiter"), ("saturne", "uranus"),
        ("neptune", "pluton"), ("anneau", "satellite"), ("cratère", "mer"),
        ("marée", "phase"), ("équinoxe", "solstice"), ("astrolabe", "sextant"),
        ("coupole", "monture"), ("oculaire", "miroir"), ("année-lumière", "parsec"),
        ("nébuleuse", "quasar"),
    ),
    "Danse": (
        ("salsa", "bachata"), ("rumba", "cha-cha"), ("flamenco", "sévillane"),
        ("claquettes", "charleston"), ("swing", "lindy"), ("hip-hop", "breakdance"),
        ("classique", "contemporain"), ("jazz", "modern"), ("folklore", "sarabande"),
        ("menuet", "gavotte"), ("polka", "mazurka"), ("quadrille", "farandole"),
        ("pirouette", "arabesque"), ("jeté", "plié"), ("tutu", "justaucorps"),
        ("chorégraphie", "improvisation"), ("duo", "ensemble"), ("bal", "guinguette"),
    ),
    "Vin et gastronomie": (
        ("cépage", "terroir"), ("vendange", "pressurage"), ("fût", "cuve"),
        ("carafe", "décanteur"), ("millésime", "assemblage"), ("tanin", "acidité"),
        ("bouquet", "finale"), ("dégustation", "accord"), ("cave", "chai"),
        ("sommelier", "caviste"), ("apéritif", "amuse-bouche"), ("nappe", "argenterie"),
        ("plat", "garniture"), ("sauce", "jus"), ("cuisson", "marinade"),
        ("dressage", "assaisonnement"), ("étoile", "toque"), ("brigade", "commis"),
        ("pourboire", "addition"),
    ),
    "Textile et couture": (
        ("bobine", "canette"), ("patron", "gabarit"), ("ourlet", "surpiqûre"),
        ("couture", "surjet"), ("fermeture", "pression"), ("bouton", "œillet"),
        ("biais", "passepoil"), ("doublure", "entoilage"), ("machine", "surjeteuse"),
        ("mannequin", "buste"), ("écheveau", "pelote"), ("maille", "point"),
        ("jersey", "molleton"), ("tweed", "flanelle"), ("popeline", "batiste"),
        ("jacquard", "chenille"), ("teinture", "impression"),
    ),
    "Secours et sécurité": (
        ("alarme", "sirène"), ("extincteur", "lance"), ("civière", "brancard"),
        ("garrot", "compresse"), ("défibrillateur", "oxygène"), ("gyrophare", "avertisseur"),
        ("barrage", "cordon"), ("balise", "fumigène"), ("secouriste", "brancardier"),
        ("caserne", "poste"), ("exercice", "alerte"), ("issue", "sas"),
        ("plan", "consigne"), ("talkie", "radio"), ("maître-nageur", "surveillant"),
    ),
    "Bureau de poste et papeterie": (
        ("ramette", "bloc"), ("intercalaire", "onglet"), ("reliure", "spirale"),
        ("massicot", "cutter"), ("règle", "pochoir"), ("encre", "cartouche"),
        ("buvard", "sous-verre"), ("étiquette", "gommette"), ("élastique", "attache"),
        ("porte-mine", "recharge"), ("surligneur", "stabilo"), ("carnet", "répertoire"),
        ("calendrier", "éphéméride"), ("globe", "planisphère"), ("tampon", "encreur"),
        ("balance", "affranchissement"),
    ),
    "Marché et étal": (
        ("bâche", "auvent"), ("balance", "poids"), ("primeur", "maraîcher"),
        ("crémier", "affineur"), ("volailler", "tripier"), ("rôtisseur", "traiteur"),
        ("criée", "enchère"), ("monnaie", "appoint"), ("caissette", "barquette"),
        ("glacière", "vitrine"),
    ),
    "Ferme et récolte": (
        ("moisson", "fenaison"), ("labour", "hersage"), ("sillon", "andain"),
        ("épi", "gerbe"), ("botte", "balle"), ("grain", "son"),
        ("meule", "silo"), ("batteuse", "ensileuse"), ("semoir", "épandeur"),
        ("étable", "stabulation"), ("traite", "tank"), ("pis", "trayon"),
        ("verger", "houblonnière"), ("rucher", "hausse"), ("pressoir", "alambic"),
        ("cidrerie", "distillerie"), ("greffe", "taille"), ("échalas", "palissage"),
    ),
    "Races et robes": (
        ("caniche", "teckel"), ("labrador", "beagle"), ("bouledogue", "carlin"),
        ("chihuahua", "yorkshire"), ("dalmatien", "dogue"), ("lévrier", "épagneul"),
        ("terrier", "setter"), ("siamois", "persan"), ("angora", "sphynx"),
        ("tigré", "tacheté"), ("moucheté", "pommelé"), ("bai", "alezan"),
        ("pie", "isabelle"), ("percheron", "pur-sang"), ("poney", "trait"),
        ("holstein", "charolaise"), ("limousine", "normande"), ("mérinos", "romanov"),
        ("leghorn", "wyandotte"),
    ),
    "Pain et viennoiserie": (
        ("miche", "boule"), ("bâtard", "flûte"), ("complet", "céréales"),
        ("seigle", "sarrasin"), ("levain", "poolish"), ("pétrin", "façonnage"),
        ("fournil", "banneton"), ("lame", "grigne"), ("croûton", "chapelure"),
        ("biscotte", "melba"), ("chouquette", "sacristain"), ("palmier", "torsade"),
        ("kouglof", "panettone"), ("stollen", "pandoro"), ("gaufrette", "tuile"),
    ),
    "Écrans et réseaux": (
        ("pixel", "résolution"), ("téléchargement", "diffusion"), ("abonnement", "essai"),
        ("profil", "avatar"), ("publication", "commentaire"), ("notification", "alerte"),
        ("émoji", "autocollant"), ("filtre", "effet"), ("story", "direct"),
        ("chaîne", "playlist"), ("wifi", "données"), ("antenne", "relais"),
        ("forfait", "recharge"), ("cadenas", "certificat"), ("cookie", "historique"),
        ("bug", "panne"), ("redémarrage", "réinitialisation"),
    ),
    "Décoration": (
        ("guirlande", "photophore"), ("bibelot", "figurine"), ("moulure", "corniche"),
        ("plinthe", "chambranle"), ("tenture", "voilage"), ("embrasse", "tringle"),
        ("descente", "carpette"), ("pouf", "repose-pied"), ("desserte", "sellette"),
        ("vitrine", "étagère"), ("bougeoir", "chandelier"), ("brûle-parfum", "diffuseur"),
        ("sculpture", "totem"), ("terrarium", "aquarium"), ("mobile", "attrape-rêves"),
    ),
    "Bricolage : mesures": (
        ("centimètre", "pouce"), ("gramme", "once"), ("litre", "pinte"),
        ("degré", "radian"), ("watt", "ampère"), ("volt", "ohm"),
        ("décibel", "hertz"), ("nœud", "mille"), ("hectare", "arpent"),
        ("tonne", "quintal"), ("baril", "boisseau"), ("carat", "titre"),
        ("épaisseur", "largeur"), ("volume", "surface"),
    ),
    "Épices et herbes": (
        ("aneth", "estragon"), ("sarriette", "marjolaine"), ("sauge", "verveine"),
        ("camomille", "tilleul"), ("badiane", "anis"), ("cumin", "carvi"),
        ("fenugrec", "sumac"), ("vanille", "tonka"), ("saumure", "marinade"),
    ),
    "Chaussures et cuir": (
        ("richelieu", "oxford"), ("brogue", "monk"), ("chelsea", "jodhpur"),
        ("compensée", "plateforme"), ("stiletto", "kitten"), ("trotteur", "derby"),
        ("cuissarde", "bottillon"), ("après-ski", "raquette"), ("charentaise", "babouche"),
        ("tannerie", "mégisserie"), ("croûte", "nubuck"), ("embauchoir", "chausse-pied"),
        ("trépointe", "contrefort"), ("bride", "salomé"),
    ),
    "Petits objets": (
        ("décapsuleur", "ouvre-boîte"), ("presse-ail", "dénoyauteur"), ("entonnoir", "louche"),
        ("écumoire", "araignée"), ("pilon", "fouet"), ("moulinette", "hachoir"),
        ("plumier", "écritoire"), ("boulier", "sablier"), ("clochette", "grelot"),
        ("sonnaille", "carillon"), ("boutonnière", "passant"), ("mousqueton", "anneau"),
        ("clapet", "valve"),
    ),
    "Sur la route": (
        ("autoroute", "nationale"), ("départementale", "chemin"), ("bretelle", "échangeur"),
        ("glissière", "muret"), ("ralentisseur", "chicane"), ("borne", "kilomètre"),
        ("bouchon", "ralentissement"), ("chantier", "cône"), ("tunnel", "viaduc"),
        ("dépanneuse", "remorquage"),
    ),
    "Encore des objets": (
        ("tabouret", "marchepied"), ("paravent", "claustra"), ("penderie", "vestiaire"),
        ("chevalet", "lutrin"), ("lutrin", "pupitre"), ("guéridon", "sellette"),
        ("hotte", "besace"), ("cruche", "pichet"), ("bassin", "cuvette"),
        ("écuelle", "gamelle"), ("timbale", "quart"), ("cafetière", "théière"),
        ("passoire", "égouttoir"), ("bougeoir", "photophore"), ("veilleuse", "lanterne"),
        ("chandelle", "torche"), ("soufflet", "tisonnier"), ("pelle", "balayette"),
        ("plumeau", "chiffon"), ("cintre", "housse"), ("besace", "musette"),
    ),
    "Encore des lieux": (
        ("belvédère", "kiosque"), ("pergola", "tonnelle"), ("perron", "porche"),
        ("préau", "auvent"), ("cour", "patio"), ("venelle", "passage"),
        ("promenade", "corniche"), ("quai", "berge"), ("écluse", "moulin"),
        ("lavoir", "abreuvoir"), ("puits", "citerne"), ("chapelle", "calvaire"),
        ("cimetière", "ossuaire"), ("crypte", "catacombe"), ("bastion", "échauguette"),
        ("guérite", "tourelle"), ("halle", "arcade"), ("estaminet", "guinguette"),
        ("pension", "villégiature"), ("hameau", "bourg"), ("faubourg", "quartier"),
    ),
    "Encore des mots": (
        ("linteau", "seuil"), ("faîtage", "arêtier"), ("torchère", "applique"),
        ("baldaquin", "alcôve"), ("paillasse", "plan"), ("enseigne", "devanture"),
        ("store", "banne"), ("perron", "emmarchement"), ("soupirail", "vasistas"),
        ("courette", "impasse"), ("colombage", "torchis"), ("chaume", "bardeau"),
        ("zinc", "cuivre"), ("crépi", "badigeon"), ("lambris", "boiserie"),
        ("rosace", "tympan"), ("gargouille", "chapiteau"), ("nef", "transept"),
        ("chœur", "abside"), ("cloître", "déambulatoire"), ("jubé", "chaire"),
        ("bénitier", "fonts"), ("vitrail", "verrière"), ("clocheton", "flèche"),
        ("contrefort", "arc-boutant"), ("créneau", "mâchicoulis"), ("herse", "poterne"),
        ("échauguette", "barbacane"), ("glacis", "talus"), ("motte", "enceinte"),
        ("logis", "dépendance"), ("orangerie", "volière"), ("potager", "verger"),
    ),
    "Champignons et sous-bois": (
        ("cèpe", "morille"), ("morille", "truffe"), ("girolle", "pleurote"),
        ("pleurote", "shiitaké"), ("bolet", "russule"), ("amanite", "coulemelle"),
        ("humus", "litière"), ("gland", "samare"), ("noisette", "faîne"),
        ("fougère", "muguet"), ("myrtille", "airelle"),
    ),
    "Céréales et graines": (
        ("blé", "épeautre"), ("épeautre", "sarrasin"), ("orge", "millet"),
        ("millet", "sorgho"), ("avoine", "riz"), ("quinoa", "amarante"),
        ("lentille", "fève"), ("fève", "haricot"), ("soja", "lupin"),
        ("tournesol", "sésame"), ("sésame", "pavot"), ("farine", "fécule"),
    ),
    "Vaisselle et table": (
        ("saladier", "compotier"), ("soupière", "légumier"), ("théière", "chocolatière"),
        ("sucrier", "beurrier"), ("huilier", "saucière"), ("ravier", "coupelle"),
        ("chope", "timbale"),
    ),
    "Éclairage": (
        ("lustre", "plafonnier"), ("plafonnier", "spot"), ("spot", "réglette"),
        ("lampadaire", "liseuse"), ("liseuse", "chevet"), ("torche", "frontale"),
        ("néon", "halogène"), ("halogène", "led"), ("douille", "abat-jour"),
        ("variateur", "détecteur"), ("chandelle", "flambeau"),
    ),
    "Plomberie et chauffage": (
        ("tuyau", "coude"), ("coude", "raccord"), ("raccord", "manchon"),
        ("vanne", "robinet"), ("siphon", "bonde"), ("bonde", "grille"),
        ("ballon", "cumulus"), ("radiateur", "convecteur"), ("thermostat", "sonde"),
        ("purgeur", "clapet"), ("joint", "collier"), ("mitigeur", "flexible"),
    ),
    "Électricité": (
        ("disjoncteur", "fusible"), ("tableau", "coffret"), ("va-et-vient", "télérupteur"),
        ("gaine", "goulotte"), ("transformateur", "onduleur"), ("panneau", "éolienne"),
        ("batterie", "générateur"), ("relais", "contacteur"), ("rallonge", "enrouleur"),
        ("multimètre", "testeur"),
    ),
    "Montagne": (
        ("piolet", "crampon"), ("mousqueton", "coinceur"), ("téléski", "télésiège"),
        ("télésiège", "télécabine"), ("névé", "sérac"), ("sérac", "crevasse"),
        ("aiguille", "pic"), ("pic", "dôme"), ("versant", "combe"),
    ),
    "Types de logements": (
        ("studio", "duplex"), ("duplex", "loft"), ("pavillon", "longère"),
        ("mas", "bastide"), ("bastide", "gentilhommière"), ("isba", "datcha"),
        ("igloo", "yourte"), ("yourte", "tipi"), ("péniche", "roulotte"),
        ("roulotte", "mobil-home"),
    ),
    "Sports d hiver": (
        ("slalom", "descente"), ("saut", "combiné"), ("bosses", "halfpipe"),
        ("raquette", "ski"), ("patin", "luge"), ("fart", "carre"),
        ("anorak", "salopette"),
    ),
    "Voix et chant": (
        ("soprano", "alto"), ("ténor", "baryton"), ("baryton", "basse"),
        ("choriste", "soliste"), ("vocalise", "gamme"), ("chorale", "quatuor"),
        ("canon", "polyphonie"), ("cantique", "psaume"), ("aria", "récitatif"),
    ),
    "Emballages": (
        ("palette", "conteneur"), ("film", "bulle"), ("calage", "polystyrène"),
        ("sangle", "cerclage"), ("opercule", "capsule"), ("blister", "coque"),
        ("bidon", "fût"), ("sachet", "dosette"), ("barquette", "coupelle"),
    ),
    "Poissons et coquillages": (
        ("dorade", "bar"), ("lieu", "merlan"), ("merlan", "églefin"),
        ("rouget", "grondin"), ("raie", "roussette"), ("espadon", "marlin"),
        ("flétan", "cabillaud"), ("éperlan", "ablette"), ("tanche", "barbeau"),
        ("omble", "corégone"), ("praire", "telline"), ("ormeau", "patelle"),
        ("tourteau", "étrille"), ("bulot", "murex"),
    ),
    "Fromages": (
        ("cantal", "salers"), ("reblochon", "morbier"), ("morbier", "tomme"),
        ("munster", "maroilles"), ("crottin", "picodon"), ("beaufort", "abondance"),
        ("emmental", "edam"), ("gouda", "cheddar"), ("parmesan", "pecorino"),
    ),
    "Motos et cycles": (
        ("trail", "enduro"), ("enduro", "motocross"), ("side-car", "trike"),
        ("guidon", "cintre"), ("fourche", "amortisseur"), ("chaîne", "courroie"),
        ("dérailleur", "moyeu"), ("garde-boue", "carter"), ("béquille", "porte-bagages"),
    ),
    "Jeux de cartes": (
        ("pique", "trèfle"), ("coeur", "carreau"), ("valet", "cavalier"),
        ("as", "joker"), ("belote", "coinche"), ("rami", "canasta"),
        ("bataille", "menteur"), ("pli", "levée"), ("mise", "relance"),
    ),
    "Au bord de l eau": (
        ("parasol", "tente"), ("serviette", "paréo"), ("bouée", "brassard"),
        ("coquillage", "galet"), ("ponton", "plongeoir"), ("dune", "digue"),
    ),
    "Vocabulaire du train": (
        ("locomotive", "automotrice"), ("couchette", "compartiment"), ("rail", "traverse"),
        ("ballast", "aiguillage"), ("caténaire", "pantographe"), ("dépôt", "triage"),
        ("tender", "fourgon"), ("terminus", "correspondance"),
    ),
    "Sensations et perceptions": (
        ("chaleur", "moiteur"), ("froid", "engourdissement"), ("fatigue", "courbature"),
        ("crampe", "fourmillement"), ("frisson", "sueur"), ("nausée", "hoquet"),
        ("démangeaison", "brûlure"),
    ),
    "Brawl Stars": (
        ("Bull", "Frank"), ("Rosa", "Jacky"), ("Darryl", "Ash"),
        ("Hank", "Buster"), ("Draco", "Meg"), ("Frank", "Rosa"),
        ("Bull", "Jacky"), ("Ash", "Buster"), ("Piper", "Brock"),
        ("Bea", "Nani"), ("Belle", "Mandy"), ("Angelo", "Janet"),
        ("Brock", "Bea"), ("Piper", "Belle"), ("Nani", "Angelo"),
        ("Mandy", "Janet"), ("Barley", "Dynamike"), ("Tick", "Sprout"),
        ("Grom", "Willow"), ("Juju", "Sprout"), ("Dynamike", "Grom"),
        ("Barley", "Willow"), ("Mortis", "Crow"), ("Leon", "Edgar"),
        ("Fang", "Buzz"), ("Stu", "Kenji"), ("Melodie", "Lily"),
        ("Cordelius", "Shade"), ("Crow", "Leon"), ("Edgar", "Fang"),
        ("Poco", "Byron"), ("Pam", "Gus"), ("Kit", "Berry"),
        ("Doug", "Ruffs"), ("Max", "Gale"), ("Byron", "Gus"),
        ("Poco", "Kit"), ("Gene", "Tara"), ("Sandy", "Emz"),
        ("Otis", "Charlie"), ("Lou", "Chester"), ("Colette", "Amber"),
        ("Tara", "Sandy"), ("Emz", "Otis"), ("Colt", "Rico"),
        ("Spike", "Carl"), ("Bibi", "Surge"), ("Nita", "Jessie"),
        ("Penny", "Bo"), ("Griff", "Sam"), ("Squeak", "Gray"),
        ("Chuck", "Mico"), ("Clancy", "Moe"), ("Pearl", "Lola"),
        ("Maisie", "Eve"), ("Bonnie", "Ollie"), ("8-Bit", "R-T"),
        ("Rico", "Squeak"), ("Shelly", "Nita"), ("Carl", "Surge"),
    ),
}

OPTIONAL_THEMES: tuple[str, ...] = ("Brawl Stars",)
"""Thèmes qui ne rejoignent jamais le tirage général.

Un thème optionnel est **exclusif** : soit il est éteint et ses paires
n'existent pas pour la partie, soit il est allumé et c'est le seul
dictionnaire. Le mélanger au reste n'aurait pas de sens — les indices
d'un personnage de jeu vidéo et ceux d'un légume ne se ressemblent en
rien, et la table ne saurait plus dans quel univers elle joue.
"""

WORD_PAIRS: tuple[WordPair, ...] = tuple(
    pair
    for theme, pairs in PAIRS_BY_THEME.items()
    if theme not in OPTIONAL_THEMES
    for pair in pairs
)


def theme_pairs(theme: str) -> tuple[WordPair, ...]:
    """Les paires d'un seul thème, pour jouer en mode exclusif."""
    try:
        return PAIRS_BY_THEME[theme]
    except KeyError:
        raise KeyError(f"Thème inconnu : {theme!r}") from None


def theme_of(pair_index: int) -> str:
    """Le theme auquel appartient la paire d'indice donne."""
    seen = 0
    for theme, pairs in PAIRS_BY_THEME.items():
        if theme in OPTIONAL_THEMES:
            continue  # hors du tirage général, donc hors des indices
        if pair_index < seen + len(pairs):
            return theme
        seen += len(pairs)
    raise IndexError(pair_index)


class WordGenerator:
    """Tire une des paires du dictionnaire."""

    def __init__(
        self,
        pairs: Sequence[Sequence[str]] = WORD_PAIRS,
        rng: random.Random | None = None,
    ) -> None:
        if not pairs:
            raise ValueError("Il faut au moins une paire de mots")
        invalid = [
            i for i, pair in enumerate(pairs)
            if len(pair) != 2 or pair[0] == pair[1]
        ]
        if invalid:
            raise ValueError(
                f"Ces paires n'ont pas deux mots distincts : {invalid}"
            )
        self._pairs = tuple(tuple(pair) for pair in pairs)
        self._rng = rng or random.Random()

    def pair(self) -> WordPair:
        """Une paire au hasard.

        L'ordre est tire lui aussi : sans cela, le mot de la majorite
        serait toujours le premier ecrit, et un joueur qui connait la
        liste saurait dans quel camp il est.
        """
        first, second = self._rng.choice(self._pairs)
        return (first, second) if self._rng.random() < 0.5 else (second, first)

    def pair_count(self) -> int:
        """Nombre de paires du dictionnaire."""
        return len(self._pairs)
