"""Les paires de mots du jeu.

Chaque paire est écrite à la main. C'est le remplacement d'un système
par groupes de dix où l'on tirait deux mots au hasard : sur 45
combinaisons possibles par groupe, certaines étaient bonnes et d'autres
non, sans moyen de trier. Ici, **chaque tirage est une paire validée**.

Ce qui fait une bonne paire :

1. **Même nature.** Deux fruits, deux métiers, deux instruments — pas
   « gare » et « piscine », dont les indices n'ont rien en commun.
2. **Une seule différence saillante.** « courgette » et « concombre » se
   ressemblent, mais l'un se cuit et l'autre se croque. C'est cette
   unique différence qui permet de démasquer l'Undercover.
3. **Aucun synonyme.** « développeur » et « programmeur » se décrivent
   identiquement : les civils ne peuvent structurellement pas gagner.
4. **Aucun hyperonyme.** Pas de « chaussure » face à « botte » : le
   joueur qui a le mot général ne peut rien dire qui ne s'applique pas
   aussi à l'autre.
5. **Pas de différence de taille seule.** « lac » et « étang », c'est la
   même chose en plus petit — indécidable en un indice.
6. **Que des mots connus, et un seul mot par carte.** Un joueur qui
   reçoit « caracal » ne joue pas, il se tait. Rien qui contienne un
   espace non plus, sinon l'indice unique porterait sur deux idées.
7. **Aucun duo réflexe.** « bain » et « douche » vont par deux dans la
   tête de tout le monde : celui qui tire l'un sait aussitôt ce qu'a
   l'autre camp, et l'Undercover se fond sans effort. Il faut que le mot
   reçu laisse plusieurs voisins possibles.

Les contraires tombent sous la règle 7 autant que les duos d'usage :
« généreux » appelle « avare » aussi sûrement que « bain » appelle
« douche ». Les traits de caractère sont donc croisés sans rapport entre
eux plutôt qu'opposés deux à deux.

C'est encore la règle 7 qui explique **qu'un mot serve dans plusieurs
paires**, trois au maximum. « pomme » tombe tantôt avec « poire »,
tantôt avec « coing » : le tenir ne renseigne sur rien. Un dictionnaire
où chaque mot n'aurait qu'un seul partenaire serait entièrement
prévisible dès qu'on le connaît — défaut supportable à 257 paires,
rédhibitoire à 2500.

`tools/audit_words.py` vérifie ce qui est vérifiable automatiquement :
doublons, mots trop sollicités, mots à espace, ressemblance de forme.
Il ne juge pas le sens : la ressemblance de surface sert à repérer les
paires à relire, pas à les condamner.
"""

from __future__ import annotations

import random
from typing import Sequence

WordPair = tuple[str, str]

# Les themes servent a la relecture et a l'audit ; le tirage, lui, pioche
# uniformement dans WORD_PAIRS.
PAIRS_BY_THEME: dict[str, tuple[WordPair, ...]] = {
    "Ferme": (
        ("vache", "chèvre"), ("vache", "brebis"), ("chèvre", "truie"),
        ("mouton", "cochon"), ("mouton", "veau"), ("agneau", "veau"),
        ("agneau", "chevreau"), ("taureau", "bélier"), ("taureau", "étalon"),
        ("bélier", "bouc"), ("bouc", "verrat"), ("cheval", "âne"),
        ("cheval", "mulet"), ("poney", "âne"), ("poney", "mulet"),
        ("jument", "truie"), ("poule", "pintade"), ("poule", "oie"),
        ("coq", "paon"), ("canard", "oie"), ("canard", "dinde"),
        ("dinde", "pintade"), ("poussin", "caneton"), ("lapin", "cochon"),
        ("étable", "bergerie"), ("étable", "poulailler"), ("grange", "silo"),
        ("grange", "hangar"), ("mangeoire", "abreuvoir"), ("enclos", "pâturage"),
        ("clôture", "haie"), ("foin", "paille"), ("blé", "orge"),
        ("blé", "seigle"), ("avoine", "orge"), ("maïs", "seigle"),
        ("tracteur", "moissonneuse"), ("charrue", "herse"), ("faux", "faucille"),
        ("ruche", "poulailler"), ("berger", "vacher"),
    ),
    "Animaux sauvages": (
        ("lion", "tigre"), ("lion", "guépard"), ("tigre", "panthère"),
        ("guépard", "léopard"), ("panthère", "lynx"), ("lynx", "puma"),
        ("loup", "renard"), ("loup", "chacal"), ("renard", "blaireau"),
        ("hyène", "chacal"), ("ours", "sanglier"), ("ours", "panda"),
        ("panda", "koala"), ("koala", "paresseux"), ("singe", "gorille"),
        ("gorille", "chimpanzé"), ("chimpanzé", "babouin"), ("éléphant", "rhinocéros"),
        ("rhinocéros", "hippopotame"), ("hippopotame", "buffle"), ("girafe", "zèbre"),
        ("zèbre", "antilope"), ("antilope", "gazelle"), ("gazelle", "impala"),
        ("cerf", "élan"), ("cerf", "chevreuil"), ("chevreuil", "daim"),
        ("renne", "élan"), ("bison", "buffle"), ("sanglier", "phacochère"),
        ("kangourou", "wallaby"), ("kangourou", "autruche"), ("chameau", "lama"),
        ("dromadaire", "lama"), ("écureuil", "marmotte"), ("souris", "musaraigne"),
        ("rat", "mulot"), ("hérisson", "taupe"), ("taupe", "blaireau"),
        ("castor", "loutre"), ("loutre", "phoque"), ("phoque", "morse"),
        ("morse", "otarie"), ("chauve-souris", "hibou"), ("belette", "furet"),
        ("furet", "martre"), ("raton", "opossum"), ("suricate", "marmotte"),
        ("gnou", "buffle"), ("okapi", "antilope"),
    ),
    "Oiseaux": (
        ("aigle", "faucon"), ("aigle", "vautour"), ("faucon", "épervier"),
        ("buse", "épervier"), ("vautour", "condor"), ("hibou", "chouette"),
        ("corbeau", "pie"), ("corbeau", "choucas"), ("pie", "geai"),
        ("moineau", "mésange"), ("moineau", "rouge-gorge"), ("mésange", "chardonneret"),
        ("merle", "grive"), ("merle", "étourneau"), ("rossignol", "alouette"),
        ("hirondelle", "martinet"), ("pinson", "linotte"), ("pigeon", "tourterelle"),
        ("pigeon", "mouette"), ("mouette", "goéland"), ("goéland", "cormoran"),
        ("cygne", "oie"), ("cygne", "flamant"), ("héron", "cigogne"),
        ("cigogne", "grue"), ("grue", "flamant"), ("pélican", "cormoran"),
        ("manchot", "autruche"), ("autruche", "émeu"), ("émeu", "casoar"),
        ("paon", "faisan"), ("faisan", "perdrix"), ("perdrix", "caille"),
        ("perroquet", "toucan"), ("perroquet", "ara"), ("perruche", "canari"),
        ("canari", "chardonneret"), ("colibri", "martinet"), ("pivert", "sittelle"),
        ("coucou", "grive"), ("albatros", "condor"), ("nid", "terrier"),
        ("plume", "écaille"), ("aile", "nageoire"),
    ),
    "Mer et rivière": (
        ("dauphin", "marsouin"), ("dauphin", "requin"), ("requin", "raie"),
        ("baleine", "cachalot"), ("baleine", "orque"), ("orque", "narval"),
        ("thon", "saumon"), ("thon", "maquereau"), ("saumon", "truite"),
        ("truite", "carpe"), ("carpe", "brochet"), ("brochet", "perche"),
        ("sardine", "anchois"), ("hareng", "maquereau"), ("morue", "colin"),
        ("sole", "turbot"), ("anguille", "murène"), ("murène", "congre"),
        ("poulpe", "seiche"), ("seiche", "calmar"), ("méduse", "anémone"),
        ("étoile", "oursin"), ("oursin", "anémone"), ("crabe", "homard"),
        ("homard", "langouste"), ("crevette", "écrevisse"), ("écrevisse", "langoustine"),
        ("moule", "huître"), ("huître", "coquille"), ("palourde", "coque"),
        ("bulot", "bigorneau"), ("corail", "algue"), ("algue", "plancton"),
        ("hippocampe", "poisson-clown"), ("tortue", "crocodile"), ("crocodile", "alligator"),
        ("alligator", "caïman"), ("otarie", "phoque"), ("récif", "banc"),
        ("marée", "courant"), ("vague", "houle"), ("écume", "mousse"),
    ),
    "Insectes et petites bêtes": (
        ("abeille", "guêpe"), ("abeille", "bourdon"), ("guêpe", "frelon"),
        ("papillon", "libellule"), ("papillon", "mite"), ("libellule", "éphémère"),
        ("fourmi", "termite"), ("fourmi", "cloporte"), ("termite", "cafard"),
        ("cafard", "punaise"), ("puce", "pou"), ("pou", "tique"),
        ("tique", "acarien"), ("moustique", "moucheron"), ("taon", "moustique"),
        ("criquet", "sauterelle"), ("sauterelle", "grillon"), ("grillon", "cigale"),
        ("coccinelle", "scarabée"), ("scarabée", "hanneton"), ("lucane", "hanneton"),
        ("araignée", "scorpion"), ("scorpion", "mille-pattes"), ("escargot", "limace"),
        ("limace", "ver"), ("ver", "chenille"), ("chenille", "larve"),
        ("cocon", "chrysalide"), ("toile", "nid"), ("grenouille", "crapaud"),
        ("crapaud", "salamandre"), ("salamandre", "triton"), ("lézard", "gecko"),
        ("gecko", "caméléon"), ("caméléon", "iguane"), ("serpent", "orvet"),
        ("vipère", "couleuvre"), ("cobra", "python"), ("python", "boa"),
        ("boa", "anaconda"),
    ),
    "Fruits": (
        ("pomme", "poire"), ("pomme", "coing"), ("poire", "prune"),
        ("pêche", "abricot"), ("abricot", "prune"), ("cerise", "groseille"),
        ("cerise", "prune"), ("fraise", "framboise"), ("framboise", "mûre"),
        ("mûre", "myrtille"), ("myrtille", "groseille"), ("cassis", "groseille"),
        ("raisin", "figue"), ("figue", "datte"), ("datte", "pruneau"),
        ("banane", "mangue"), ("mangue", "papaye"), ("papaye", "goyave"),
        ("ananas", "mangue"), ("orange", "mandarine"), ("mandarine", "clémentine"),
        ("citron", "pamplemousse"), ("pamplemousse", "orange"), ("kiwi", "litchi"),
        ("litchi", "grenade"), ("grenade", "kaki"), ("melon", "pastèque"),
        ("melon", "courge"), ("noix", "noisette"), ("noisette", "amande"),
        ("amande", "pistache"), ("cacahuète", "pistache"), ("olive", "câpre"),
        ("avocat", "olive"), ("noyau", "pépin"), ("peau", "écorce"),
        ("verger", "vigne"), ("panier", "cageot"),
    ),
    "Légumes": (
        ("carotte", "navet"), ("carotte", "panais"), ("navet", "radis"),
        ("radis", "betterave"), ("betterave", "céleri"), ("tomate", "poivron"),
        ("poivron", "piment"), ("piment", "paprika"), ("courgette", "concombre"),
        ("courgette", "aubergine"), ("aubergine", "poivron"), ("courge", "potiron"),
        ("oignon", "échalote"), ("échalote", "ail"), ("ail", "poireau"),
        ("poireau", "asperge"), ("asperge", "haricot"), ("salade", "épinard"),
        ("épinard", "blette"), ("blette", "chou"), ("chou", "brocoli"),
        ("brocoli", "chou-fleur"), ("artichaut", "chou-fleur"), ("endive", "fenouil"),
        ("fenouil", "céleri"), ("champignon", "truffe"), ("champignon", "cèpe"),
        ("cèpe", "girolle"), ("maïs", "quinoa"), ("riz", "semoule"),
        ("semoule", "boulgour"), ("potager", "serre"), ("récolte", "semis"),
    ),
    "Plats": (
        ("pizza", "quiche"), ("quiche", "tourte"), ("burger", "sandwich"),
        ("sandwich", "wrap"), ("wrap", "kebab"), ("hot-dog", "kebab"),
        ("sushi", "maki"), ("maki", "nem"), ("nem", "samoussa"),
        ("raviolis", "gnocchis"), ("gnocchis", "spaghettis"), ("spaghettis", "tagliatelles"),
        ("lasagnes", "cannellonis"), ("risotto", "paella"), ("paella", "couscous"),
        ("couscous", "tajine"), ("tajine", "curry"), ("curry", "chili"),
        ("ragoût", "pot-au-feu"), ("pot-au-feu", "blanquette"), ("blanquette", "bourguignon"),
        ("gratin", "clafoutis"), ("purée", "écrasé"), ("frites", "chips"),
        ("chips", "beignets"), ("beignet", "croquette"), ("croquette", "nugget"),
        ("soupe", "velouté"), ("velouté", "bouillon"), ("bouillon", "consommé"),
        ("salade", "taboulé"), ("taboulé", "coleslaw"), ("omelette", "brouillade"),
        ("crêpe", "galette"), ("galette", "gaufre"), ("raclette", "fondue"),
        ("fondue", "tartiflette"), ("choucroute", "cassoulet"), ("cassoulet", "chili"),
        ("rôti", "grillade"), ("grillade", "brochette"), ("brochette", "kebab"),
        ("steak", "escalope"), ("escalope", "côtelette"), ("saucisse", "merguez"),
        ("merguez", "chipolata"),
    ),
    "Desserts et sucreries": (
        ("gâteau", "tarte"), ("gâteau", "cake"), ("tarte", "flan"),
        ("éclair", "religieuse"), ("religieuse", "chou"), ("mille-feuille", "opéra"),
        ("macaron", "meringue"), ("meringue", "guimauve"), ("guimauve", "nougat"),
        ("nougat", "praline"), ("praline", "truffe"), ("bonbon", "sucette"),
        ("sucette", "chewing-gum"), ("caramel", "toffee"), ("chocolat", "praliné"),
        ("glace", "sorbet"), ("sorbet", "granité"), ("granité", "smoothie"),
        ("croissant", "brioche"), ("brioche", "chausson"), ("chausson", "beignet"),
        ("madeleine", "financier"), ("financier", "cannelé"), ("cookie", "biscuit"),
        ("biscuit", "sablé"), ("sablé", "spéculoos"), ("gaufre", "churro"),
        ("crumble", "cobbler"), ("compote", "confiture"), ("confiture", "gelée"),
        ("miel", "sirop"), ("sirop", "mélasse"), ("sucre", "vanille"),
        ("cupcake", "muffin"), ("donut", "beignet"), ("pâte", "glaçage"),
    ),
    "Boissons": (
        ("thé", "infusion"), ("infusion", "tisane"), ("expresso", "cappuccino"),
        ("cappuccino", "latte"), ("jus", "nectar"), ("nectar", "smoothie"),
        ("soda", "limonade"), ("limonade", "tonic"), ("cola", "tonic"),
        ("sirop", "grenadine"), ("bière", "cidre"), ("cidre", "poiré"),
        ("vin", "champagne"), ("champagne", "mousseux"), ("rosé", "sangria"),
        ("whisky", "rhum"), ("rhum", "vodka"), ("vodka", "gin"),
        ("gin", "tequila"), ("liqueur", "digestif"), ("apéritif", "digestif"),
        ("cocktail", "punch"), ("punch", "sangria"), ("milkshake", "smoothie"),
        ("chope", "gobelet"), ("carafe", "pichet"), ("bouteille", "gourde"),
        ("paille", "touillette"), ("glaçon", "rondelle"), ("bar", "terrasse"),
        ("tonneau", "fût"),
    ),
    "Épicerie": (
        ("pain", "baguette"), ("baguette", "ficelle"), ("croûte", "mie"),
        ("farine", "levure"), ("levure", "bicarbonate"), ("beurre", "margarine"),
        ("margarine", "saindoux"), ("huile", "vinaigre"), ("moutarde", "mayonnaise"),
        ("mayonnaise", "ketchup"), ("ketchup", "harissa"), ("sel", "sucre"),
        ("poivre", "muscade"), ("muscade", "cannelle"), ("cannelle", "gingembre"),
        ("gingembre", "curcuma"), ("curcuma", "safran"), ("basilic", "persil"),
        ("persil", "coriandre"), ("coriandre", "menthe"), ("thym", "romarin"),
        ("romarin", "laurier"), ("laurier", "origan"), ("camembert", "brie"),
        ("brie", "roquefort"), ("roquefort", "gorgonzola"), ("comté", "gruyère"),
        ("feta", "mozzarella"), ("mozzarella", "burrata"), ("crème", "mascarpone"),
        ("jambon", "saucisson"), ("saucisson", "chorizo"), ("chorizo", "salami"),
        ("pâté", "rillettes"), ("rillettes", "terrine"), ("bocal", "conserve"),
        ("boîte", "sachet"),
    ),
    "Vêtements": (
        ("chemise", "polo"), ("polo", "tee-shirt"), ("tee-shirt", "débardeur"),
        ("pull", "gilet"), ("pull", "sweat"), ("sweat", "hoodie"),
        ("gilet", "cardigan"), ("veste", "blazer"), ("blazer", "smoking"),
        ("manteau", "parka"), ("parka", "doudoune"), ("doudoune", "anorak"),
        ("imperméable", "ciré"), ("cape", "poncho"), ("poncho", "châle"),
        ("robe", "tunique"), ("tunique", "jupe"), ("jupe", "kilt"),
        ("pantalon", "jean"), ("jean", "chino"), ("short", "bermuda"),
        ("bermuda", "corsaire"), ("legging", "collant"), ("collant", "bas"),
        ("pyjama", "peignoir"), ("peignoir", "kimono"), ("maillot", "combinaison"),
        ("combinaison", "salopette"), ("uniforme", "livrée"), ("costume", "tailleur"),
        ("gilet", "brassière"), ("caleçon", "boxer"), ("soutien-gorge", "brassière"),
        ("chaussette", "chausson"), ("manche", "col"), ("col", "revers"),
        ("bouton", "fermeture"), ("poche", "doublure"), ("ourlet", "pli"),
        ("tissu", "cuir"), ("laine", "coton"), ("coton", "lin"),
        ("lin", "soie"), ("soie", "velours"), ("velours", "satin"),
        ("dentelle", "broderie"),
    ),
    "Chaussures et accessoires": (
        ("basket", "tennis"), ("basket", "mocassin"), ("mocassin", "derby"),
        ("escarpin", "ballerine"), ("ballerine", "mule"), ("bottine", "santiag"),
        ("sandale", "tong"), ("tong", "claquette"), ("espadrille", "sandale"),
        ("sabot", "galoche"), ("lacet", "boucle"), ("semelle", "talon"),
        ("casquette", "bonnet"), ("bonnet", "cagoule"), ("béret", "turban"),
        ("turban", "bandana"), ("chapeau", "canotier"), ("canotier", "melon"),
        ("écharpe", "foulard"), ("foulard", "châle"), ("gant", "moufle"),
        ("moufle", "mitaine"), ("ceinture", "bretelles"), ("lunettes", "masque"),
        ("masque", "visière"), ("sac", "cabas"), ("cabas", "besace"),
        ("sacoche", "pochette"), ("valise", "malle"), ("malle", "coffre"),
        ("parapluie", "ombrelle"), ("éventail", "ombrelle"), ("portefeuille", "porte-monnaie"),
        ("mouchoir", "serviette"),
    ),
    "Bijoux et parures": (
        ("bague", "chevalière"), ("bague", "alliance"), ("collier", "sautoir"),
        ("sautoir", "pendentif"), ("pendentif", "médaillon"), ("bracelet", "gourmette"),
        ("gourmette", "jonc"), ("boucle", "créole"), ("créole", "puce"),
        ("broche", "épingle"), ("épingle", "barrette"), ("diadème", "couronne"),
        ("couronne", "tiare"), ("montre", "bracelet"), ("chaîne", "cordon"),
        ("perle", "nacre"), ("diamant", "rubis"), ("rubis", "saphir"),
        ("saphir", "émeraude"), ("émeraude", "topaze"), ("améthyste", "topaze"),
        ("or", "argent"), ("argent", "bronze"), ("bronze", "cuivre"),
        ("platine", "titane"), ("écrin", "coffret"), ("maquillage", "fard"),
    ),
    "Corps humain": (
        ("bras", "jambe"), ("coude", "genou"), ("genou", "cheville"),
        ("poignet", "cheville"), ("épaule", "hanche"), ("hanche", "taille"),
        ("main", "pied"), ("doigt", "orteil"), ("pouce", "index"),
        ("ongle", "cheveu"), ("cheveu", "poil"), ("front", "menton"),
        ("menton", "joue"), ("joue", "tempe"), ("nez", "oreille"),
        ("œil", "sourcil"), ("sourcil", "cil"), ("lèvre", "paupière"),
        ("dent", "gencive"), ("langue", "palais"), ("gorge", "nuque"),
        ("nuque", "échine"), ("dos", "ventre"), ("torse", "hanche"),
        ("cœur", "poumon"), ("poumon", "foie"), ("foie", "rein"),
        ("rein", "estomac"), ("cerveau", "moelle"), ("os", "cartilage"),
        ("muscle", "tendon"), ("tendon", "ligament"), ("veine", "artère"),
        ("peau", "ongle"), ("crâne", "mâchoire"), ("côte", "vertèbre"),
        ("talon", "voûte"), ("paume", "plante"), ("barbe", "moustache"),
        ("ride", "cicatrice"),
    ),
    "Santé et soins": (
        ("rhume", "grippe"), ("grippe", "angine"), ("angine", "bronchite"),
        ("toux", "éternuement"), ("fièvre", "frisson"), ("migraine", "vertige"),
        ("nausée", "vertige"), ("bleu", "bosse"), ("bosse", "égratignure"),
        ("coupure", "brûlure"), ("brûlure", "ampoule"), ("entorse", "fracture"),
        ("fracture", "luxation"), ("piqûre", "morsure"), ("allergie", "eczéma"),
        ("eczéma", "urticaire"), ("carie", "abcès"), ("pansement", "bandage"),
        ("bandage", "attelle"), ("plâtre", "attelle"), ("béquille", "canne"),
        ("canne", "déambulateur"), ("seringue", "perfusion"), ("comprimé", "gélule"),
        ("pommade", "baume"), ("baume", "crème"), ("thermomètre", "tensiomètre"),
        ("stéthoscope", "otoscope"), ("radio", "scanner"), ("scanner", "échographie"),
        ("vaccin", "rappel"), ("ordonnance", "posologie"), ("infirmerie", "urgences"),
        ("massage", "étirement"),
    ),
    "Pièces et bâti": (
        ("salon", "véranda"), ("cave", "grenier"), ("cave", "cellier"),
        ("chambre", "bureau"), ("bureau", "atelier"), ("atelier", "garage"),
        ("balcon", "terrasse"), ("terrasse", "patio"), ("loggia", "véranda"),
        ("couloir", "palier"), ("palier", "vestibule"), ("entrée", "vestibule"),
        ("escalier", "échelle"), ("échelle", "rampe"), ("buanderie", "cellier"),
        ("dressing", "penderie"), ("mansarde", "grenier"), ("mur", "cloison"),
        ("cloison", "paroi"), ("plafond", "plancher"), ("plancher", "parquet"),
        ("parquet", "carrelage"), ("carrelage", "lino"), ("moquette", "lino"),
        ("portail", "grille"), ("fenêtre", "lucarne"), ("lucarne", "hublot"),
        ("volet", "persienne"), ("store", "rideau"), ("tuile", "ardoise"),
        ("cheminée", "poêle"), ("gouttière", "chéneau"), ("perron", "seuil"),
        ("clé", "verrou"), ("verrou", "loquet"), ("poignée", "bouton"),
        ("sonnette", "heurtoir"), ("interrupteur", "prise"), ("radiateur", "climatiseur"),
    ),
    "Meubles": (
        ("table", "comptoir"), ("table", "console"), ("bureau", "secrétaire"),
        ("chaise", "tabouret"), ("tabouret", "banc"), ("banc", "banquette"),
        ("canapé", "fauteuil"), ("fauteuil", "pouf"), ("pouf", "coussin"),
        ("lit", "hamac"), ("hamac", "matelas"), ("matelas", "sommier"),
        ("berceau", "couffin"), ("armoire", "commode"), ("commode", "buffet"),
        ("buffet", "vaisselier"), ("étagère", "bibliothèque"), ("placard", "penderie"),
        ("tiroir", "casier"), ("casier", "coffre"), ("miroir", "psyché"),
        ("paravent", "cloison"), ("porte-manteau", "patère"), ("guéridon", "console"),
        ("chevet", "commode"), ("parasol", "store"), ("tapis", "paillasson"),
        ("lampadaire", "applique"), ("applique", "suspension"), ("abat-jour", "globe"),
        ("cadre", "toile"), ("horloge", "pendule"),
    ),
    "Cuisine : ustensiles": (
        ("assiette", "bol"), ("assiette", "coupelle"), ("bol", "ramequin"),
        ("saladier", "plat"), ("plat", "terrine"), ("tasse", "mug"),
        ("mug", "bol"), ("fourchette", "pique"), ("cuillère", "louche"),
        ("louche", "écumoire"), ("couteau", "éplucheur"), ("éplucheur", "râpe"),
        ("râpe", "mandoline"), ("ciseaux", "pince"), ("pince", "spatule"),
        ("spatule", "maryse"), ("fouet", "batteur"), ("batteur", "mixeur"),
        ("mixeur", "blender"), ("casserole", "poêle"), ("poêle", "wok"),
        ("wok", "sauteuse"), ("cocotte", "marmite"), ("marmite", "faitout"),
        ("passoire", "tamis"), ("tamis", "chinois"), ("planche", "billot"),
        ("rouleau", "pilon"), ("mortier", "pilon"), ("moule", "ramequin"),
        ("plaque", "grille"), ("minuteur", "sablier"), ("torchon", "maniques"),
        ("tablier", "toque"), ("bouchon", "capsule"), ("tire-bouchon", "décapsuleur"),
        ("essoreuse", "égouttoir"), ("bocal", "boîte"), ("moulin", "salière"),
    ),
    "Salle de bain": (
        ("baignoire", "jacuzzi"), ("douche", "cabine"), ("lavabo", "vasque"),
        ("vasque", "évier"), ("robinet", "mitigeur"), ("pommeau", "flexible"),
        ("mousse", "gel"), ("peigne", "brosse"), ("sèche-cheveux", "lisseur"),
        ("lisseur", "boucleur"), ("rasoir", "tondeuse"), ("lime", "râpe"),
        ("balance", "pèse-personne"), ("déodorant", "talc"), ("parfum", "lotion"),
    ),
    "Électroménager": (
        ("four", "rôtissoire"), ("micro-ondes", "vapeur"), ("plaque", "réchaud"),
        ("hotte", "ventilateur"), ("congélateur", "glacière"), ("lave-vaisselle", "lave-linge"),
        ("sèche-linge", "étendoir"), ("aspirateur", "balai"), ("balai", "serpillière"),
        ("robot", "cireuse"), ("bouilloire", "cafetière"), ("cafetière", "percolateur"),
        ("grille-pain", "gaufrier"), ("gaufrier", "crêpière"), ("friteuse", "cuiseur"),
        ("robot", "hachoir"), ("presse-agrumes", "centrifugeuse"), ("yaourtière", "sorbetière"),
        ("chauffage", "climatiseur"), ("télévision", "vidéoprojecteur"), ("enceinte", "casque"),
        ("radio", "réveil"), ("téléphone", "tablette"), ("chargeur", "batterie"),
        ("ampoule", "néon"), ("rallonge", "multiprise"), ("pile", "accumulateur"),
    ),
    "Outils et bricolage": (
        ("marteau", "maillet"), ("maillet", "massette"), ("tournevis", "clé"),
        ("clé", "pince"), ("tenaille", "cisaille"), ("scie", "égoïne"),
        ("perceuse", "visseuse"), ("visseuse", "meuleuse"), ("ponceuse", "raboteuse"),
        ("burin", "ciseau"), ("mètre", "équerre"), ("équerre", "compas"),
        ("étau", "serre-joint"), ("établi", "tréteau"), ("échelle", "escabeau"),
        ("escabeau", "échafaudage"), ("clou", "vis"), ("vis", "boulon"),
        ("boulon", "écrou"), ("cheville", "rivet"), ("colle", "mastic"),
        ("mastic", "silicone"), ("ruban", "adhésif"), ("peinture", "vernis"),
        ("vernis", "lasure"), ("pinceau", "rouleau"), ("truelle", "spatule"),
        ("bétonnière", "brouette"), ("ciment", "plâtre"), ("plâtre", "enduit"),
        ("brique", "parpaing"), ("planche", "poutre"), ("poutre", "chevron"),
        ("clou", "agrafe"), ("casque", "gants"),
    ),
    "Jardin": (
        ("arrosoir", "seau"), ("arrosoir", "pulvérisateur"), ("râteau", "pelle"),
        ("pelle", "bêche"), ("bêche", "fourche"), ("binette", "griffe"),
        ("sécateur", "cisaille"), ("cisaille", "taille-haie"), ("tondeuse", "débroussailleuse"),
        ("brouette", "chariot"), ("hache", "serpe"), ("tronçonneuse", "hache"),
        ("gant", "genouillère"), ("pot", "jardinière"), ("jardinière", "bac"),
        ("terreau", "compost"), ("compost", "paillage"), ("engrais", "fumier"),
        ("graine", "bulbe"), ("bulbe", "bouture"), ("semis", "plant"),
        ("serre", "châssis"), ("tuteur", "treillis"), ("treillis", "pergola"),
        ("clôture", "barrière"), ("portillon", "barrière"), ("allée", "sentier"),
        ("bassin", "mare"), ("fontaine", "cascade"), ("nichoir", "mangeoire"),
        ("épouvantail", "moulinet"), ("barbecue", "plancha"), ("hamac", "balançoire"),
        ("cabane", "abri"), ("niche", "clapier"),
    ),
    "Véhicules": (
        ("voiture", "camionnette"), ("camion", "benne"), ("benne", "citerne"),
        ("bus", "autocar"), ("autocar", "navette"), ("tramway", "trolleybus"),
        ("métro", "funiculaire"), ("funiculaire", "téléphérique"), ("train", "locomotive"),
        ("wagon", "fourgon"), ("moto", "scooter"), ("vélo", "trottinette"),
        ("trottinette", "gyropode"), ("tandem", "tricycle"), ("tricycle", "draisienne"),
        ("skateboard", "roller"), ("roller", "patinette"), ("tracteur", "bulldozer"),
        ("bulldozer", "pelleteuse"), ("grue", "nacelle"), ("ambulance", "taxi"),
        ("taxi", "limousine"), ("corbillard", "fourgon"), ("caravane", "camping-car"),
        ("remorque", "attelage"), ("calèche", "diligence"), ("charrette", "carriole"),
        ("traîneau", "luge"), ("quad", "buggy"), ("volant", "guidon"),
        ("pédale", "manette"), ("frein", "embrayage"), ("moteur", "batterie"),
        ("roue", "chenille"), ("pneu", "jante"), ("phare", "clignotant"),
        ("rétroviseur", "pare-brise"), ("capot", "coffre"), ("portière", "hayon"),
        ("klaxon", "sirène"), ("essence", "gazole"), ("péage", "parking"),
        ("station", "garage"),
    ),
    "Bateaux et eau": (
        ("voilier", "goélette"), ("goélette", "caravelle"), ("yacht", "vedette"),
        ("ferry", "paquebot"), ("paquebot", "cargo"), ("cargo", "pétrolier"),
        ("péniche", "chaland"), ("chalutier", "thonier"), ("remorqueur", "brise-glace"),
        ("canoë", "kayak"), ("kayak", "pirogue"), ("pédalo", "barque"),
        ("radeau", "ponton"), ("gondole", "sampan"), ("jet-ski", "hors-bord"),
        ("sous-marin", "bathyscaphe"), ("torpille", "mine"), ("voile", "spinnaker"),
        ("mât", "bôme"), ("gouvernail", "quille"), ("ancre", "amarre"),
        ("bouée", "balise"), ("hublot", "écoutille"), ("pont", "cale"),
        ("cabine", "soute"), ("rame", "pagaie"), ("port", "quai"),
        ("quai", "jetée"), ("digue", "écluse"), ("écluse", "canal"),
        ("phare", "sémaphore"), ("marin", "capitaine"),
    ),
    "Air et espace": (
        ("avion", "jet"), ("jet", "planeur"), ("planeur", "deltaplane"),
        ("deltaplane", "parapente"), ("montgolfière", "dirigeable"), ("parachute", "aile"),
        ("drone", "satellite"), ("fusée", "navette"), ("navette", "capsule"),
        ("sonde", "rover"), ("station", "module"), ("hublot", "cockpit"),
        ("aile", "hélice"), ("hélice", "réacteur"), ("piste", "hangar"),
        ("scaphandre", "combinaison"), ("planète", "astéroïde"), ("astéroïde", "comète"),
        ("comète", "météorite"), ("étoile", "galaxie"), ("galaxie", "nébuleuse"),
        ("cratère", "canyon"), ("orbite", "trajectoire"), ("télescope", "lunette"),
        ("observatoire", "planétarium"), ("apesanteur", "gravité"),
    ),
    "Paysages": (
        ("montagne", "colline"), ("colline", "butte"), ("volcan", "geyser"),
        ("falaise", "canyon"), ("canyon", "gorge"), ("gorge", "ravin"),
        ("vallée", "plaine"), ("plaine", "plateau"), ("plage", "crique"),
        ("crique", "baie"), ("baie", "golfe"), ("cap", "presqu'île"),
        ("île", "archipel"), ("atoll", "récif"), ("oasis", "mirage"),
        ("désert", "savane"), ("savane", "steppe"), ("steppe", "toundra"),
        ("forêt", "jungle"), ("jungle", "mangrove"), ("bosquet", "clairière"),
        ("clairière", "lisière"), ("marais", "tourbière"), ("étang", "mare"),
        ("lac", "lagune"), ("rivière", "torrent"), ("torrent", "cascade"),
        ("cascade", "rapide"), ("fleuve", "estuaire"), ("delta", "estuaire"),
        ("source", "puits"), ("grotte", "gouffre"), ("gouffre", "crevasse"),
        ("glacier", "banquise"), ("banquise", "iceberg"), ("sentier", "col"),
        ("sommet", "crête"), ("éboulis", "moraine"),
    ),
    "Météo et ciel": (
        ("pluie", "bruine"), ("bruine", "crachin"), ("averse", "orage"),
        ("neige", "grésil"), ("givre", "gel"), ("verglas", "gel"),
        ("rosée", "brume"), ("brume", "brouillard"), ("nuage", "cumulus"),
        ("tonnerre", "grondement"), ("foudre", "éclair"), ("vent", "brise"),
        ("brise", "bourrasque"), ("rafale", "bourrasque"), ("tempête", "ouragan"),
        ("ouragan", "typhon"), ("tornade", "cyclone"), ("canicule", "sécheresse"),
        ("inondation", "crue"), ("avalanche", "glissement"), ("arc-en-ciel", "halo"),
        ("aurore", "crépuscule"), ("éclipse", "solstice"), ("marée", "houle"),
        ("baromètre", "girouette"), ("thermomètre", "pluviomètre"),
    ),
    "Arbres et plantes": (
        ("chêne", "hêtre"), ("hêtre", "frêne"), ("frêne", "orme"),
        ("bouleau", "tremble"), ("peuplier", "saule"), ("saule", "aulne"),
        ("sapin", "épicéa"), ("épicéa", "mélèze"), ("pin", "cèdre"),
        ("cyprès", "if"), ("platane", "marronnier"), ("marronnier", "tilleul"),
        ("érable", "charme"), ("noyer", "châtaignier"), ("olivier", "figuier"),
        ("pommier", "cerisier"), ("cerisier", "prunier"), ("palmier", "bananier"),
        ("baobab", "séquoia"), ("bambou", "roseau"), ("roseau", "jonc"),
        ("mousse", "fougère"), ("fougère", "prêle"), ("cactus", "aloès"),
        ("ronce", "buisson"), ("buisson", "haie"), ("tronc", "branche"),
        ("branche", "rameau"), ("racine", "souche"), ("écorce", "sève"),
        ("feuille", "aiguille"), ("bourgeon", "pousse"), ("gland", "faîne"),
        ("champignon", "lichen"),
    ),
    "Fleurs": (
        ("rose", "pivoine"), ("pivoine", "camélia"), ("tulipe", "jonquille"),
        ("jonquille", "narcisse"), ("narcisse", "jacinthe"), ("lys", "iris"),
        ("iris", "glaïeul"), ("marguerite", "pâquerette"), ("tournesol", "dahlia"),
        ("dahlia", "chrysanthème"), ("œillet", "gerbera"), ("orchidée", "anthurium"),
        ("violette", "pensée"), ("pensée", "primevère"), ("coquelicot", "bleuet"),
        ("bleuet", "myosotis"), ("lavande", "bruyère"), ("muguet", "clochette"),
        ("hortensia", "lilas"), ("lilas", "glycine"), ("mimosa", "genêt"),
        ("géranium", "bégonia"), ("nénuphar", "lotus"), ("tige", "pétale"),
        ("pétale", "corolle"), ("pollen", "nectar"), ("bouquet", "couronne"),
        ("gerbe", "guirlande"),
    ),
    "Sports": (
        ("football", "rugby"), ("basketball", "handball"), ("handball", "waterpolo"),
        ("volley", "badminton"), ("badminton", "squash"), ("tennis", "padel"),
        ("padel", "squash"), ("ping-pong", "badminton"), ("hockey", "crosse"),
        ("golf", "croquet"), ("pétanque", "bowling"), ("bowling", "curling"),
        ("baseball", "cricket"), ("natation", "plongeon"), ("aviron", "canoë"),
        ("surf", "bodyboard"), ("kitesurf", "wakeboard"), ("course", "marche"),
        ("sprint", "marathon"), ("haies", "steeple"), ("perche", "hauteur"),
        ("javelot", "disque"), ("disque", "marteau"), ("poids", "javelot"),
        ("escalade", "randonnée"), ("randonnée", "trekking"), ("alpinisme", "spéléologie"),
        ("ski", "snowboard"), ("patinage", "luge"), ("bobsleigh", "skeleton"),
        ("boxe", "judo"), ("judo", "karaté"), ("karaté", "taekwondo"),
        ("lutte", "sumo"), ("équitation", "polo"), ("cyclisme", "BMX"),
        ("danse", "gymnastique"), ("gymnastique", "trampoline"), ("yoga", "pilates"),
        ("musculation", "crossfit"), ("aérobic", "zumba"), ("parkour", "acrobatie"),
        ("échauffement", "étirement"),
    ),
    "Équipement sportif": (
        ("raquette", "batte"), ("batte", "crosse"), ("filet", "but"),
        ("but", "panier"), ("panier", "poteau"), ("casque", "genouillère"),
        ("coudière", "genouillère"), ("maillot", "dossard"), ("short", "cuissard"),
        ("crampon", "pointe"), ("chronomètre", "sifflet"), ("sifflet", "drapeau"),
        ("médaille", "trophée"), ("coupe", "ceinture"), ("podium", "tribune"),
        ("vestiaire", "gradin"), ("terrain", "piste"), ("piste", "couloir"),
        ("tapis", "ring"), ("ring", "tatami"), ("agrès", "barre"),
        ("haltère", "kettlebell"), ("corde", "élastique"), ("tremplin", "plongeoir"),
        ("palme", "tuba"), ("mousqueton", "baudrier"), ("bâton", "fixation"),
        ("arc", "arbalète"), ("cible", "carton"), ("selle", "étrier"),
    ),
    "Jeux": (
        ("échecs", "shogi"), ("dames", "othello"), ("go", "backgammon"),
        ("cartes", "tarot"), ("tarot", "belote"), ("poker", "rami"),
        ("dominos", "mahjong"), ("dés", "yams"), ("toupie", "yoyo"),
        ("bille", "osselet"), ("scrabble", "boggle"), ("monopoly", "cluedo"),
        ("cluedo", "risk"), ("puzzle", "labyrinthe"), ("charade", "devinette"),
        ("énigme", "rébus"), ("loto", "tombola"), ("bingo", "loterie"),
        ("billard", "fléchettes"), ("baby-foot", "flipper"), ("console", "manette"),
        ("borne", "simulateur"), ("cerf-volant", "boomerang"), ("frisbee", "boomerang"),
        ("marelle", "élastique"), ("balançoire", "toboggan"), ("bascule", "manège"),
        ("poupée", "peluche"), ("peluche", "marionnette"), ("robot", "figurine"),
        ("cube", "brique"), ("ballon", "cerceau"), ("corde", "diabolo"),
        ("kaléidoscope", "toupie"), ("pion", "jeton"), ("plateau", "damier"),
        ("règle", "consigne"),
    ),
    "Métiers": (
        ("médecin", "infirmier"), ("infirmier", "aide-soignant"), ("chirurgien", "anesthésiste"),
        ("pharmacien", "biologiste"), ("vétérinaire", "zoologiste"), ("opticien", "audioprothésiste"),
        ("kinésithérapeute", "ostéopathe"), ("psychologue", "psychiatre"), ("sage-femme", "pédiatre"),
        ("boulanger", "pâtissier"), ("pâtissier", "chocolatier"), ("boucher", "charcutier"),
        ("charcutier", "traiteur"), ("poissonnier", "écailler"), ("fromager", "crémier"),
        ("cuisinier", "commis"), ("serveur", "barman"), ("barman", "sommelier"),
        ("primeur", "épicier"), ("berger", "agriculteur"), ("agriculteur", "maraîcher"),
        ("viticulteur", "brasseur"), ("apiculteur", "pisciculteur"), ("bûcheron", "forestier"),
        ("mineur", "carrier"), ("pêcheur", "marin"), ("pompier", "secouriste"),
        ("policier", "gendarme"), ("militaire", "légionnaire"), ("douanier", "vigile"),
        ("garde", "sentinelle"), ("juge", "avocat"), ("notaire", "huissier"),
        ("greffier", "procureur"), ("facteur", "livreur"), ("chauffeur", "coursier"),
        ("éboueur", "cantonnier"), ("jardinier", "paysagiste"), ("pilote", "steward"),
        ("aiguilleur", "contrôleur"), ("architecte", "ingénieur"), ("plombier", "électricien"),
        ("électricien", "chauffagiste"), ("maçon", "charpentier"), ("charpentier", "menuisier"),
        ("menuisier", "ébéniste"), ("couvreur", "carreleur"), ("peintre", "plâtrier"),
        ("serrurier", "vitrier"), ("mécanicien", "carrossier"), ("soudeur", "chaudronnier"),
        ("horloger", "bijoutier"), ("cordonnier", "maroquinier"), ("tailleur", "couturier"),
        ("coiffeur", "barbier"), ("esthéticienne", "manucure"), ("photographe", "cameraman"),
        ("journaliste", "reporter"), ("écrivain", "traducteur"), ("libraire", "bibliothécaire"),
        ("professeur", "instituteur"), ("éducateur", "animateur"), ("comptable", "banquier"),
        ("caissier", "vendeur"), ("secrétaire", "assistant"), ("acteur", "figurant"),
        ("chanteur", "musicien"), ("danseur", "chorégraphe"), ("clown", "acrobate"),
        ("arbitre", "entraîneur"), ("guide", "réceptionniste"), ("archéologue", "géologue"),
        ("astronome", "météorologue"),
    ),
    "Instruments": (
        ("piano", "clavecin"), ("clavecin", "orgue"), ("orgue", "harmonium"),
        ("guitare", "banjo"), ("banjo", "mandoline"), ("ukulélé", "mandoline"),
        ("violon", "alto"), ("alto", "violoncelle"), ("violoncelle", "contrebasse"),
        ("harpe", "cithare"), ("batterie", "percussion"), ("tambour", "timbale"),
        ("cymbale", "gong"), ("triangle", "maracas"), ("xylophone", "marimba"),
        ("marimba", "vibraphone"), ("saxophone", "clarinette"), ("clarinette", "hautbois"),
        ("hautbois", "basson"), ("flûte", "piccolo"), ("trompette", "cornet"),
        ("cornet", "bugle"), ("trombone", "tuba"), ("cor", "tuba"),
        ("accordéon", "bandonéon"), ("harmonica", "mélodica"), ("synthétiseur", "sampler"),
        ("archet", "médiator"), ("corde", "anche"), ("touche", "pédale"),
        ("partition", "tablature"), ("métronome", "diapason"), ("pupitre", "étui"),
    ),
    "Musique et spectacle": (
        ("rock", "punk"), ("punk", "metal"), ("metal", "grunge"),
        ("jazz", "blues"), ("blues", "soul"), ("soul", "funk"),
        ("rap", "slam"), ("pop", "disco"), ("disco", "house"),
        ("techno", "trance"), ("reggae", "ska"), ("folk", "country"),
        ("country", "bluegrass"), ("classique", "baroque"), ("opéra", "opérette"),
        ("symphonie", "concerto"), ("concerto", "sonate"), ("chorale", "orchestre"),
        ("orchestre", "fanfare"), ("fanfare", "harmonie"), ("refrain", "couplet"),
        ("mélodie", "harmonie"), ("rythme", "tempo"), ("concert", "festival"),
        ("festival", "tournée"), ("scène", "coulisses"), ("cirque", "cabaret"),
        ("cabaret", "revue"), ("théâtre", "opéra"), ("mime", "marionnette"),
        ("magie", "hypnose"), ("jonglage", "équilibrisme"), ("chapiteau", "estrade"),
        ("projecteur", "micro"), ("micro", "haut-parleur"), ("rideau", "décor"),
        ("costume", "maquillage"), ("répétition", "générale"), ("applaudissement", "rappel"),
        ("billet", "programme"),
    ),
    "Arts et loisirs créatifs": (
        ("dessin", "croquis"), ("croquis", "esquisse"), ("peinture", "aquarelle"),
        ("aquarelle", "gouache"), ("gouache", "acrylique"), ("huile", "pastel"),
        ("fusain", "sanguine"), ("encre", "lavis"), ("sculpture", "modelage"),
        ("poterie", "céramique"), ("céramique", "faïence"), ("porcelaine", "grès"),
        ("gravure", "sérigraphie"), ("mosaïque", "vitrail"), ("fresque", "graffiti"),
        ("collage", "origami"), ("origami", "pliage"), ("tricot", "crochet"),
        ("crochet", "macramé"), ("couture", "broderie"), ("broderie", "patchwork"),
        ("tissage", "tapisserie"), ("photo", "vidéo"), ("montage", "retouche"),
        ("caricature", "portrait"), ("toile", "chevalet"), ("palette", "godet"),
        ("pinceau", "brosse"), ("crayon", "feutre"), ("feutre", "marqueur"),
        ("moule", "empreinte"), ("galerie", "atelier"), ("vernissage", "exposition"),
    ),
    "École": (
        ("stylo", "plume"), ("crayon", "portemine"), ("gomme", "correcteur"),
        ("règle", "équerre"), ("compas", "rapporteur"), ("cahier", "classeur"),
        ("classeur", "chemise"), ("agenda", "carnet"), ("colle", "scotch"),
        ("agrafeuse", "perforatrice"), ("ciseaux", "cutter"), ("cartable", "trousse"),
        ("calculatrice", "abaque"), ("tableau", "ardoise"), ("craie", "marqueur"),
        ("pupitre", "estrade"), ("récréation", "interclasse"), ("cantine", "internat"),
        ("maths", "physique"), ("chimie", "biologie"), ("géologie", "astronomie"),
        ("histoire", "philosophie"), ("géographie", "économie"), ("anglais", "espagnol"),
        ("allemand", "italien"), ("latin", "grec"), ("grammaire", "orthographe"),
        ("conjugaison", "vocabulaire"), ("rédaction", "dictée"), ("exposé", "mémoire"),
        ("contrôle", "examen"), ("examen", "concours"), ("note", "moyenne"),
        ("bulletin", "carnet"), ("devoir", "exercice"), ("leçon", "chapitre"),
        ("manuel", "dictionnaire"), ("dictionnaire", "encyclopédie"), ("bibliothèque", "médiathèque"),
        ("diplôme", "certificat"), ("rentrée", "vacances"),
    ),
    "Bureau et informatique": (
        ("ordinateur", "tablette"), ("portable", "fixe"), ("clavier", "souris"),
        ("écran", "moniteur"), ("imprimante", "scanner"), ("photocopieuse", "fax"),
        ("serveur", "routeur"), ("routeur", "modem"), ("câble", "adaptateur"),
        ("logiciel", "application"), ("fichier", "dossier"), ("document", "tableur"),
        ("diaporama", "affiche"), ("courriel", "message"), ("site", "blog"),
        ("virus", "pare-feu"), ("corbeille", "archive"), ("raccourci", "menu"),
        ("curseur", "pointeur"), ("onglet", "fenêtre"), ("classeur", "parapheur"),
        ("tampon", "signature"), ("facture", "devis"), ("contrat", "avenant"),
        ("réunion", "entretien"), ("planning", "échéance"), ("badge", "pointeuse"),
    ),
    "Ville et commerces": (
        ("boulangerie", "pâtisserie"), ("épicerie", "supérette"), ("librairie", "papeterie"),
        ("kiosque", "tabac"), ("institut", "spa"), ("banque", "assurance"),
        ("poste", "pressing"), ("marché", "brocante"), ("brocante", "vide-grenier"),
        ("fleuriste", "jardinerie"), ("restaurant", "brasserie"), ("brasserie", "bistrot"),
        ("cantine", "self"), ("bijouterie", "parfumerie"), ("quincaillerie", "droguerie"),
        ("garage", "concession"), ("station-service", "lavage"), ("mairie", "préfecture"),
        ("commissariat", "caserne"), ("tribunal", "prison"), ("hôpital", "clinique"),
        ("collège", "lycée"), ("université", "faculté"), ("crèche", "garderie"),
        ("théâtre", "cinéma"), ("musée", "galerie"), ("stade", "gymnase"),
        ("piscine", "patinoire"), ("parc", "square"), ("place", "esplanade"),
        ("avenue", "boulevard"), ("boulevard", "ruelle"), ("impasse", "ruelle"),
        ("trottoir", "chaussée"), ("rond-point", "carrefour"), ("feu", "panneau"),
        ("lampadaire", "borne"), ("parking", "aire"),
    ),
    "Bâtiments et monuments": (
        ("château", "palais"), ("palais", "manoir"), ("manoir", "villa"),
        ("chaumière", "cabane"), ("chalet", "bungalow"), ("immeuble", "gratte-ciel"),
        ("tour", "beffroi"), ("beffroi", "clocher"), ("cathédrale", "basilique"),
        ("basilique", "abbaye"), ("chapelle", "oratoire"), ("mosquée", "synagogue"),
        ("temple", "pagode"), ("monastère", "couvent"), ("donjon", "rempart"),
        ("rempart", "muraille"), ("douve", "pont-levis"), ("forteresse", "citadelle"),
        ("moulin", "silo"), ("aqueduc", "viaduc"), ("viaduc", "pont"),
        ("barrage", "digue"), ("tunnel", "souterrain"), ("arène", "amphithéâtre"),
        ("colonne", "obélisque"), ("obélisque", "stèle"), ("statue", "buste"),
        ("pyramide", "mausolée"), ("mausolée", "tombeau"), ("ruine", "vestige"),
        ("fresque", "bas-relief"), ("dôme", "coupole"), ("voûte", "arcade"),
        ("fondation", "charpente"),
    ),
    "Voyage": (
        ("bagage", "colis"), ("passeport", "visa"), ("billet", "réservation"),
        ("hôtel", "auberge"), ("auberge", "gîte"), ("camping", "bivouac"),
        ("tente", "caravane"), ("croisière", "circuit"), ("excursion", "escapade"),
        ("séjour", "escale"), ("guichet", "comptoir"), ("douane", "contrôle"),
        ("carte", "boussole"), ("boussole", "GPS"), ("itinéraire", "détour"),
        ("étape", "halte"), ("auberge", "relais"), ("guide", "brochure"),
        ("devise", "change"), ("pourboire", "taxe"), ("hébergement", "pension"),
        ("chambre", "dortoir"), ("réception", "conciergerie"), ("plage", "station"),
        ("randonnée", "balade"), ("gourde", "thermos"), ("lampe", "frontale"),
        ("duvet", "matelas"), ("réchaud", "popote"),
    ),
    "Fêtes et célébrations": (
        ("anniversaire", "fête"), ("mariage", "fiançailles"), ("baptême", "communion"),
        ("noces", "banquet"), ("banquet", "buffet"), ("réception", "cocktail"),
        ("bal", "soirée"), ("carnaval", "défilé"), ("défilé", "parade"),
        ("procession", "cortège"), ("guirlande", "banderole"), ("confetti", "serpentin"),
        ("ballon", "lampion"), ("bougie", "cierge"), ("cadeau", "présent"),
        ("emballage", "ruban"), ("carte", "invitation"), ("discours", "toast"),
        ("costume", "déguisement"), ("masque", "perruque"), ("sapin", "crèche"),
        ("cloche", "trompette"), ("vœux", "résolution"), ("kermesse", "foire"),
        ("manège", "stand"), ("tirage", "récompense"),
    ),
    "Temps et calendrier": (
        ("seconde", "minute"), ("heure", "journée"), ("matin", "après-midi"),
        ("midi", "goûter"), ("soirée", "veillée"), ("semaine", "quinzaine"),
        ("mois", "trimestre"), ("saison", "semestre"), ("année", "décennie"),
        ("décennie", "siècle"), ("siècle", "millénaire"), ("printemps", "automne"),
        ("été", "hiver"), ("veille", "surlendemain"), ("époque", "ère"),
        ("horloge", "cadran"), ("montre", "chronomètre"), ("calendrier", "almanach"),
        ("agenda", "planning"), ("date", "échéance"), ("délai", "attente"),
        ("retard", "avance"), ("pause", "interruption"), ("durée", "intervalle"),
    ),
    "Émotions": (
        ("espoir", "confiance"), ("fierté", "vanité"), ("tendresse", "affection"),
        ("amour", "passion"), ("amitié", "complicité"), ("tristesse", "mélancolie"),
        ("larme", "sanglot"), ("deuil", "regret"), ("colère", "irritation"),
        ("jalousie", "envie"), ("rancune", "amertume"), ("peur", "crainte"),
        ("timidité", "gêne"), ("surprise", "étonnement"), ("courage", "audace"),
    ),
    "Communication": (
        ("lettre", "carte"), ("colis", "recommandé"), ("timbre", "cachet"),
        ("enveloppe", "étiquette"), ("appel", "message"), ("sonnerie", "vibreur"),
        ("affiche", "panneau"), ("publicité", "réclame"), ("journal", "magazine"),
        ("magazine", "revue"), ("article", "chronique"), ("titre", "légende"),
        ("interview", "reportage"), ("émission", "podcast"), ("bulletin", "communiqué"),
        ("secret", "confidence"), ("promesse", "serment"), ("question", "requête"),
        ("réponse", "réplique"), ("discours", "allocution"), ("débat", "discussion"),
        ("dispute", "querelle"), ("reproche", "critique"), ("insulte", "moquerie"),
        ("blague", "anecdote"), ("signature", "paraphe"), ("code", "signal"),
        ("geste", "mimique"),
    ),
    "Contenants": (
        ("caisse", "cageot"), ("corbeille", "hotte"), ("bocal", "pot"),
        ("flacon", "fiole"), ("fiole", "ampoule"), ("bouteille", "carafe"),
        ("bidon", "jerrican"), ("seau", "bassine"), ("bassine", "cuvette"),
        ("baquet", "tonneau"), ("tonneau", "barrique"), ("cuve", "citerne"),
        ("étui", "housse"), ("housse", "fourreau"), ("enveloppe", "pochette"),
        ("tube", "cartouche"), ("bombe", "vaporisateur"), ("cornet", "gobelet"),
        ("plateau", "corbeille"), ("filet", "sacoche"), ("valise", "cantine"),
        ("urne", "tirelire"), ("coffre-fort", "casier"),
    ),
    "Matières": (
        ("chêne", "contreplaqué"), ("pierre", "marbre"), ("marbre", "granit"),
        ("granit", "ardoise"), ("sable", "gravier"), ("gravier", "galet"),
        ("argile", "terre"), ("brique", "torchis"), ("verre", "cristal"),
        ("cristal", "quartz"), ("acier", "fer"), ("fer", "fonte"),
        ("aluminium", "zinc"), ("cuivre", "laiton"), ("plomb", "étain"),
        ("plastique", "résine"), ("caoutchouc", "latex"), ("papier", "carton"),
        ("carton", "parchemin"), ("tissu", "feutre"), ("cuir", "daim"),
        ("fourrure", "peau"), ("laine", "cachemire"), ("nylon", "polyester"),
        ("liège", "paille"), ("cire", "résine"), ("charbon", "tourbe"),
        ("pétrole", "goudron"), ("cendre", "poussière"), ("glace", "givre"),
    ),
    "Formes et couleurs": (
        ("rouge", "bordeaux"), ("bordeaux", "grenat"), ("rose", "fuchsia"),
        ("orange", "corail"), ("jaune", "moutarde"), ("moutarde", "ocre"),
        ("vert", "olive"), ("turquoise", "cyan"), ("bleu", "indigo"),
        ("indigo", "marine"), ("violet", "mauve"), ("mauve", "lilas"),
        ("marron", "beige"), ("beige", "taupe"), ("gris", "argenté"),
        ("blanc", "ivoire"), ("ivoire", "crème"), ("noir", "anthracite"),
        ("doré", "cuivré"), ("carré", "losange"), ("losange", "trapèze"),
        ("cercle", "ovale"), ("sphère", "cylindre"), ("cylindre", "cône"),
        ("cube", "prisme"), ("courbe", "arc"), ("ligne", "trait"),
        ("point", "virgule"), ("rayure", "carreau"), ("pois", "damier"),
        ("motif", "arabesque"),
    ),
    "Argent et commerce": (
        ("pièce", "billet"), ("euro", "dollar"), ("caisse", "tirelire"),
        ("tarif", "barème"), ("solde", "promotion"), ("facture", "ticket"),
        ("reçu", "quittance"), ("achat", "commande"), ("vente", "enchère"),
        ("enchère", "adjudication"), ("troc", "échange"), ("emprunt", "crédit"),
        ("dette", "arriéré"), ("épargne", "placement"), ("intérêt", "dividende"),
        ("salaire", "prime"), ("prime", "pourboire"), ("budget", "dépense"),
        ("fortune", "héritage"), ("guichet", "distributeur"), ("stock", "inventaire"),
        ("étal", "vitrine"), ("rayon", "linéaire"), ("livraison", "expédition"),
    ),
    "Récits et imaginaire": (
        ("conte", "fable"), ("fable", "légende"), ("légende", "mythe"),
        ("roman", "nouvelle"), ("nouvelle", "récit"), ("poème", "chanson"),
        ("épopée", "saga"), ("intrigue", "péripétie"), ("héros", "aventurier"),
        ("chevalier", "écuyer"), ("roi", "empereur"), ("reine", "impératrice"),
        ("prince", "duc"), ("duc", "comte"), ("seigneur", "vassal"),
        ("sorcière", "fée"), ("fée", "nymphe"), ("lutin", "gnome"),
        ("gnome", "nain"), ("elfe", "farfadet"), ("géant", "ogre"),
        ("ogre", "troll"), ("dragon", "hydre"), ("licorne", "pégase"),
        ("griffon", "sphinx"), ("sirène", "naïade"), ("vampire", "loup-garou"),
        ("zombie", "momie"), ("monstre", "chimère"), ("pirate", "corsaire"),
        ("détective", "espion"), ("bouffon", "ménestrel"), ("oracle", "devin"),
        ("baguette", "grimoire"), ("trésor", "butin"), ("malédiction", "sortilège"),
        ("quête", "épreuve"), ("prophétie", "présage"),
    ),
    "Objets du quotidien": (
        ("porte-clés", "breloque"), ("briquet", "allumette"), ("bougie", "lanterne"),
        ("aiguille", "épingle"), ("fil", "ficelle"), ("trombone", "agrafe"),
        ("punaise", "aimant"), ("crochet", "clou"), ("chiffon", "lingette"),
        ("balai", "plumeau"), ("poubelle", "bac"), ("éponge", "brosse"),
        ("gant", "tablier"), ("nappe", "set"), ("thermos", "glacière"),
        ("réveil", "minuteur"), ("télécommande", "manette"), ("cintre", "portant"),
        ("fer", "planche"), ("miroir", "loupe"), ("loupe", "jumelles"),
        ("carnet", "bloc-notes"), ("marque-page", "signet"),
    ),
    "Sons et bruits": (
        ("grincement", "craquement"), ("tintement", "carillon"), ("sonnerie", "alarme"),
        ("sifflement", "bourdonnement"), ("ronflement", "râle"), ("gargouillis", "clapotis"),
        ("fracas", "détonation"), ("aboiement", "hurlement"), ("miaulement", "ronronnement"),
        ("hennissement", "braiment"), ("meuglement", "bêlement"), ("gazouillis", "pépiement"),
        ("croassement", "caquètement"), ("sifflet", "cor"), ("battement", "pulsation"),
        ("chuchotement", "soupir"), ("applaudissement", "huée"), ("mélodie", "berceuse"),
        ("hymne", "marche"),
    ),
    "Sensations": (
        ("douceur", "rugosité"), ("piquant", "brûlant"), ("démangeaison", "picotement"),
        ("engourdissement", "crampe"), ("sucré", "mielleux"), ("salé", "iodé"),
        ("éclat", "reflet"),
    ),
    "Mouvements": (
        ("marche", "flânerie"), ("course", "sprint"), ("saut", "bond"),
        ("bond", "cabriole"), ("chute", "glissade"), ("roulade", "culbute"),
        ("nage", "plongeon"), ("danse", "valse"), ("valse", "tango"),
        ("pirouette", "entrechat"), ("balancement", "oscillation"), ("secousse", "vibration"),
        ("poussée", "traction"), ("virage", "demi-tour"), ("élan", "impulsion"),
        ("détour", "raccourci"), ("va-et-vient", "aller-retour"), ("galop", "trot"),
        ("pas", "enjambée"),
    ),
    "Armes et défense": (
        ("épée", "sabre"), ("sabre", "rapière"), ("rapière", "fleuret"),
        ("dague", "poignard"), ("poignard", "stylet"), ("hache", "hallebarde"),
        ("lance", "pique"), ("massue", "gourdin"), ("fléau", "masse"),
        ("flèche", "carreau"), ("fronde", "lance-pierre"), ("catapulte", "baliste"),
        ("bélier", "trébuchet"), ("gantelet", "brassard"), ("cuirasse", "plastron"),
        ("fourreau", "carquois"), ("canon", "mortier"), ("mousquet", "arquebuse"),
        ("pistolet", "revolver"), ("fusil", "carabine"), ("grenade", "obus"),
        ("mine", "piège"), ("rempart", "meurtrière"), ("tranchée", "abri"),
    ),
    "Histoire et société": (
        ("royaume", "empire"), ("empire", "république"), ("tribu", "clan"),
        ("village", "hameau"), ("cité", "métropole"), ("colonie", "comptoir"),
        ("traité", "alliance"), ("bataille", "escarmouche"), ("siège", "assaut"),
        ("trêve", "armistice"), ("noble", "bourgeois"), ("paysan", "serf"),
        ("artisan", "marchand"), ("guilde", "corporation"), ("marché", "foire"),
        ("caravane", "convoi"), ("expédition", "conquête"), ("découverte", "exploration"),
        ("vestige", "fouille"), ("manuscrit", "parchemin"), ("sceau", "blason"),
        ("blason", "emblème"), ("couronnement", "sacre"), ("trône", "sceptre"),
        ("loi", "décret"), ("décret", "édit"), ("tribunal", "assemblée"),
        ("vote", "scrutin"), ("citoyen", "sujet"), ("frontière", "province"),
    ),
    "Enfance": (
        ("berceau", "landau"), ("landau", "poussette"), ("biberon", "tétine"),
        ("bavoir", "body"), ("couche", "lange"), ("hochet", "mobile"),
        ("doudou", "peluche"), ("parc", "trotteur"), ("comptine", "berceuse"),
        ("toboggan", "tourniquet"), ("cerceau", "quilles"), ("craie", "gommette"),
        ("déguisement", "grimage"), ("goûter", "compote"), ("nounou", "puéricultrice"),
        ("cour", "préau"), ("récré", "sieste"),
    ),
    "Nettoyage et entretien": (
        ("serpillière", "lavette"), ("seau", "chariot"), ("aspirateur", "souffleur"),
        ("chiffon", "microfibre"), ("savon", "détergent"), ("lessive", "assouplissant"),
        ("cire", "encaustique"), ("essuie-tout", "papier"), ("repassage", "pliage"),
        ("tache", "auréole"), ("moisissure", "calcaire"), ("désodorisant", "encens"),
        ("compost", "recyclage"), ("conteneur", "benne"),
    ),
    "Traits de caractère": (
        ("bavard", "gourmand"), ("timide", "distrait"), ("généreux", "drôle"),
        ("avare", "râleur"), ("courageux", "patient"), ("peureux", "coquet"),
        ("paresseux", "naïf"), ("travailleur", "discret"), ("menteur", "moqueur"),
        ("honnête", "économe"), ("gentil", "ordonné"), ("sévère", "ponctuel"),
        ("curieux", "maladroit"), ("habile", "solitaire"), ("têtu", "rêveur"),
        ("modeste", "sociable"), ("nerveux", "dépensier"), ("prudent", "brouillon"),
        ("audacieux", "bienveillant"), ("méfiant", "bruyant"), ("orgueilleux", "frileux"),
        ("indulgent", "impulsif"), ("posé", "négligé"), ("attentif", "conciliant"),
    ),
    "Cinéma et télévision": (
        ("film", "série"), ("épisode", "saison"), ("bande-annonce", "générique"),
        ("scénario", "storyboard"), ("réalisateur", "producteur"), ("caméra", "perche"),
        ("figurant", "cascadeur"), ("doublure", "cascadeur"), ("comédie", "thriller"),
        ("thriller", "polar"), ("western", "péplum"), ("horreur", "fantastique"),
        ("documentaire", "reportage"), ("animation", "marionnette"), ("court-métrage", "clip"),
        ("plan", "séquence"), ("montage", "mixage"), ("sous-titre", "doublage"),
        ("affiche", "jaquette"), ("salle", "écran"), ("séance", "avant-première"),
        ("critique", "palmarès"), ("prix", "nomination"), ("acteur", "réalisateur"),
        ("costumier", "maquilleur"), ("décor", "accessoire"), ("perruque", "prothèse"),
    ),
    "Livres et écriture": (
        ("roman", "essai"), ("biographie", "mémoires"), ("recueil", "anthologie"),
        ("chapitre", "paragraphe"), ("sommaire", "index"), ("couverture", "jaquette"),
        ("reliure", "brochure"), ("page", "feuillet"), ("marge", "interligne"),
        ("caractère", "police"), ("virgule", "tiret"), ("parenthèse", "guillemet"),
        ("accent", "cédille"), ("rime", "vers"), ("strophe", "refrain"),
        ("métaphore", "comparaison"), ("narrateur", "personnage"), ("brouillon", "manuscrit"),
        ("éditeur", "imprimeur"), ("tirage", "édition"), ("étagère", "rayon"),
        ("emprunt", "prêt"), ("signet", "onglet"), ("plume", "encrier"),
        ("papyrus", "tablette"),
    ),
    "Croyances et rites": (
        ("prière", "chant"), ("messe", "office"), ("sermon", "prêche"),
        ("pèlerinage", "procession"), ("jeûne", "abstinence"), ("offrande", "sacrifice"),
        ("autel", "reliquaire"), ("icône", "statuette"), ("encens", "myrrhe"),
        ("chapelet", "amulette"), ("talisman", "amulette"), ("prophète", "apôtre"),
        ("moine", "ermite"), ("prêtre", "rabbin"), ("imam", "pasteur"),
        ("nonne", "novice"), ("croyant", "pèlerin"), ("miracle", "révélation"),
        ("rite", "coutume"), ("superstition", "présage"), ("horoscope", "tarot"),
        ("boule", "pendule"),
    ),
    "Camping et plein air": (
        ("tente", "tipi"), ("sardine", "piquet"), ("duvet", "couverture"),
        ("réchaud", "brasero"), ("gamelle", "assiette"), ("couteau", "multitool"),
        ("boussole", "altimètre"), ("gourde", "filtre"), ("lampe", "bougie"),
        ("trousse", "attelle"), ("feu", "braise"), ("fumée", "étincelle"),
        ("sac", "bâche"), ("moustiquaire", "répulsif"), ("jumelles", "longue-vue"),
        ("nœud", "boucle"), ("sentier", "balise"), ("refuge", "bivouac"),
    ),
    "Pêche et chasse": (
        ("canne", "moulinet"), ("hameçon", "leurre"), ("appât", "amorce"),
        ("flotteur", "plomb"), ("épuisette", "nasse"), ("harpon", "foène"),
        ("cuissarde", "waders"), ("truite", "gardon"), ("gardon", "goujon"),
        ("silure", "sandre"), ("étang", "réservoir"), ("berge", "ponton"),
        ("affût", "battue"), ("meute", "chien"), ("cor", "trompe"),
        ("gibecière", "carnier"), ("cartouche", "douille"), ("piège", "collet"),
        ("perdreau", "bécasse"), ("lièvre", "lapin"), ("chevreuil", "marcassin"),
        ("permis", "quota"), ("saison", "ouverture"),
    ),
    "Coiffure et beauté": (
        ("mèche", "frange"), ("chignon", "tresse"), ("tresse", "natte"),
        ("queue", "couette"), ("raie", "épi"), ("teinture", "mèches"),
        ("balayage", "coloration"), ("permanente", "lissage"), ("ciseaux", "rasoir"),
        ("tondeuse", "sabot"), ("cape", "serviette"), ("bac", "fauteuil"),
        ("blush", "highlighter"), ("crayon", "khôl"), ("pinceau", "éponge"),
        ("manucure", "pédicure"), ("lime", "polissoir"), ("épilation", "rasage"),
    ),
    "Justice et administration": (
        ("plainte", "recours"), ("procès", "audience"), ("verdict", "sentence"),
        ("peine", "sanction"), ("preuve", "témoignage"), ("témoin", "juré"),
        ("accusé", "prévenu"), ("plaidoirie", "réquisitoire"), ("appel", "cassation"),
        ("dossier", "pièce"), ("acte", "titre"), ("attestation", "justificatif"),
        ("formulaire", "questionnaire"), ("timbre", "vignette"), ("registre", "cadastre"),
        ("permis", "licence"), ("licence", "agrément"), ("mandat", "procuration"),
        ("caution", "garantie"), ("bail", "location"), ("expulsion", "saisie"),
        ("prison", "détention"), ("cellule", "parloir"), ("gardien", "surveillant"),
    ),
    "Cuisine du monde": (
        ("tapas", "mezzé"), ("antipasti", "tapas"), ("ramen", "pho"),
        ("bibimbap", "donburi"), ("falafel", "houmous"), ("shawarma", "gyros"),
        ("empanada", "arepa"), ("burrito", "quesadilla"), ("guacamole", "salsa"),
        ("ceviche", "tartare"), ("goulash", "borchtch"), ("moussaka", "parmigiana"),
        ("gaspacho", "vichyssoise"), ("bortsch", "minestrone"), ("polenta", "semoule"),
        ("naan", "pita"), ("tortilla", "galette"), ("bagel", "bretzel"),
        ("scone", "muffin"), ("baklava", "loukoum"), ("mochi", "dorayaki"),
        ("wasabi", "raifort"), ("kimchi", "pickles"),
    ),
    "Bébés animaux et groupes": (
        ("chaton", "chiot"), ("poulain", "ânon"), ("veau", "cabri"),
        ("porcelet", "agnelet"), ("faon", "marcassin"), ("ourson", "louveteau"),
        ("lionceau", "tigreau"), ("éléphanteau", "girafon"), ("têtard", "alevin"),
        ("larve", "nymphe"), ("troupeau", "harde"), ("meute", "horde"),
        ("nuée", "essaim"), ("volée", "nichée"), ("portée", "couvée"),
        ("terrier", "tanière"), ("gîte", "hutte"), ("ruche", "guêpier"),
        ("aquarium", "volière"), ("écurie", "chenil"), ("chenil", "clapier"),
    ),
    "Photographie": (
        ("objectif", "zoom"), ("flash", "réflecteur"), ("trépied", "monopode"),
        ("pellicule", "capteur"), ("obturateur", "diaphragme"), ("netteté", "profondeur"),
        ("contraste", "luminosité"), ("filtre", "gélatine"), ("portrait", "paysage"),
        ("selfie", "autoportrait"), ("album", "tirage"), ("négatif", "diapositive"),
        ("pose", "instantané"),
    ),
    "Roches et minéraux": (
        ("basalte", "obsidienne"), ("calcaire", "craie"), ("silex", "quartz"),
        ("schiste", "gneiss"), ("grès", "meulière"), ("gypse", "albâtre"),
        ("mica", "feldspath"), ("agate", "onyx"), ("jade", "turquoise"),
        ("ambre", "jais"), ("opale", "lapis"), ("pyrite", "galène"),
        ("filon", "veine"), ("carrière", "mine"), ("fossile", "empreinte"),
        ("cristal", "géode"), ("lave", "magma"), ("sédiment", "alluvion"),
    ),
    "Astronomie": (
        ("lune", "croissant"), ("éclipse", "transit"), ("constellation", "zodiaque"),
        ("mercure", "vénus"), ("mars", "jupiter"), ("saturne", "uranus"),
        ("neptune", "pluton"), ("anneau", "satellite"), ("cratère", "mer"),
        ("marée", "phase"), ("équinoxe", "solstice"), ("astrolabe", "sextant"),
        ("coupole", "monture"), ("oculaire", "miroir"), ("année-lumière", "parsec"),
        ("nébuleuse", "quasar"),
    ),
    "Danse": (
        ("salsa", "bachata"), ("rumba", "cha-cha"), ("flamenco", "sévillane"),
        ("claquettes", "charleston"), ("swing", "lindy"), ("hip-hop", "breakdance"),
        ("classique", "contemporain"), ("jazz", "modern"), ("folklore", "sarabande"),
        ("menuet", "gavotte"), ("polka", "mazurka"), ("quadrille", "farandole"),
        ("pirouette", "arabesque"), ("jeté", "plié"), ("tutu", "justaucorps"),
        ("chorégraphie", "improvisation"), ("duo", "ensemble"), ("bal", "guinguette"),
    ),
    "Vin et gastronomie": (
        ("cépage", "terroir"), ("vendange", "pressurage"), ("fût", "cuve"),
        ("carafe", "décanteur"), ("millésime", "assemblage"), ("tanin", "acidité"),
        ("bouquet", "finale"), ("dégustation", "accord"), ("cave", "chai"),
        ("sommelier", "caviste"), ("apéritif", "amuse-bouche"), ("nappe", "argenterie"),
        ("plat", "garniture"), ("sauce", "jus"), ("cuisson", "marinade"),
        ("dressage", "assaisonnement"), ("étoile", "toque"), ("brigade", "commis"),
        ("pourboire", "addition"),
    ),
    "Textile et couture": (
        ("bobine", "canette"), ("patron", "gabarit"), ("ourlet", "surpiqûre"),
        ("couture", "surjet"), ("fermeture", "pression"), ("bouton", "œillet"),
        ("biais", "passepoil"), ("doublure", "entoilage"), ("machine", "surjeteuse"),
        ("mannequin", "buste"), ("écheveau", "pelote"), ("maille", "point"),
        ("jersey", "molleton"), ("tweed", "flanelle"), ("popeline", "batiste"),
        ("teinture", "impression"),
    ),
    "Secours et sécurité": (
        ("alarme", "sirène"), ("extincteur", "lance"), ("civière", "brancard"),
        ("garrot", "compresse"), ("défibrillateur", "oxygène"), ("gyrophare", "avertisseur"),
        ("barrage", "cordon"), ("balise", "fumigène"), ("secouriste", "brancardier"),
        ("caserne", "poste"), ("exercice", "alerte"), ("issue", "sas"),
        ("plan", "consigne"), ("talkie", "radio"), ("maître-nageur", "surveillant"),
    ),
    "Bureau de poste et papeterie": (
        ("ramette", "bloc"), ("intercalaire", "onglet"), ("reliure", "spirale"),
        ("massicot", "cutter"), ("règle", "pochoir"), ("encre", "cartouche"),
        ("buvard", "sous-verre"), ("étiquette", "gommette"), ("élastique", "attache"),
        ("porte-mine", "recharge"), ("surligneur", "stabilo"), ("calendrier", "éphéméride"),
        ("globe", "planisphère"), ("tampon", "encreur"), ("balance", "affranchissement"),
    ),
    "Marché et étal": (
        ("bâche", "auvent"), ("balance", "poids"), ("primeur", "maraîcher"),
        ("crémier", "affineur"), ("volailler", "tripier"), ("rôtisseur", "traiteur"),
        ("criée", "enchère"), ("monnaie", "appoint"), ("caissette", "barquette"),
        ("glacière", "vitrine"),
    ),
    "Ferme et récolte": (
        ("moisson", "fenaison"), ("labour", "hersage"), ("sillon", "andain"),
        ("épi", "gerbe"), ("botte", "balle"), ("grain", "son"),
        ("meule", "silo"), ("batteuse", "ensileuse"), ("semoir", "épandeur"),
        ("étable", "stabulation"), ("traite", "tank"), ("pis", "trayon"),
        ("verger", "houblonnière"), ("rucher", "hausse"), ("pressoir", "alambic"),
        ("cidrerie", "distillerie"), ("greffe", "taille"), ("échalas", "palissage"),
    ),
    "Races et robes": (
        ("caniche", "teckel"), ("labrador", "beagle"), ("berger", "husky"),
        ("bouledogue", "carlin"), ("chihuahua", "yorkshire"), ("dalmatien", "dogue"),
        ("lévrier", "épagneul"), ("terrier", "setter"), ("siamois", "persan"),
        ("angora", "sphynx"), ("tigré", "tacheté"), ("moucheté", "pommelé"),
        ("bai", "alezan"), ("pie", "isabelle"), ("percheron", "pur-sang"),
        ("poney", "trait"), ("holstein", "charolaise"), ("limousine", "normande"),
        ("mérinos", "romanov"), ("leghorn", "wyandotte"),
    ),
    "Pain et viennoiserie": (
        ("miche", "boule"), ("bâtard", "flûte"), ("complet", "céréales"),
        ("seigle", "sarrasin"), ("levain", "poolish"), ("pétrin", "façonnage"),
        ("fournil", "banneton"), ("lame", "grigne"), ("croûton", "chapelure"),
        ("biscotte", "melba"), ("chouquette", "sacristain"), ("palmier", "torsade"),
        ("kouglof", "panettone"), ("stollen", "pandoro"), ("gaufrette", "tuile"),
    ),
    "Écrans et réseaux": (
        ("pixel", "résolution"), ("téléchargement", "diffusion"), ("abonnement", "essai"),
        ("profil", "avatar"), ("publication", "commentaire"), ("notification", "alerte"),
        ("émoji", "autocollant"), ("filtre", "effet"), ("story", "direct"),
        ("chaîne", "playlist"), ("wifi", "données"), ("antenne", "relais"),
        ("forfait", "recharge"), ("cadenas", "certificat"), ("cookie", "historique"),
        ("bug", "panne"), ("redémarrage", "réinitialisation"),
    ),
    "Décoration": (
        ("guirlande", "photophore"), ("bibelot", "figurine"), ("moulure", "corniche"),
        ("plinthe", "chambranle"), ("tenture", "voilage"), ("embrasse", "tringle"),
        ("descente", "carpette"), ("pouf", "repose-pied"), ("desserte", "sellette"),
        ("vitrine", "étagère"), ("bougeoir", "chandelier"), ("brûle-parfum", "diffuseur"),
        ("sculpture", "totem"), ("terrarium", "aquarium"), ("mobile", "attrape-rêves"),
    ),
    "Bricolage : mesures": (
        ("centimètre", "pouce"), ("gramme", "once"), ("litre", "pinte"),
        ("degré", "radian"), ("watt", "ampère"), ("volt", "ohm"),
        ("décibel", "hertz"), ("nœud", "mille"), ("hectare", "arpent"),
        ("tonne", "quintal"), ("baril", "boisseau"), ("carat", "titre"),
        ("épaisseur", "largeur"), ("volume", "surface"),
    ),
    "Épices et herbes": (
        ("aneth", "estragon"), ("sarriette", "marjolaine"), ("sauge", "verveine"),
        ("camomille", "tilleul"), ("badiane", "anis"), ("cumin", "carvi"),
        ("fenugrec", "sumac"), ("vanille", "tonka"), ("saumure", "marinade"),
    ),
    "Chaussures et cuir": (
        ("richelieu", "oxford"), ("brogue", "monk"), ("chelsea", "jodhpur"),
        ("compensée", "plateforme"), ("stiletto", "kitten"), ("trotteur", "derby"),
        ("cuissarde", "bottillon"), ("après-ski", "raquette"), ("charentaise", "babouche"),
        ("tannerie", "mégisserie"), ("croûte", "nubuck"), ("embauchoir", "chausse-pied"),
        ("trépointe", "contrefort"), ("bride", "salomé"),
    ),
    "Petits objets": (
        ("décapsuleur", "ouvre-boîte"), ("presse-ail", "dénoyauteur"), ("entonnoir", "louche"),
        ("écumoire", "araignée"), ("pilon", "fouet"), ("moulinette", "hachoir"),
        ("plumier", "écritoire"), ("boulier", "sablier"), ("clochette", "grelot"),
        ("sonnaille", "carillon"), ("boutonnière", "passant"), ("mousqueton", "anneau"),
        ("clapet", "valve"),
    ),
    "Sur la route": (
        ("autoroute", "nationale"), ("départementale", "chemin"), ("bretelle", "échangeur"),
        ("glissière", "muret"), ("ralentisseur", "chicane"), ("borne", "kilomètre"),
        ("bouchon", "ralentissement"), ("chantier", "cône"), ("tunnel", "viaduc"),
        ("dépanneuse", "remorquage"),
    ),
    "Encore des objets": (
        ("tabouret", "marchepied"), ("paravent", "claustra"), ("penderie", "vestiaire"),
        ("chevalet", "lutrin"), ("lutrin", "pupitre"), ("guéridon", "sellette"),
        ("hotte", "besace"), ("cruche", "pichet"), ("bassin", "cuvette"),
        ("écuelle", "gamelle"), ("timbale", "quart"), ("cafetière", "théière"),
        ("passoire", "égouttoir"), ("bougeoir", "photophore"), ("veilleuse", "lanterne"),
        ("chandelle", "torche"), ("soufflet", "tisonnier"), ("pelle", "balayette"),
        ("plumeau", "chiffon"), ("cintre", "housse"), ("besace", "musette"),
    ),
    "Encore des lieux": (
        ("belvédère", "kiosque"), ("pergola", "tonnelle"), ("véranda", "serre"),
        ("perron", "porche"), ("préau", "auvent"), ("cour", "patio"),
        ("venelle", "passage"), ("promenade", "corniche"), ("quai", "berge"),
        ("écluse", "moulin"), ("lavoir", "abreuvoir"), ("puits", "citerne"),
        ("chapelle", "calvaire"), ("cimetière", "ossuaire"), ("crypte", "catacombe"),
        ("bastion", "échauguette"), ("guérite", "tourelle"), ("halle", "arcade"),
        ("estaminet", "guinguette"), ("pension", "villégiature"), ("hameau", "bourg"),
        ("faubourg", "quartier"),
    ),
    "Encore des mots": (
        ("linteau", "seuil"), ("faîtage", "arêtier"), ("torchère", "applique"),
        ("baldaquin", "alcôve"), ("paillasse", "plan"), ("enseigne", "devanture"),
        ("store", "banne"), ("perron", "emmarchement"), ("soupirail", "vasistas"),
        ("courette", "impasse"), ("colombage", "torchis"), ("chaume", "bardeau"),
        ("zinc", "cuivre"), ("crépi", "badigeon"), ("lambris", "boiserie"),
        ("rosace", "tympan"), ("gargouille", "chapiteau"), ("nef", "transept"),
        ("chœur", "abside"), ("cloître", "déambulatoire"), ("jubé", "chaire"),
        ("bénitier", "fonts"), ("vitrail", "verrière"), ("clocheton", "flèche"),
        ("contrefort", "arc-boutant"), ("créneau", "mâchicoulis"), ("herse", "poterne"),
        ("échauguette", "barbacane"), ("glacis", "talus"), ("motte", "enceinte"),
        ("logis", "dépendance"), ("orangerie", "volière"), ("potager", "verger"),
    ),
}

WORD_PAIRS: tuple[WordPair, ...] = tuple(
    pair for pairs in PAIRS_BY_THEME.values() for pair in pairs
)


def theme_of(pair_index: int) -> str:
    """Le theme auquel appartient la paire d'indice donne."""
    seen = 0
    for theme, pairs in PAIRS_BY_THEME.items():
        if pair_index < seen + len(pairs):
            return theme
        seen += len(pairs)
    raise IndexError(pair_index)


class WordGenerator:
    """Tire une des paires du dictionnaire."""

    def __init__(
        self,
        pairs: Sequence[Sequence[str]] = WORD_PAIRS,
        rng: random.Random | None = None,
    ) -> None:
        if not pairs:
            raise ValueError("Il faut au moins une paire de mots")
        invalid = [
            i for i, pair in enumerate(pairs)
            if len(pair) != 2 or pair[0] == pair[1]
        ]
        if invalid:
            raise ValueError(
                f"Ces paires n'ont pas deux mots distincts : {invalid}"
            )
        self._pairs = tuple(tuple(pair) for pair in pairs)
        self._rng = rng or random.Random()

    def pair(self) -> WordPair:
        """Une paire au hasard.

        L'ordre est tire lui aussi : sans cela, le mot de la majorite
        serait toujours le premier ecrit, et un joueur qui connait la
        liste saurait dans quel camp il est.
        """
        first, second = self._rng.choice(self._pairs)
        return (first, second) if self._rng.random() < 0.5 else (second, first)

    def pair_count(self) -> int:
        """Nombre de paires du dictionnaire."""
        return len(self._pairs)
