"""Les paires de mots du jeu.

Chaque paire est écrite à la main. C'est le remplacement d'un système
par groupes de dix où l'on tirait deux mots au hasard : sur 45
combinaisons possibles par groupe, certaines étaient bonnes et d'autres
non, sans moyen de trier. Ici, **chaque tirage est une paire validée**.

Ce qui fait une bonne paire :

1. **Même nature.** Deux fruits, deux métiers, deux instruments — pas
   « gare » et « piscine », dont les indices n'ont rien en commun.
2. **Une seule différence saillante.** « courgette » et « concombre » se
   ressemblent, mais l'un se cuit et l'autre se croque. C'est cette
   unique différence qui permet de démasquer l'Undercover.
3. **Aucun synonyme.** « développeur » et « programmeur » se décrivent
   identiquement : les civils ne peuvent structurellement pas gagner.
4. **Aucun hyperonyme.** Pas de « chaussure » face à « botte » : le
   joueur qui a le mot général ne peut rien dire qui ne s'applique pas
   aussi à l'autre.
5. **Pas de différence de taille seule.** « lac » et « étang », c'est la
   même chose en plus petit — indécidable en un indice.
6. **Que des mots connus, et un seul mot par carte.** Un joueur qui
   reçoit « caracal » ne joue pas, il se tait. Rien qui contienne un
   espace non plus, sinon l'indice unique porterait sur deux idées.
7. **Aucun duo réflexe.** « bain » et « douche » vont par deux dans la
   tête de tout le monde : celui qui tire l'un sait aussitôt ce qu'a
   l'autre camp, et l'Undercover se fond sans effort. Il faut que le mot
   reçu laisse plusieurs voisins possibles.

Les contraires tombent sous la règle 7 autant que les duos d'usage :
« généreux » appelle « avare » aussi sûrement que « bain » appelle
« douche ». Les traits de caractère sont donc croisés sans rapport entre
eux plutôt qu'opposés deux à deux.

C'est encore la règle 7 qui explique **qu'un mot serve dans plusieurs
paires**, trois au maximum. « pomme » tombe tantôt avec « coing »,
tantôt avec « pêche » : le tenir ne renseigne sur rien. Un dictionnaire
où chaque mot n'aurait qu'un seul partenaire serait entièrement
prévisible dès qu'on le connaît — défaut supportable à 257 paires,
rédhibitoire à 2500.

Les règles 3, 4 et 7 ne se vérifient pas automatiquement : elles portent
sur ce que deux mots évoquent, pas sur leur forme. Elles s'appliquent à
la relecture, thème par thème. `tools/audit_words.py` couvre le reste —
doublons, mots trop sollicités, mots à espace — et signale les paires
proches de forme, qui sont des points à relire, pas un verdict.
"""

from __future__ import annotations

import random
from typing import Sequence

WordPair = tuple[str, str]

# Les themes servent a la relecture et a l'audit ; le tirage, lui, pioche
# uniformement dans WORD_PAIRS.
PAIRS_BY_THEME: dict[str, tuple[WordPair, ...]] = {
    "Ferme": (
        ("vache", "chèvre"), ("vache", "brebis"), ("chèvre", "truie"),
        ("mouton", "cochon"), ("mouton", "veau"), ("agneau", "veau"),
        ("agneau", "chevreau"), ("taureau", "bélier"), ("taureau", "étalon"),
        ("bélier", "bouc"), ("cheval", "âne"), ("cheval", "mulet"),
        ("poney", "âne"), ("poney", "mulet"), ("jument", "truie"),
        ("poule", "pintade"), ("poule", "oie"), ("coq", "paon"),
        ("canard", "oie"), ("canard", "dinde"), ("dinde", "pintade"),
        ("poussin", "caneton"), ("lapin", "cochon"), ("étable", "bergerie"),
        ("étable", "poulailler"), ("grange", "silo"), ("grange", "hangar"),
        ("enclos", "pâturage"), ("clôture", "haie"), ("blé", "orge"),
        ("blé", "seigle"), ("avoine", "orge"), ("maïs", "seigle"),
        ("tracteur", "moissonneuse"), ("ruche", "poulailler"), ("avoine", "seigle"),
        ("hangar", "silo"), ("bergerie", "poulailler"), ("enclos", "haie"),
        ("coq", "canard"), ("chevreau", "caneton"), ("agneau", "poussin"),
        ("truie", "brebis"), ("bouc", "étalon"), ("lapin", "chèvre"),
        ("veau", "poney"), ("mulet", "taureau"), ("grange", "étable"),
        ("berger", "ruche"),
    ),
    "Animaux sauvages": (
        ("lion", "tigre"), ("lion", "guépard"), ("tigre", "panthère"),
        ("guépard", "léopard"), ("panthère", "lynx"), ("lynx", "puma"),
        ("loup", "renard"), ("loup", "chacal"), ("renard", "blaireau"),
        ("hyène", "chacal"), ("ours", "sanglier"), ("ours", "panda"),
        ("panda", "koala"), ("koala", "paresseux"), ("singe", "gorille"),
        ("gorille", "chimpanzé"), ("chimpanzé", "babouin"), ("éléphant", "rhinocéros"),
        ("rhinocéros", "hippopotame"), ("hippopotame", "buffle"), ("girafe", "zèbre"),
        ("zèbre", "antilope"), ("antilope", "gazelle"), ("cerf", "élan"),
        ("cerf", "chevreuil"), ("renne", "élan"), ("bison", "buffle"),
        ("sanglier", "phacochère"), ("kangourou", "autruche"), ("chameau", "lama"),
        ("dromadaire", "lama"), ("écureuil", "marmotte"), ("souris", "musaraigne"),
        ("rat", "mulot"), ("hérisson", "taupe"), ("taupe", "blaireau"),
        ("castor", "loutre"), ("loutre", "phoque"), ("phoque", "morse"),
        ("morse", "otarie"), ("chauve-souris", "hibou"), ("belette", "furet"),
        ("suricate", "marmotte"), ("gnou", "buffle"), ("lion", "ours"),
        ("loup", "lynx"), ("tigre", "hyène"), ("girafe", "chameau"),
        ("éléphant", "bison"), ("singe", "koala"), ("cerf", "sanglier"),
        ("renard", "belette"), ("castor", "marmotte"), ("hérisson", "opossum"),
        ("morse", "loutre"), ("kangourou", "paresseux"), ("zèbre", "gnou"),
        ("puma", "chacal"), ("écureuil", "furet"), ("gazelle", "renne"),
        ("panda", "suricate"), ("guépard", "gazelle"), ("panthère", "puma"),
        ("gorille", "babouin"), ("éléphant", "girafe"), ("hippopotame", "bison"),
        ("kangourou", "suricate"), ("chameau", "dromadaire"), ("lama", "gnou"),
        ("écureuil", "souris"), ("blaireau", "opossum"), ("singe", "rat"),
    ),
    "Oiseaux": (
        ("aigle", "faucon"), ("aigle", "vautour"), ("faucon", "épervier"),
        ("buse", "épervier"), ("vautour", "condor"), ("corbeau", "pie"),
        ("pie", "geai"), ("moineau", "mésange"), ("moineau", "rouge-gorge"),
        ("mésange", "chardonneret"), ("merle", "grive"), ("merle", "étourneau"),
        ("rossignol", "alouette"), ("hirondelle", "martinet"), ("pigeon", "tourterelle"),
        ("pigeon", "mouette"), ("mouette", "goéland"), ("goéland", "cormoran"),
        ("cygne", "oie"), ("cygne", "flamant"), ("héron", "cigogne"),
        ("cigogne", "grue"), ("grue", "flamant"), ("pélican", "cormoran"),
        ("manchot", "autruche"), ("autruche", "émeu"), ("paon", "faisan"),
        ("faisan", "perdrix"), ("perdrix", "caille"), ("perroquet", "toucan"),
        ("perroquet", "ara"), ("perruche", "canari"), ("canari", "chardonneret"),
        ("colibri", "martinet"), ("coucou", "grive"), ("albatros", "condor"),
        ("nid", "terrier"), ("plume", "écaille"), ("aile", "nageoire"),
        ("aigle", "cygne"), ("corbeau", "moineau"), ("hibou", "paon"),
        ("mouette", "héron"), ("perroquet", "canari"), ("pigeon", "faisan"),
        ("hirondelle", "merle"), ("cigogne", "vautour"), ("colibri", "toucan"),
        ("caille", "grive"), ("flamant", "pélican"), ("geai", "pinson"),
        ("buse", "coucou"), ("plume", "nid"), ("faucon", "condor"),
        ("hibou", "pie"), ("mésange", "rossignol"), ("héron", "grue"),
        ("toucan", "ara"), ("albatros", "martinet"), ("coucou", "alouette"),
        ("étourneau", "tourterelle"),
    ),
    "Mer et rivière": (
        ("dauphin", "requin"), ("requin", "raie"), ("baleine", "cachalot"),
        ("baleine", "orque"), ("orque", "narval"), ("thon", "saumon"),
        ("thon", "maquereau"), ("saumon", "truite"), ("truite", "carpe"),
        ("carpe", "brochet"), ("sardine", "anchois"), ("hareng", "maquereau"),
        ("anguille", "murène"), ("poulpe", "seiche"), ("seiche", "calmar"),
        ("méduse", "anémone"), ("étoile", "oursin"), ("oursin", "anémone"),
        ("crabe", "homard"), ("homard", "langouste"), ("crevette", "écrevisse"),
        ("écrevisse", "langoustine"), ("moule", "huître"), ("huître", "coquille"),
        ("bulot", "bigorneau"), ("corail", "algue"), ("algue", "plancton"),
        ("hippocampe", "poisson-clown"), ("tortue", "crocodile"), ("otarie", "phoque"),
        ("marée", "courant"), ("dauphin", "baleine"), ("orque", "cachalot"),
        ("narval", "hippocampe"), ("thon", "sardine"), ("saumon", "hareng"),
        ("brochet", "anguille"), ("anchois", "crevette"), ("crabe", "langoustine"),
        ("homard", "écrevisse"), ("poulpe", "calmar"), ("seiche", "méduse"),
        ("plancton", "coquille"),
    ),
    "Insectes et petites bêtes": (
        ("abeille", "guêpe"), ("abeille", "bourdon"), ("guêpe", "frelon"),
        ("papillon", "libellule"), ("papillon", "mite"), ("fourmi", "termite"),
        ("fourmi", "cloporte"), ("termite", "cafard"), ("cafard", "punaise"),
        ("puce", "pou"), ("pou", "tique"), ("tique", "acarien"),
        ("moustique", "moucheron"), ("taon", "moustique"), ("criquet", "sauterelle"),
        ("sauterelle", "grillon"), ("grillon", "cigale"), ("coccinelle", "scarabée"),
        ("scarabée", "hanneton"), ("araignée", "scorpion"), ("scorpion", "mille-pattes"),
        ("limace", "ver"), ("toile", "nid"), ("crapaud", "salamandre"),
        ("salamandre", "triton"), ("lézard", "gecko"), ("gecko", "caméléon"),
        ("caméléon", "iguane"), ("cobra", "python"), ("python", "boa"),
        ("boa", "anaconda"), ("abeille", "frelon"), ("guêpe", "bourdon"),
        ("papillon", "coccinelle"), ("libellule", "cigale"), ("fourmi", "puce"),
        ("termite", "cloporte"), ("cafard", "moustique"), ("mite", "taon"),
        ("criquet", "grillon"), ("sauterelle", "hanneton"), ("scarabée", "araignée"),
        ("crapaud", "triton"), ("lézard", "caméléon"), ("gecko", "iguane"),
        ("acarien", "punaise"),
    ),
    "Fruits": (
        ("pomme", "coing"), ("poire", "prune"), ("pêche", "abricot"),
        ("abricot", "prune"), ("cerise", "groseille"), ("cerise", "prune"),
        ("fraise", "framboise"), ("framboise", "mûre"), ("mûre", "myrtille"),
        ("myrtille", "groseille"), ("cassis", "groseille"), ("raisin", "figue"),
        ("figue", "datte"), ("datte", "pruneau"), ("banane", "mangue"),
        ("mangue", "papaye"), ("papaye", "goyave"), ("ananas", "mangue"),
        ("orange", "mandarine"), ("citron", "pamplemousse"), ("pamplemousse", "orange"),
        ("kiwi", "litchi"), ("litchi", "grenade"), ("noix", "noisette"),
        ("noisette", "amande"), ("amande", "pistache"), ("cacahuète", "pistache"),
        ("avocat", "olive"), ("peau", "écorce"), ("verger", "vigne"),
        ("panier", "cageot"), ("abricot", "figue"), ("fraise", "cassis"),
        ("banane", "datte"), ("noix", "cacahuète"), ("pastèque", "courge"),
        ("mandarine", "litchi"), ("ananas", "goyave"), ("coing", "pruneau"),
        ("avocat", "kiwi"), ("papaye", "pamplemousse"), ("pêche", "raisin"),
        ("pomme", "pêche"), ("cerise", "myrtille"), ("fraise", "mûre"),
        ("cassis", "raisin"), ("pastèque", "grenade"), ("kiwi", "goyave"),
        ("noix", "pistache"), ("amande", "cacahuète"), ("courge", "vigne"),
    ),
    "Légumes": (
        ("carotte", "navet"), ("navet", "radis"), ("radis", "betterave"),
        ("betterave", "céleri"), ("tomate", "poivron"), ("poivron", "piment"),
        ("piment", "paprika"), ("courgette", "concombre"), ("courgette", "aubergine"),
        ("aubergine", "poivron"), ("courge", "potiron"), ("oignon", "échalote"),
        ("échalote", "ail"), ("ail", "poireau"), ("poireau", "asperge"),
        ("asperge", "haricot"), ("salade", "épinard"), ("épinard", "blette"),
        ("blette", "chou"), ("chou", "brocoli"), ("brocoli", "chou-fleur"),
        ("artichaut", "chou-fleur"), ("endive", "fenouil"), ("fenouil", "céleri"),
        ("champignon", "truffe"), ("champignon", "cèpe"), ("cèpe", "girolle"),
        ("maïs", "quinoa"), ("riz", "semoule"), ("potager", "serre"),
        ("carotte", "poireau"), ("tomate", "aubergine"), ("radis", "endive"),
        ("betterave", "artichaut"), ("navet", "fenouil"), ("chou-fleur", "haricot"),
        ("épinard", "asperge"), ("oignon", "piment"), ("courgette", "potiron"),
        ("blette", "brocoli"), ("maïs", "riz"), ("endive", "céleri"),
        ("riz", "quinoa"),
    ),
    "Plats": (
        ("pizza", "quiche"), ("quiche", "tourte"), ("burger", "sandwich"),
        ("sandwich", "wrap"), ("wrap", "kebab"), ("hot-dog", "kebab"),
        ("sushi", "maki"), ("maki", "nem"), ("nem", "samoussa"),
        ("raviolis", "gnocchis"), ("gnocchis", "spaghettis"), ("spaghettis", "tagliatelles"),
        ("lasagnes", "cannellonis"), ("risotto", "paella"), ("paella", "couscous"),
        ("couscous", "tajine"), ("tajine", "curry"), ("curry", "chili"),
        ("ragoût", "pot-au-feu"), ("pot-au-feu", "blanquette"), ("blanquette", "bourguignon"),
        ("gratin", "clafoutis"), ("frites", "chips"), ("chips", "beignets"),
        ("beignet", "croquette"), ("croquette", "nugget"), ("soupe", "velouté"),
        ("velouté", "bouillon"), ("salade", "taboulé"), ("taboulé", "coleslaw"),
        ("crêpe", "galette"), ("galette", "gaufre"), ("fondue", "tartiflette"),
        ("choucroute", "cassoulet"), ("cassoulet", "chili"), ("rôti", "grillade"),
        ("grillade", "brochette"), ("brochette", "kebab"), ("steak", "escalope"),
        ("escalope", "côtelette"), ("saucisse", "merguez"), ("merguez", "chipolata"),
        ("pizza", "lasagnes"), ("sushi", "samoussa"), ("couscous", "risotto"),
        ("soupe", "salade"), ("omelette", "gratin"), ("crêpe", "gaufre"),
        ("frites", "purée"), ("steak", "saucisse"), ("brochette", "croquette"),
        ("blanquette", "ragoût"), ("chips", "nugget"), ("pizza", "tourte"),
        ("quiche", "gratin"), ("raviolis", "lasagnes"), ("tajine", "chili"),
        ("cassoulet", "ragoût"), ("pot-au-feu", "choucroute"), ("soupe", "bouillon"),
        ("velouté", "purée"), ("nugget", "escalope"), ("steak", "côtelette"),
        ("saucisse", "chipolata"), ("coleslaw", "fondue"), ("tartiflette", "clafoutis"),
    ),
    "Desserts et sucreries": (
        ("gâteau", "tarte"), ("gâteau", "cake"), ("tarte", "flan"),
        ("éclair", "religieuse"), ("religieuse", "chou"), ("macaron", "meringue"),
        ("meringue", "guimauve"), ("guimauve", "nougat"), ("nougat", "praline"),
        ("praline", "truffe"), ("bonbon", "sucette"), ("sucette", "chewing-gum"),
        ("chocolat", "praliné"), ("glace", "sorbet"), ("sorbet", "granité"),
        ("granité", "smoothie"), ("croissant", "brioche"), ("brioche", "chausson"),
        ("chausson", "beignet"), ("madeleine", "financier"), ("financier", "cannelé"),
        ("cookie", "biscuit"), ("biscuit", "sablé"), ("sablé", "spéculoos"),
        ("gaufre", "churro"), ("compote", "confiture"), ("confiture", "gelée"),
        ("miel", "sirop"), ("sucre", "vanille"), ("cupcake", "muffin"),
        ("donut", "beignet"), ("pâte", "glaçage"), ("gâteau", "flan"),
        ("tarte", "crumble"), ("glace", "granité"), ("bonbon", "nougat"),
        ("macaron", "madeleine"), ("cookie", "spéculoos"), ("chocolat", "caramel"),
        ("éclair", "cannelé"), ("muffin", "donut"), ("compote", "gelée"),
        ("sorbet", "milkshake"), ("praline", "caramel"), ("chocolat", "vanille"),
        ("bonbon", "chewing-gum"), ("sucette", "biscuit"), ("spéculoos", "madeleine"),
        ("donut", "churro"), ("sucre", "truffe"),
    ),
    "Boissons": (
        ("expresso", "cappuccino"), ("cappuccino", "latte"), ("jus", "nectar"),
        ("nectar", "smoothie"), ("soda", "limonade"), ("limonade", "tonic"),
        ("cola", "tonic"), ("sirop", "grenadine"), ("bière", "cidre"),
        ("vin", "champagne"), ("champagne", "mousseux"), ("rosé", "sangria"),
        ("whisky", "rhum"), ("rhum", "vodka"), ("vodka", "gin"),
        ("gin", "tequila"), ("cocktail", "punch"), ("punch", "sangria"),
        ("milkshake", "smoothie"), ("chope", "gobelet"), ("carafe", "pichet"),
        ("bouteille", "gourde"), ("bar", "terrasse"), ("tonneau", "fût"),
        ("mousseux", "sangria"), ("whisky", "gin"), ("tequila", "punch"),
        ("cola", "limonade"), ("soda", "tonic"), ("expresso", "latte"),
        ("rosé", "milkshake"),
    ),
    "Épicerie": (
        ("pain", "baguette"), ("baguette", "ficelle"), ("farine", "levure"),
        ("levure", "bicarbonate"), ("moutarde", "mayonnaise"), ("mayonnaise", "ketchup"),
        ("ketchup", "harissa"), ("sel", "sucre"), ("poivre", "muscade"),
        ("muscade", "cannelle"), ("cannelle", "gingembre"), ("gingembre", "curcuma"),
        ("curcuma", "safran"), ("basilic", "persil"), ("persil", "coriandre"),
        ("coriandre", "menthe"), ("thym", "romarin"), ("romarin", "laurier"),
        ("laurier", "origan"), ("camembert", "brie"), ("brie", "roquefort"),
        ("roquefort", "gorgonzola"), ("comté", "gruyère"), ("feta", "mozzarella"),
        ("mozzarella", "burrata"), ("crème", "mascarpone"), ("jambon", "saucisson"),
        ("saucisson", "chorizo"), ("chorizo", "salami"), ("pâté", "rillettes"),
        ("rillettes", "terrine"), ("bocal", "conserve"), ("boîte", "sachet"),
        ("ficelle", "farine"), ("sel", "poivre"), ("safran", "basilic"),
        ("menthe", "thym"), ("origan", "camembert"), ("gorgonzola", "comté"),
        ("gruyère", "feta"), ("jambon", "chorizo"), ("saucisson", "salami"),
        ("conserve", "sachet"),
    ),
    "Vêtements": (
        ("chemise", "polo"), ("polo", "tee-shirt"), ("tee-shirt", "débardeur"),
        ("pull", "gilet"), ("pull", "sweat"), ("sweat", "hoodie"),
        ("gilet", "cardigan"), ("veste", "blazer"), ("blazer", "smoking"),
        ("manteau", "parka"), ("parka", "doudoune"), ("doudoune", "anorak"),
        ("imperméable", "ciré"), ("cape", "poncho"), ("poncho", "châle"),
        ("robe", "tunique"), ("tunique", "jupe"), ("jupe", "kilt"),
        ("pantalon", "jean"), ("short", "bermuda"), ("collant", "bas"),
        ("pyjama", "peignoir"), ("peignoir", "kimono"), ("maillot", "combinaison"),
        ("combinaison", "salopette"), ("costume", "tailleur"), ("caleçon", "boxer"),
        ("chaussette", "chausson"), ("manche", "col"), ("col", "revers"),
        ("poche", "doublure"), ("ourlet", "pli"), ("tissu", "cuir"),
        ("laine", "coton"), ("coton", "lin"), ("lin", "soie"),
        ("soie", "velours"), ("velours", "satin"), ("dentelle", "broderie"),
        ("chemise", "pull"), ("robe", "salopette"), ("jean", "short"),
        ("manteau", "cape"), ("pyjama", "maillot"), ("jupe", "bermuda"),
        ("costume", "uniforme"), ("kimono", "poncho"), ("anorak", "blazer"),
        ("collant", "chaussette"), ("laine", "dentelle"), ("velours", "cuir"),
        ("coton", "satin"), ("manche", "poche"), ("tunique", "débardeur"),
        ("cardigan", "sweat"), ("veste", "manteau"), ("parka", "anorak"),
        ("doudoune", "imperméable"), ("uniforme", "tailleur"), ("revers", "poche"),
        ("doublure", "ourlet"), ("pli", "bouton"),
    ),
    "Chaussures et accessoires": (
        ("basket", "mocassin"), ("escarpin", "ballerine"), ("bottine", "santiag"),
        ("sandale", "tong"), ("tong", "claquette"), ("espadrille", "sandale"),
        ("lacet", "boucle"), ("semelle", "talon"), ("casquette", "bonnet"),
        ("bonnet", "cagoule"), ("béret", "turban"), ("turban", "bandana"),
        ("écharpe", "foulard"), ("foulard", "châle"), ("gant", "moufle"),
        ("moufle", "mitaine"), ("ceinture", "bretelles"), ("lunettes", "masque"),
        ("masque", "visière"), ("sac", "cabas"), ("cabas", "besace"),
        ("sacoche", "pochette"), ("valise", "malle"), ("malle", "coffre"),
        ("éventail", "ombrelle"), ("mouchoir", "serviette"), ("claquette", "espadrille"),
        ("lacet", "semelle"), ("casquette", "béret"), ("mitaine", "ceinture"),
        ("bretelles", "lunettes"), ("éventail", "mouchoir"), ("besace", "sacoche"),
        ("pochette", "valise"), ("serviette", "châle"),
    ),
    "Bijoux et parures": (
        ("bague", "chevalière"), ("bague", "alliance"), ("pendentif", "médaillon"),
        ("bracelet", "gourmette"), ("boucle", "créole"), ("créole", "puce"),
        ("broche", "épingle"), ("épingle", "barrette"), ("diadème", "couronne"),
        ("couronne", "tiare"), ("chaîne", "cordon"), ("diamant", "rubis"),
        ("rubis", "saphir"), ("saphir", "émeraude"), ("émeraude", "topaze"),
        ("améthyste", "topaze"), ("argent", "bronze"), ("bronze", "cuivre"),
    ),
    "Corps humain": (
        ("coude", "genou"), ("genou", "cheville"), ("poignet", "cheville"),
        ("épaule", "hanche"), ("hanche", "taille"), ("pouce", "index"),
        ("ongle", "cheveu"), ("cheveu", "poil"), ("front", "menton"),
        ("menton", "joue"), ("joue", "tempe"), ("nez", "oreille"),
        ("œil", "sourcil"), ("lèvre", "paupière"), ("dent", "gencive"),
        ("gorge", "nuque"), ("torse", "hanche"), ("cœur", "poumon"),
        ("poumon", "foie"), ("foie", "rein"), ("rein", "estomac"),
        ("cerveau", "moelle"), ("os", "cartilage"), ("muscle", "tendon"),
        ("tendon", "ligament"), ("peau", "ongle"), ("crâne", "mâchoire"),
        ("côte", "vertèbre"), ("ride", "cicatrice"), ("genou", "épaule"),
        ("poignet", "nuque"), ("dent", "langue"), ("cœur", "rein"),
        ("foie", "estomac"), ("poumon", "cerveau"), ("os", "muscle"),
        ("tendon", "vertèbre"), ("crâne", "côte"), ("talon", "pouce"),
        ("gorge", "gencive"), ("moelle", "cartilage"), ("coude", "poignet"),
        ("taille", "torse"), ("ongle", "poil"), ("cheveu", "sourcil"),
        ("front", "joue"), ("menton", "tempe"), ("lèvre", "gencive"),
        ("moelle", "os"), ("muscle", "ligament"), ("paupière", "œil"),
    ),
    "Santé et soins": (
        ("rhume", "grippe"), ("grippe", "angine"), ("angine", "bronchite"),
        ("toux", "éternuement"), ("fièvre", "frisson"), ("migraine", "vertige"),
        ("nausée", "vertige"), ("bosse", "égratignure"), ("coupure", "brûlure"),
        ("brûlure", "ampoule"), ("entorse", "fracture"), ("fracture", "luxation"),
        ("piqûre", "morsure"), ("allergie", "eczéma"), ("eczéma", "urticaire"),
        ("carie", "abcès"), ("pansement", "bandage"), ("bandage", "attelle"),
        ("plâtre", "attelle"), ("béquille", "canne"), ("canne", "déambulateur"),
        ("seringue", "perfusion"), ("comprimé", "gélule"), ("thermomètre", "tensiomètre"),
        ("scanner", "échographie"), ("vaccin", "rappel"), ("infirmerie", "urgences"),
        ("massage", "étirement"), ("rhume", "toux"), ("grippe", "fièvre"),
        ("migraine", "nausée"), ("vertige", "frisson"), ("ampoule", "piqûre"),
        ("morsure", "allergie"), ("pansement", "compresse"), ("déambulateur", "seringue"),
        ("perfusion", "comprimé"), ("gélule", "vaccin"), ("tensiomètre", "scanner"),
        ("éternuement", "rappel"),
    ),
    "Pièces et bâti": (
        ("salon", "véranda"), ("cave", "cellier"), ("chambre", "bureau"),
        ("bureau", "atelier"), ("atelier", "garage"), ("balcon", "terrasse"),
        ("terrasse", "patio"), ("couloir", "palier"), ("palier", "vestibule"),
        ("entrée", "vestibule"), ("escalier", "échelle"), ("échelle", "rampe"),
        ("buanderie", "cellier"), ("dressing", "penderie"), ("mansarde", "grenier"),
        ("mur", "cloison"), ("plancher", "parquet"), ("parquet", "carrelage"),
        ("carrelage", "lino"), ("moquette", "lino"), ("portail", "grille"),
        ("fenêtre", "lucarne"), ("lucarne", "hublot"), ("volet", "persienne"),
        ("store", "rideau"), ("tuile", "ardoise"), ("cheminée", "poêle"),
        ("clé", "verrou"), ("verrou", "loquet"), ("poignée", "bouton"),
        ("radiateur", "climatiseur"), ("escalier", "rampe"), ("buanderie", "dressing"),
        ("penderie", "cloison"), ("mur", "plancher"), ("persienne", "store"),
        ("rideau", "portail"),
    ),
    "Meubles": (
        ("table", "comptoir"), ("chaise", "tabouret"), ("canapé", "fauteuil"),
        ("fauteuil", "pouf"), ("pouf", "coussin"), ("lit", "hamac"),
        ("hamac", "matelas"), ("matelas", "sommier"), ("berceau", "couffin"),
        ("armoire", "commode"), ("commode", "buffet"), ("buffet", "vaisselier"),
        ("étagère", "bibliothèque"), ("placard", "penderie"), ("tiroir", "casier"),
        ("casier", "coffre"), ("paravent", "cloison"), ("chevet", "commode"),
        ("parasol", "store"), ("tapis", "paillasson"), ("lampadaire", "applique"),
        ("abat-jour", "globe"), ("cadre", "toile"), ("table", "étagère"),
        ("chaise", "coussin"), ("canapé", "lit"), ("armoire", "tiroir"),
        ("bibliothèque", "vaisselier"), ("berceau", "banquette"), ("tapis", "paravent"),
        ("cadre", "globe"), ("chevet", "guéridon"), ("sommier", "couffin"),
        ("parasol", "abat-jour"), ("placard", "tiroir"), ("miroir", "cadre"),
        ("paillasson", "parasol"), ("abat-jour", "chevet"),
    ),
    "Cuisine : ustensiles": (
        ("assiette", "bol"), ("assiette", "coupelle"), ("bol", "ramequin"),
        ("saladier", "plat"), ("plat", "terrine"), ("tasse", "mug"),
        ("mug", "bol"), ("fourchette", "pique"), ("cuillère", "louche"),
        ("louche", "écumoire"), ("couteau", "éplucheur"), ("éplucheur", "râpe"),
        ("ciseaux", "pince"), ("pince", "spatule"), ("fouet", "batteur"),
        ("batteur", "mixeur"), ("mixeur", "blender"), ("casserole", "poêle"),
        ("poêle", "wok"), ("wok", "sauteuse"), ("cocotte", "marmite"),
        ("marmite", "faitout"), ("passoire", "tamis"), ("rouleau", "pilon"),
        ("moule", "ramequin"), ("plaque", "grille"), ("minuteur", "sablier"),
        ("tablier", "toque"), ("bouchon", "capsule"), ("tire-bouchon", "décapsuleur"),
        ("essoreuse", "égouttoir"), ("bocal", "boîte"), ("moulin", "salière"),
        ("casserole", "cocotte"), ("wok", "faitout"), ("fouet", "écumoire"),
        ("passoire", "râpe"), ("cuillère", "pique"), ("saladier", "terrine"),
        ("tasse", "ramequin"), ("bouchon", "salière"), ("torchon", "tablier"),
        ("plaque", "boîte"), ("fourchette", "cuillère"), ("faitout", "grille"),
        ("planche", "rouleau"), ("pilon", "salière"),
        ("tire-bouchon", "essoreuse"), ("égouttoir", "torchon"),
    ),
    "Salle de bain": (
        ("baignoire", "jacuzzi"), ("douche", "cabine"), ("vasque", "évier"),
        ("robinet", "mitigeur"), ("mousse", "gel"), ("sèche-cheveux", "lisseur"),
        ("rasoir", "tondeuse"), ("déodorant", "talc"), ("parfum", "lotion"),
        ("sèche-cheveux", "rasoir"), ("talc", "lotion"),
    ),
    "Électroménager": (
        ("plaque", "réchaud"), ("congélateur", "glacière"), ("sèche-linge", "étendoir"),
        ("aspirateur", "balai"), ("balai", "serpillière"), ("bouilloire", "cafetière"),
        ("cafetière", "percolateur"), ("grille-pain", "gaufrier"), ("gaufrier", "crêpière"),
        ("friteuse", "cuiseur"), ("robot", "hachoir"), ("presse-agrumes", "centrifugeuse"),
        ("yaourtière", "sorbetière"), ("télévision", "vidéoprojecteur"), ("enceinte", "casque"),
        ("radio", "réveil"), ("téléphone", "tablette"), ("chargeur", "batterie"),
        ("ampoule", "néon"), ("rallonge", "multiprise"), ("cuiseur", "réchaud"),
        ("bouilloire", "percolateur"), ("cafetière", "crêpière"), ("gaufrier", "hachoir"),
        ("serpillière", "étendoir"), ("sèche-linge", "radio"), ("chargeur", "rallonge"),
        ("multiprise", "néon"),
    ),
    "Outils et bricolage": (
        ("tournevis", "clé"), ("clé", "pince"), ("tenaille", "cisaille"),
        ("perceuse", "visseuse"), ("visseuse", "meuleuse"), ("burin", "ciseau"),
        ("mètre", "équerre"), ("équerre", "compas"), ("étau", "serre-joint"),
        ("établi", "tréteau"), ("échelle", "escabeau"), ("escabeau", "échafaudage"),
        ("vis", "boulon"), ("cheville", "rivet"), ("colle", "mastic"),
        ("mastic", "silicone"), ("ruban", "adhésif"), ("peinture", "vernis"),
        ("pinceau", "rouleau"), ("truelle", "spatule"), ("bétonnière", "brouette"),
        ("ciment", "plâtre"), ("plâtre", "enduit"), ("brique", "parpaing"),
        ("planche", "poutre"), ("clou", "agrafe"), ("casque", "gants"),
        ("scie", "perceuse"), ("tenaille", "burin"), ("mètre", "compas"),
        ("étau", "tréteau"), ("clou", "rivet"), ("colle", "silicone"),
        ("pinceau", "truelle"), ("ciment", "parpaing"), ("ruban", "agrafe"),
        ("meuleuse", "ponceuse"), ("serre-joint", "établi"), ("tréteau", "escabeau"),
        ("boulon", "rivet"), ("adhésif", "peinture"), ("enduit", "brique"),
        ("parpaing", "poutre"), ("gants", "spatule"),
    ),
    "Jardin": (
        ("arrosoir", "seau"), ("arrosoir", "pulvérisateur"), ("râteau", "pelle"),
        ("bêche", "fourche"), ("sécateur", "cisaille"), ("cisaille", "taille-haie"),
        ("tondeuse", "débroussailleuse"), ("brouette", "chariot"), ("tronçonneuse", "hache"),
        ("gant", "genouillère"), ("pot", "jardinière"), ("jardinière", "bac"),
        ("terreau", "compost"), ("engrais", "fumier"), ("graine", "bulbe"),
        ("bulbe", "bouture"), ("tuteur", "treillis"), ("treillis", "pergola"),
        ("clôture", "barrière"), ("portillon", "barrière"), ("allée", "sentier"),
        ("bassin", "mare"), ("fontaine", "cascade"), ("nichoir", "mangeoire"),
        ("barbecue", "plancha"), ("hamac", "balançoire"), ("niche", "clapier"),
        ("arrosoir", "brouette"), ("tondeuse", "tronçonneuse"), ("terreau", "fumier"),
        ("graine", "bouture"), ("serre", "pergola"), ("clôture", "portillon"),
        ("bassin", "fontaine"), ("nichoir", "épouvantail"), ("barbecue", "balançoire"),
        ("seau", "bac"), ("terreau", "engrais"), ("fumier", "compost"),
        ("portillon", "allée"), ("mare", "fontaine"), ("cascade", "nichoir"),
        ("mangeoire", "épouvantail"),
    ),
    "Véhicules": (
        ("voiture", "camionnette"), ("camion", "benne"), ("benne", "citerne"),
        ("bus", "autocar"), ("autocar", "navette"), ("tramway", "trolleybus"),
        ("métro", "funiculaire"), ("funiculaire", "téléphérique"), ("train", "locomotive"),
        ("wagon", "fourgon"), ("moto", "scooter"), ("vélo", "trottinette"),
        ("tandem", "tricycle"), ("skateboard", "roller"), ("tracteur", "bulldozer"),
        ("bulldozer", "pelleteuse"), ("ambulance", "taxi"), ("taxi", "limousine"),
        ("corbillard", "fourgon"), ("caravane", "camping-car"), ("remorque", "attelage"),
        ("calèche", "diligence"), ("charrette", "carriole"), ("traîneau", "luge"),
        ("quad", "buggy"), ("pédale", "manette"), ("frein", "embrayage"),
        ("moteur", "batterie"), ("phare", "clignotant"), ("rétroviseur", "pare-brise"),
        ("klaxon", "sirène"), ("péage", "parking"), ("station", "garage"),
        ("camion", "autocar"), ("moto", "quad"), ("vélo", "roller"),
        ("tramway", "funiculaire"), ("train", "métro"), ("tracteur", "pelleteuse"),
        ("caravane", "remorque"), ("traîneau", "charrette"), ("roue", "phare"),
        ("moteur", "klaxon"), ("portière", "rétroviseur"), ("diligence", "carriole"),
        ("skateboard", "tricycle"), ("bus", "trolleybus"), ("citerne", "fourgon"),
        ("wagon", "remorque"), ("ambulance", "corbillard"), ("portière", "klaxon"),
        ("sirène", "manette"),
    ),
    "Bateaux et eau": (
        ("voilier", "goélette"), ("goélette", "caravelle"), ("ferry", "paquebot"),
        ("paquebot", "cargo"), ("cargo", "pétrolier"), ("remorqueur", "brise-glace"),
        ("canoë", "kayak"), ("kayak", "pirogue"), ("pédalo", "barque"),
        ("radeau", "ponton"), ("jet-ski", "hors-bord"), ("torpille", "mine"),
        ("gouvernail", "quille"), ("ancre", "amarre"), ("bouée", "balise"),
        ("hublot", "écoutille"), ("cabine", "soute"), ("port", "quai"),
        ("quai", "jetée"), ("digue", "écluse"), ("écluse", "canal"),
        ("marin", "capitaine"), ("voilier", "caravelle"), ("pirogue", "pédalo"),
        ("barque", "radeau"), ("jetée", "digue"), ("phare", "capitaine"),
    ),
    "Air et espace": (
        ("avion", "jet"), ("jet", "planeur"), ("planeur", "deltaplane"),
        ("deltaplane", "parapente"), ("montgolfière", "dirigeable"), ("parachute", "aile"),
        ("drone", "satellite"), ("fusée", "navette"), ("navette", "capsule"),
        ("sonde", "rover"), ("hublot", "cockpit"), ("aile", "hélice"),
        ("hélice", "réacteur"), ("piste", "hangar"), ("scaphandre", "combinaison"),
        ("planète", "astéroïde"), ("astéroïde", "comète"), ("comète", "météorite"),
        ("étoile", "galaxie"), ("galaxie", "nébuleuse"), ("cratère", "canyon"),
        ("orbite", "trajectoire"), ("observatoire", "planétarium"), ("parapente", "montgolfière"),
        ("dirigeable", "parachute"), ("rover", "station"), ("météorite", "étoile"),
        ("cratère", "orbite"), ("trajectoire", "observatoire"),
    ),
    "Paysages": (
        ("montagne", "colline"), ("colline", "butte"), ("volcan", "geyser"),
        ("falaise", "canyon"), ("gorge", "ravin"), ("vallée", "plaine"),
        ("plaine", "plateau"), ("plage", "crique"), ("crique", "baie"),
        ("baie", "golfe"), ("île", "archipel"), ("atoll", "récif"),
        ("oasis", "mirage"), ("désert", "savane"), ("savane", "steppe"),
        ("steppe", "toundra"), ("forêt", "jungle"), ("jungle", "mangrove"),
        ("bosquet", "clairière"), ("clairière", "lisière"), ("lac", "lagune"),
        ("rivière", "torrent"), ("torrent", "cascade"), ("fleuve", "estuaire"),
        ("source", "puits"), ("grotte", "gouffre"), ("gouffre", "crevasse"),
        ("glacier", "banquise"), ("banquise", "iceberg"), ("sentier", "col"),
        ("colline", "falaise"), ("île", "atoll"), ("désert", "steppe"),
        ("forêt", "marais"), ("lac", "torrent"), ("fleuve", "source"),
        ("grotte", "crevasse"), ("savane", "toundra"), ("ravin", "butte"),
        ("golfe", "lagune"), ("récif", "iceberg"), ("butte", "falaise"),
        ("canyon", "ravin"), ("mangrove", "bosquet"), ("marais", "lac"),
        ("lagune", "rivière"), ("crevasse", "glacier"),
    ),
    "Météo et ciel": (
        ("pluie", "bruine"), ("averse", "orage"), ("rosée", "brume"),
        ("nuage", "cumulus"), ("vent", "brise"), ("brise", "bourrasque"),
        ("tempête", "ouragan"), ("canicule", "sécheresse"), ("inondation", "crue"),
        ("arc-en-ciel", "halo"), ("éclipse", "solstice"), ("marée", "houle"),
        ("baromètre", "girouette"), ("thermomètre", "pluviomètre"), ("nuage", "brume"),
        ("rosée", "halo"), ("vent", "bourrasque"), ("pluviomètre", "cumulus"),
        ("arc-en-ciel", "éclipse"), ("houle", "solstice"),
    ),
    "Arbres et plantes": (
        ("chêne", "hêtre"), ("hêtre", "frêne"), ("frêne", "orme"),
        ("peuplier", "saule"), ("sapin", "épicéa"), ("pin", "cèdre"),
        ("platane", "marronnier"), ("marronnier", "tilleul"), ("noyer", "châtaignier"),
        ("olivier", "figuier"), ("pommier", "cerisier"), ("cerisier", "prunier"),
        ("palmier", "bananier"), ("baobab", "séquoia"), ("bambou", "roseau"),
        ("mousse", "fougère"), ("cactus", "aloès"), ("tronc", "branche"),
        ("racine", "souche"), ("écorce", "sève"), ("feuille", "aiguille"),
        ("bourgeon", "pousse"), ("champignon", "lichen"), ("chêne", "bouleau"),
        ("sapin", "palmier"), ("saule", "olivier"), ("pin", "platane"),
        ("cactus", "bambou"), ("noyer", "figuier"), ("érable", "tilleul"),
        ("cyprès", "séquoia"), ("hêtre", "marronnier"), ("pommier", "prunier"),
        ("baobab", "aloès"), ("racine", "bourgeon"), ("tronc", "sève"),
        ("feuille", "gland"), ("bouleau", "peuplier"), ("saule", "platane"),
        ("cyprès", "érable"), ("prunier", "palmier"), ("bananier", "baobab"),
        ("séquoia", "bambou"), ("roseau", "cactus"), ("aloès", "fougère"),
        ("mousse", "lichen"),
    ),
    "Fleurs": (
        ("rose", "pivoine"), ("pivoine", "camélia"), ("tulipe", "jonquille"),
        ("narcisse", "jacinthe"), ("lys", "iris"), ("iris", "glaïeul"),
        ("tournesol", "dahlia"), ("dahlia", "chrysanthème"), ("œillet", "gerbera"),
        ("coquelicot", "bleuet"), ("bleuet", "myosotis"), ("lavande", "bruyère"),
        ("hortensia", "lilas"), ("lilas", "glycine"), ("géranium", "bégonia"),
        ("nénuphar", "lotus"), ("tige", "pétale"), ("pollen", "nectar"),
        ("bouquet", "couronne"), ("rose", "tulipe"), ("jonquille", "narcisse"),
        ("jacinthe", "lys"), ("glaïeul", "œillet"), ("gerbera", "camélia"),
        ("chrysanthème", "bégonia"), ("géranium", "hortensia"), ("glycine", "lavande"),
        ("bruyère", "coquelicot"), ("myosotis", "tournesol"), ("pollen", "bouquet"),
    ),
    "Sports": (
        ("football", "rugby"), ("basketball", "handball"), ("handball", "waterpolo"),
        ("volley", "badminton"), ("badminton", "squash"), ("tennis", "padel"),
        ("padel", "squash"), ("ping-pong", "badminton"), ("hockey", "crosse"),
        ("golf", "croquet"), ("pétanque", "bowling"), ("bowling", "curling"),
        ("baseball", "cricket"), ("natation", "plongeon"), ("aviron", "canoë"),
        ("surf", "bodyboard"), ("kitesurf", "wakeboard"), ("course", "marche"),
        ("sprint", "marathon"), ("escalade", "randonnée"), ("randonnée", "trekking"),
        ("alpinisme", "spéléologie"), ("ski", "snowboard"), ("patinage", "luge"),
        ("bobsleigh", "skeleton"), ("boxe", "judo"), ("judo", "karaté"),
        ("karaté", "taekwondo"), ("lutte", "sumo"), ("équitation", "polo"),
        ("cyclisme", "BMX"), ("danse", "gymnastique"), ("gymnastique", "trampoline"),
        ("yoga", "pilates"), ("musculation", "crossfit"), ("aérobic", "zumba"),
        ("parkour", "acrobatie"), ("football", "hockey"), ("tennis", "golf"),
        ("boxe", "lutte"), ("natation", "aviron"), ("ski", "patinage"),
        ("escalade", "spéléologie"), ("danse", "trampoline"), ("yoga", "musculation"),
        ("bowling", "croquet"), ("surf", "kitesurf"), ("judo", "sumo"),
        ("cyclisme", "équitation"), ("volley", "baseball"), ("randonnée", "alpinisme"),
        ("curling", "pétanque"), ("acrobatie", "zumba"), ("tennis", "squash"),
        ("padel", "ping-pong"), ("curling", "baseball"), ("cricket", "waterpolo"),
        ("course", "marathon"), ("sprint", "marche"), ("trampoline", "acrobatie"),
    ),
    "Équipement sportif": (
        ("raquette", "batte"), ("batte", "crosse"), ("filet", "but"),
        ("but", "panier"), ("panier", "poteau"), ("casque", "genouillère"),
        ("coudière", "genouillère"), ("maillot", "dossard"), ("chronomètre", "sifflet"),
        ("sifflet", "drapeau"), ("coupe", "ceinture"), ("podium", "tribune"),
        ("vestiaire", "gradin"), ("terrain", "piste"), ("piste", "couloir"),
        ("tapis", "ring"), ("ring", "tatami"), ("haltère", "kettlebell"),
        ("corde", "élastique"), ("tremplin", "plongeoir"), ("mousqueton", "baudrier"),
        ("bâton", "fixation"), ("arc", "arbalète"), ("selle", "étrier"),
        ("crosse", "arc"), ("coupe", "podium"), ("tribune", "gradin"),
        ("vestiaire", "terrain"),
    ),
    "Jeux": (
        ("go", "backgammon"), ("cartes", "tarot"), ("tarot", "belote"),
        ("poker", "rami"), ("dominos", "mahjong"), ("dés", "yams"),
        ("toupie", "yoyo"), ("monopoly", "cluedo"), ("cluedo", "risk"),
        ("puzzle", "labyrinthe"), ("billard", "fléchettes"), ("baby-foot", "flipper"),
        ("cerf-volant", "boomerang"), ("frisbee", "boomerang"), ("marelle", "élastique"),
        ("balançoire", "toboggan"), ("bascule", "manège"), ("poupée", "peluche"),
        ("peluche", "marionnette"), ("robot", "figurine"), ("cube", "brique"),
        ("ballon", "cerceau"), ("corde", "diabolo"), ("plateau", "damier"),
        ("belote", "poker"), ("rami", "dominos"), ("mahjong", "dés"),
        ("yams", "toupie"), ("frisbee", "marelle"), ("robot", "cube"),
    ),
    "Métiers": (
        ("médecin", "infirmier"), ("infirmier", "aide-soignant"), ("chirurgien", "anesthésiste"),
        ("pharmacien", "biologiste"), ("vétérinaire", "zoologiste"), ("sage-femme", "pédiatre"),
        ("boulanger", "pâtissier"), ("pâtissier", "chocolatier"), ("boucher", "charcutier"),
        ("charcutier", "traiteur"), ("serveur", "barman"), ("barman", "sommelier"),
        ("berger", "agriculteur"), ("agriculteur", "maraîcher"), ("viticulteur", "brasseur"),
        ("pêcheur", "marin"), ("pompier", "secouriste"), ("militaire", "légionnaire"),
        ("douanier", "vigile"), ("juge", "avocat"), ("notaire", "huissier"),
        ("greffier", "procureur"), ("facteur", "livreur"), ("chauffeur", "coursier"),
        ("jardinier", "paysagiste"), ("pilote", "steward"), ("aiguilleur", "contrôleur"),
        ("architecte", "ingénieur"), ("plombier", "électricien"), ("électricien", "chauffagiste"),
        ("maçon", "charpentier"), ("charpentier", "menuisier"), ("menuisier", "ébéniste"),
        ("couvreur", "carreleur"), ("serrurier", "vitrier"), ("mécanicien", "carrossier"),
        ("horloger", "bijoutier"), ("esthéticienne", "manucure"), ("photographe", "cameraman"),
        ("écrivain", "traducteur"), ("libraire", "bibliothécaire"), ("éducateur", "animateur"),
        ("comptable", "banquier"), ("caissier", "vendeur"), ("acteur", "figurant"),
        ("chanteur", "musicien"), ("danseur", "chorégraphe"), ("clown", "acrobate"),
        ("arbitre", "entraîneur"), ("guide", "réceptionniste"), ("archéologue", "géologue"),
        ("astronome", "météorologue"), ("boulanger", "boucher"), ("cuisinier", "serveur"),
        ("médecin", "pharmacien"), ("dentiste", "opticien"), ("pompier", "douanier"),
        ("juge", "notaire"), ("facteur", "chauffeur"), ("jardinier", "éboueur"),
        ("pilote", "marin"), ("architecte", "comptable"), ("plombier", "serrurier"),
        ("maçon", "couvreur"), ("peintre", "vitrier"), ("horloger", "cordonnier"),
        ("coiffeur", "manucure"), ("photographe", "écrivain"), ("acteur", "danseur"),
        ("libraire", "épicier"), ("berger", "apiculteur"), ("mineur", "bûcheron"),
        ("astronome", "géologue"), ("vétérinaire", "biologiste"), ("guide", "arbitre"),
        ("clown", "musicien"), ("dentiste", "pharmacien"), ("opticien", "vétérinaire"),
        ("biologiste", "zoologiste"), ("chocolatier", "boucher"), ("sommelier", "épicier"),
        ("maraîcher", "viticulteur"), ("brasseur", "apiculteur"), ("vigile", "juge"),
        ("huissier", "greffier"), ("procureur", "facteur"), ("livreur", "coursier"),
        ("chauffeur", "pilote"), ("steward", "aiguilleur"), ("contrôleur", "éboueur"),
        ("chauffagiste", "maçon"), ("ébéniste", "couvreur"), ("carreleur", "peintre"),
        ("bijoutier", "cordonnier"), ("tailleur", "coiffeur"), ("traducteur", "libraire"),
        ("médecin", "chirurgien"), ("anesthésiste", "pédiatre"), ("sage-femme", "esthéticienne"),
        ("cuisinier", "traiteur"), ("boulanger", "chocolatier"), ("secouriste", "militaire"),
        ("légionnaire", "vigile"), ("banquier", "caissier"), ("vendeur", "comptable"),
        ("archéologue", "météorologue"), ("chanteur", "chorégraphe"), ("réceptionniste", "animateur"),
    ),
    "Instruments": (
        ("piano", "clavecin"), ("clavecin", "orgue"), ("guitare", "banjo"),
        ("violon", "alto"), ("alto", "violoncelle"), ("violoncelle", "contrebasse"),
        ("tambour", "timbale"), ("cymbale", "gong"), ("triangle", "maracas"),
        ("saxophone", "clarinette"), ("clarinette", "hautbois"), ("hautbois", "basson"),
        ("flûte", "piccolo"), ("trombone", "tuba"), ("cor", "tuba"),
        ("synthétiseur", "sampler"), ("archet", "médiator"), ("touche", "pédale"),
        ("partition", "tablature"), ("métronome", "diapason"), ("pupitre", "étui"),
        ("piano", "guitare"), ("violon", "trompette"), ("harpe", "tambour"),
        ("flûte", "cymbale"), ("orgue", "banjo"), ("saxophone", "xylophone"),
        ("accordéon", "harmonica"), ("tuba", "contrebasse"), ("clarinette", "gong"),
        ("archet", "partition"), ("métronome", "étui"), ("clavecin", "ukulélé"),
        ("basson", "piccolo"), ("trombone", "vibraphone"), ("orgue", "accordéon"),
        ("timbale", "cymbale"), ("gong", "triangle"), ("maracas", "xylophone"),
        ("vibraphone", "saxophone"), ("basson", "flûte"), ("piccolo", "trompette"),
        ("cor", "harmonica"), ("corde", "touche"), ("pédale", "partition"),
        ("tablature", "métronome"), ("diapason", "pupitre"), ("étui", "guitare"),
    ),
    "Musique et spectacle": (
        ("rock", "punk"), ("punk", "metal"), ("metal", "grunge"),
        ("jazz", "blues"), ("blues", "soul"), ("soul", "funk"),
        ("rap", "slam"), ("pop", "disco"), ("techno", "trance"),
        ("reggae", "ska"), ("folk", "country"), ("classique", "baroque"),
        ("symphonie", "concerto"), ("concerto", "sonate"), ("chorale", "orchestre"),
        ("orchestre", "fanfare"), ("concert", "festival"), ("festival", "tournée"),
        ("cirque", "cabaret"), ("mime", "marionnette"), ("magie", "hypnose"),
        ("chapiteau", "estrade"), ("projecteur", "micro"), ("rideau", "décor"),
        ("costume", "maquillage"), ("applaudissement", "rappel"), ("billet", "programme"),
        ("sonate", "chorale"),
    ),
    "Arts et loisirs créatifs": (
        ("peinture", "aquarelle"), ("aquarelle", "gouache"), ("gouache", "acrylique"),
        ("huile", "pastel"), ("sculpture", "modelage"), ("céramique", "faïence"),
        ("gravure", "sérigraphie"), ("mosaïque", "vitrail"), ("fresque", "graffiti"),
        ("collage", "origami"), ("tricot", "crochet"), ("couture", "broderie"),
        ("broderie", "patchwork"), ("tissage", "tapisserie"), ("montage", "retouche"),
        ("caricature", "portrait"), ("toile", "chevalet"), ("crayon", "feutre"),
        ("moule", "empreinte"), ("galerie", "atelier"), ("vernissage", "exposition"),
        ("patchwork", "tissage"),
    ),
    "École": (
        ("gomme", "correcteur"), ("règle", "équerre"), ("compas", "rapporteur"),
        ("cahier", "classeur"), ("classeur", "chemise"), ("agenda", "carnet"),
        ("colle", "scotch"), ("agrafeuse", "perforatrice"), ("ciseaux", "cutter"),
        ("cartable", "trousse"), ("tableau", "ardoise"), ("craie", "marqueur"),
        ("pupitre", "estrade"), ("maths", "physique"), ("chimie", "biologie"),
        ("géologie", "astronomie"), ("histoire", "philosophie"), ("géographie", "économie"),
        ("anglais", "espagnol"), ("allemand", "italien"), ("latin", "grec"),
        ("grammaire", "orthographe"), ("conjugaison", "vocabulaire"), ("rédaction", "dictée"),
        ("examen", "concours"), ("note", "moyenne"), ("bulletin", "carnet"),
        ("leçon", "chapitre"), ("manuel", "dictionnaire"), ("dictionnaire", "encyclopédie"),
        ("bibliothèque", "médiathèque"), ("diplôme", "certificat"), ("cahier", "trousse"),
        ("cartable", "agenda"), ("tableau", "estrade"), ("maths", "géographie"),
        ("chimie", "philosophie"), ("latin", "italien"), ("dictée", "exposé"),
        ("note", "bulletin"), ("manuel", "encyclopédie"), ("grammaire", "conjugaison"),
        ("internat", "médiathèque"), ("scotch", "agrafeuse"), ("marqueur", "cutter"),
        ("histoire", "géographie"), ("philosophie", "économie"), ("exposé", "leçon"),
        ("chapitre", "examen"), ("concours", "note"), ("moyenne", "bulletin"),
        ("médiathèque", "classeur"),
    ),
    "Bureau et informatique": (
        ("ordinateur", "tablette"), ("imprimante", "scanner"), ("photocopieuse", "fax"),
        ("serveur", "routeur"), ("routeur", "modem"), ("câble", "adaptateur"),
        ("fichier", "dossier"), ("document", "tableur"), ("diaporama", "affiche"),
        ("site", "blog"), ("virus", "pare-feu"), ("corbeille", "archive"),
        ("raccourci", "menu"), ("onglet", "fenêtre"), ("tampon", "signature"),
        ("facture", "devis"), ("réunion", "entretien"), ("planning", "échéance"),
        ("écran", "imprimante"), ("fax", "modem"), ("entretien", "planning"),
    ),
    "Ville et commerces": (
        ("boulangerie", "pâtisserie"), ("épicerie", "supérette"), ("librairie", "papeterie"),
        ("kiosque", "tabac"), ("banque", "assurance"), ("poste", "pressing"),
        ("marché", "brocante"), ("brocante", "vide-grenier"), ("fleuriste", "jardinerie"),
        ("restaurant", "brasserie"), ("bijouterie", "parfumerie"), ("mairie", "préfecture"),
        ("commissariat", "caserne"), ("tribunal", "prison"), ("collège", "lycée"),
        ("théâtre", "cinéma"), ("musée", "galerie"), ("stade", "gymnase"),
        ("piscine", "patinoire"), ("impasse", "ruelle"), ("rond-point", "carrefour"),
        ("feu", "panneau"), ("boulangerie", "quincaillerie"), ("pharmacie", "papeterie"),
        ("banque", "poste"), ("musée", "cinéma"), ("stade", "piscine"),
        ("mairie", "tribunal"), ("caserne", "prison"), ("collège", "gymnase"),
        ("fleuriste", "bijouterie"), ("parking", "carrefour"), ("feu", "rond-point"),
        ("spa", "pressing"), ("galerie", "patinoire"), ("pharmacie", "parfumerie"),
        ("jardinerie", "quincaillerie"), ("vide-grenier", "restaurant"), ("brasserie", "cinéma"),
        ("théâtre", "musée"), ("gymnase", "piscine"), ("patinoire", "spa"),
        ("panneau", "lampadaire"),
    ),
    "Bâtiments et monuments": (
        ("manoir", "villa"), ("chaumière", "cabane"), ("chalet", "bungalow"),
        ("immeuble", "gratte-ciel"), ("basilique", "abbaye"), ("mosquée", "synagogue"),
        ("temple", "pagode"), ("donjon", "rempart"), ("moulin", "silo"),
        ("colonne", "obélisque"), ("statue", "buste"), ("viaduc", "barrage"),
    ),
    "Voyage": (
        ("bagage", "colis"), ("passeport", "visa"), ("billet", "réservation"),
        ("hôtel", "auberge"), ("auberge", "gîte"), ("camping", "bivouac"),
        ("tente", "caravane"), ("croisière", "circuit"), ("séjour", "escale"),
        ("guichet", "comptoir"), ("douane", "contrôle"), ("carte", "boussole"),
        ("boussole", "GPS"), ("itinéraire", "détour"), ("étape", "halte"),
        ("guide", "brochure"), ("devise", "change"), ("pourboire", "taxe"),
        ("chambre", "dortoir"), ("plage", "station"), ("gourde", "thermos"),
        ("duvet", "matelas"), ("valise", "bagage"), ("colis", "passeport"),
        ("visa", "billet"), ("réservation", "hôtel"), ("GPS", "itinéraire"),
        ("détour", "étape"), ("halte", "brochure"), ("réception", "plage"),
    ),
    "Fêtes et célébrations": (
        ("mariage", "fiançailles"), ("baptême", "communion"), ("banquet", "buffet"),
        ("réception", "cocktail"), ("bal", "soirée"), ("carnaval", "défilé"),
        ("emballage", "ruban"), ("carte", "invitation"), ("discours", "toast"),
        ("masque", "perruque"), ("sapin", "crèche"), ("cloche", "trompette"),
        ("vœux", "résolution"), ("manège", "stand"), ("tirage", "récompense"),
    ),
    "Temps et calendrier": (
        ("seconde", "minute"), ("heure", "journée"), ("matin", "après-midi"),
        ("midi", "goûter"), ("soirée", "veillée"), ("mois", "trimestre"),
        ("année", "décennie"), ("décennie", "siècle"), ("printemps", "automne"),
        ("été", "hiver"), ("montre", "chronomètre"), ("agenda", "planning"),
        ("date", "échéance"), ("délai", "attente"), ("matin", "midi"),
        ("après-midi", "veillée"), ("trimestre", "saison"), ("année", "siècle"),
        ("date", "délai"),
    ),
    "Communication": (
        ("lettre", "carte"), ("timbre", "cachet"), ("enveloppe", "étiquette"),
        ("appel", "message"), ("affiche", "panneau"), ("journal", "magazine"),
        ("article", "chronique"), ("titre", "légende"), ("interview", "reportage"),
        ("émission", "podcast"), ("insulte", "moquerie"), ("blague", "anecdote"),
        ("code", "signal"), ("lettre", "colis"), ("timbre", "enveloppe"),
        ("étiquette", "cachet"), ("magazine", "article"), ("chronique", "titre"),
        ("légende", "interview"), ("reportage", "émission"), ("podcast", "discours"),
    ),
    "Contenants": (
        ("caisse", "cageot"), ("bocal", "pot"), ("bouteille", "carafe"),
        ("enveloppe", "pochette"), ("tube", "cartouche"), ("plateau", "corbeille"),
        ("filet", "sacoche"), ("coffre-fort", "casier"),
    ),
    "Matières": (
        ("marbre", "granit"), ("granit", "ardoise"), ("sable", "gravier"),
        ("gravier", "galet"), ("aluminium", "zinc"), ("plastique", "résine"),
        ("caoutchouc", "latex"), ("papier", "carton"), ("tissu", "feutre"),
        ("fourrure", "peau"), ("laine", "cachemire"), ("nylon", "polyester"),
        ("liège", "paille"), ("cire", "résine"), ("pétrole", "goudron"),
        ("papier", "plastique"), ("cuivre", "zinc"), ("latex", "nylon"),
        ("cachemire", "cuir"), ("fourrure", "feutre"),
    ),
    "Formes et couleurs": (
        ("rouge", "bordeaux"), ("rose", "fuchsia"), ("orange", "corail"),
        ("jaune", "moutarde"), ("bleu", "indigo"), ("indigo", "marine"),
        ("marron", "beige"), ("beige", "taupe"), ("carré", "losange"),
        ("cercle", "ovale"), ("sphère", "cylindre"), ("cylindre", "cône"),
        ("rayure", "carreau"), ("pois", "damier"), ("bordeaux", "fuchsia"),
        ("marine", "corail"), ("ovale", "sphère"),
    ),
    "Argent et commerce": (
        ("euro", "dollar"), ("caisse", "tirelire"), ("facture", "ticket"),
        ("vente", "enchère"), ("salaire", "prime"), ("prime", "pourboire"),
        ("budget", "dépense"), ("fortune", "héritage"), ("banque", "coffre"),
        ("guichet", "distributeur"), ("stock", "inventaire"),
    ),
    "Récits et imaginaire": (
        ("conte", "fable"), ("poème", "chanson"), ("épopée", "saga"),
        ("intrigue", "péripétie"), ("héros", "aventurier"), ("roi", "empereur"),
        ("reine", "impératrice"), ("prince", "duc"), ("duc", "comte"),
        ("sorcière", "fée"), ("géant", "ogre"), ("vampire", "loup-garou"),
        ("zombie", "momie"), ("détective", "espion"), ("baguette", "grimoire"),
        ("quête", "épreuve"), ("roman", "poème"), ("chanson", "saga"),
        ("épopée", "intrigue"), ("péripétie", "quête"), ("épreuve", "héros"),
        ("prince", "comte"),
    ),
    "Objets du quotidien": (
        ("bougie", "lanterne"), ("aiguille", "épingle"), ("trombone", "agrafe"),
        ("punaise", "aimant"), ("crochet", "clou"), ("chiffon", "lingette"),
        ("balai", "plumeau"), ("éponge", "brosse"), ("gant", "tablier"),
        ("nappe", "set"), ("thermos", "glacière"), ("réveil", "minuteur"),
        ("télécommande", "manette"), ("fer", "planche"), ("miroir", "loupe"),
        ("loupe", "jumelles"), ("jumelles", "carnet"),
    ),
    "Sons et bruits": (
        ("tintement", "carillon"), ("sifflement", "bourdonnement"), ("miaulement", "ronronnement"),
        ("meuglement", "bêlement"), ("sifflet", "cor"), ("chuchotement", "soupir"),
        ("applaudissement", "huée"), ("mélodie", "berceuse"), ("hymne", "marche"),
    ),
    "Histoire et société": (
        ("royaume", "empire"), ("empire", "république"), ("colonie", "comptoir"),
        ("traité", "alliance"), ("siège", "assaut"), ("noble", "bourgeois"),
        ("artisan", "marchand"), ("marché", "foire"), ("expédition", "conquête"),
        ("vestige", "fouille"), ("loi", "décret"), ("tribunal", "assemblée"),
        ("citoyen", "sujet"), ("frontière", "province"), ("république", "colonie"),
        ("marchand", "foire"), ("siège", "traité"), ("manuscrit", "fouille"),
    ),
    "Enfance": (
        ("berceau", "landau"), ("hochet", "mobile"), ("cerceau", "quilles"),
        ("goûter", "compote"), ("cour", "préau"), ("récré", "sieste"),
    ),
    "Nettoyage et entretien": (
        ("seau", "chariot"), ("aspirateur", "souffleur"), ("lessive", "assouplissant"),
        ("repassage", "pliage"), ("moisissure", "calcaire"), ("désodorisant", "encens"),
        ("compost", "recyclage"), ("conteneur", "benne"),
    ),
    "Traits de caractère": (
        ("bavard", "gourmand"), ("timide", "distrait"), ("généreux", "drôle"),
        ("avare", "râleur"), ("courageux", "patient"), ("peureux", "coquet"),
        ("paresseux", "naïf"), ("travailleur", "discret"), ("menteur", "moqueur"),
        ("honnête", "économe"), ("gentil", "ordonné"), ("sévère", "ponctuel"),
        ("curieux", "maladroit"), ("habile", "solitaire"), ("têtu", "rêveur"),
        ("modeste", "sociable"), ("nerveux", "dépensier"), ("prudent", "brouillon"),
        ("audacieux", "bienveillant"), ("méfiant", "bruyant"), ("orgueilleux", "frileux"),
        ("indulgent", "impulsif"), ("posé", "négligé"), ("attentif", "conciliant"),
        ("bavard", "coquet"), ("timide", "gourmand"), ("généreux", "ordonné"),
        ("avare", "distrait"), ("courageux", "moqueur"), ("peureux", "économe"),
        ("travailleur", "râleur"), ("menteur", "frileux"), ("honnête", "solitaire"),
        ("gentil", "brouillon"), ("drôle", "prudent"), ("curieux", "sévère"),
        ("habile", "naïf"), ("maladroit", "sociable"), ("têtu", "ponctuel"),
        ("modeste", "nerveux"), ("orgueilleux", "patient"), ("impulsif", "discret"),
        ("rêveur", "bruyant"), ("posé", "audacieux"), ("indulgent", "méfiant"),
        ("attentif", "négligé"), ("conciliant", "dépensier"),
    ),
    "Cinéma et télévision": (
        ("film", "série"), ("épisode", "saison"), ("bande-annonce", "générique"),
        ("réalisateur", "producteur"), ("figurant", "cascadeur"), ("doublure", "cascadeur"),
        ("comédie", "thriller"), ("horreur", "fantastique"), ("animation", "marionnette"),
        ("court-métrage", "clip"), ("sous-titre", "doublage"), ("salle", "écran"),
        ("séance", "avant-première"), ("prix", "nomination"), ("acteur", "réalisateur"),
        ("décor", "accessoire"), ("thriller", "horreur"), ("montage", "sous-titre"),
        ("doublage", "affiche"), ("nomination", "décor"), ("accessoire", "perruque"),
    ),
    "Livres et écriture": (
        ("roman", "essai"), ("chapitre", "paragraphe"), ("sommaire", "index"),
        ("couverture", "jaquette"), ("virgule", "tiret"), ("rime", "vers"),
        ("métaphore", "comparaison"), ("narrateur", "personnage"), ("brouillon", "manuscrit"),
        ("éditeur", "imprimeur"), ("tirage", "édition"), ("plume", "encrier"),
    ),
    "Camping et plein air": (
        ("tente", "tipi"), ("sardine", "piquet"), ("duvet", "couverture"),
        ("gourde", "filtre"), ("lampe", "bougie"), ("trousse", "attelle"),
        ("feu", "braise"), ("fumée", "étincelle"), ("sac", "bâche"),
        ("nœud", "boucle"), ("sentier", "balise"), ("refuge", "bivouac"),
    ),
    "Coiffure et beauté": (
        ("mèche", "frange"), ("chignon", "tresse"), ("tresse", "natte"),
        ("queue", "couette"), ("raie", "épi"), ("teinture", "mèches"),
        ("balayage", "coloration"), ("permanente", "lissage"), ("gel", "laque"),
        ("ciseaux", "rasoir"), ("cape", "serviette"), ("bac", "fauteuil"),
        ("crème", "sérum"), ("pinceau", "éponge"), ("manucure", "pédicure"),
        ("épilation", "rasage"), ("natte", "queue"), ("teinture", "coloration"),
        ("balayage", "permanente"), ("lissage", "gel"), ("laque", "cire"),
        ("rasage", "mèches"),
    ),
    "Cuisine du monde": (
        ("antipasti", "tapas"), ("falafel", "houmous"), ("burrito", "quesadilla"),
        ("guacamole", "salsa"), ("polenta", "semoule"), ("naan", "pita"),
        ("tortilla", "galette"), ("bagel", "bretzel"), ("baklava", "loukoum"),
        ("kimchi", "pickles"), ("tortilla", "quesadilla"), ("burrito", "falafel"),
        ("houmous", "guacamole"), ("salsa", "pickles"),
    ),
    "Secours et sécurité": (
        ("alarme", "sirène"), ("extincteur", "lance"), ("civière", "brancard"),
        ("garrot", "compresse"), ("défibrillateur", "oxygène"), ("barrage", "cordon"),
        ("caserne", "poste"), ("exercice", "alerte"), ("plan", "consigne"),
    ),
    "Écrans et réseaux": (
        ("pixel", "résolution"), ("téléchargement", "diffusion"), ("abonnement", "essai"),
        ("profil", "avatar"), ("publication", "commentaire"), ("notification", "alerte"),
        ("émoji", "autocollant"), ("filtre", "effet"), ("story", "direct"),
        ("chaîne", "playlist"), ("wifi", "données"), ("antenne", "relais"),
        ("forfait", "recharge"), ("cadenas", "certificat"), ("cookie", "historique"),
        ("bug", "panne"), ("abonnement", "forfait"), ("wifi", "antenne"),
        ("relais", "recharge"), ("historique", "données"), ("essai", "certificat"),
    ),
    "Sur la route": (
        ("autoroute", "nationale"), ("départementale", "chemin"), ("bretelle", "échangeur"),
        ("glissière", "muret"), ("ralentisseur", "chicane"), ("bouchon", "ralentissement"),
        ("chantier", "cône"), ("tunnel", "viaduc"), ("dépanneuse", "remorquage"),
        ("cône", "tunnel"), ("viaduc", "péage"),
    ),
    "Brawl Stars": (
        ("Bull", "Frank"), ("Rosa", "Jacky"), ("Darryl", "Ash"),
        ("Hank", "Buster"), ("Draco", "Meg"), ("Frank", "Rosa"),
        ("Bull", "Jacky"), ("Ash", "Buster"), ("Piper", "Brock"),
        ("Bea", "Nani"), ("Belle", "Mandy"), ("Angelo", "Janet"),
        ("Brock", "Bea"), ("Piper", "Belle"), ("Nani", "Angelo"),
        ("Mandy", "Janet"), ("Barley", "Dynamike"), ("Tick", "Sprout"),
        ("Grom", "Willow"), ("Juju", "Sprout"), ("Dynamike", "Grom"),
        ("Barley", "Willow"), ("Mortis", "Crow"), ("Leon", "Edgar"),
        ("Fang", "Buzz"), ("Stu", "Kenji"), ("Melodie", "Lily"),
        ("Cordelius", "Shade"), ("Crow", "Leon"), ("Edgar", "Fang"),
        ("Poco", "Byron"), ("Pam", "Gus"), ("Kit", "Berry"),
        ("Doug", "Ruffs"), ("Max", "Gale"), ("Byron", "Gus"),
        ("Poco", "Kit"), ("Gene", "Tara"), ("Sandy", "Emz"),
        ("Otis", "Charlie"), ("Lou", "Chester"), ("Colette", "Amber"),
        ("Tara", "Sandy"), ("Emz", "Otis"), ("Colt", "Rico"),
        ("Spike", "Carl"), ("Bibi", "Surge"), ("Nita", "Jessie"),
        ("Penny", "Bo"), ("Griff", "Sam"), ("Squeak", "Gray"),
        ("Chuck", "Mico"), ("Clancy", "Moe"), ("Pearl", "Lola"),
        ("Maisie", "Eve"), ("Bonnie", "Ollie"), ("8-Bit", "R-T"),
        ("Rico", "Squeak"), ("Shelly", "Nita"), ("Carl", "Surge"),
    ),
}

OPTIONAL_THEMES: tuple[str, ...] = ("Brawl Stars",)
"""Thèmes qui ne rejoignent jamais le tirage général.

Un thème optionnel est **exclusif** : soit il est éteint et ses paires
n'existent pas pour la partie, soit il est allumé et c'est le seul
dictionnaire. Le mélanger au reste n'aurait pas de sens — les indices
d'un personnage de jeu vidéo et ceux d'un légume ne se ressemblent en
rien, et la table ne saurait plus dans quel univers elle joue.
"""

WORD_PAIRS: tuple[WordPair, ...] = tuple(
    pair
    for theme, pairs in PAIRS_BY_THEME.items()
    if theme not in OPTIONAL_THEMES
    for pair in pairs
)


def theme_pairs(theme: str) -> tuple[WordPair, ...]:
    """Les paires d'un seul thème, pour jouer en mode exclusif."""
    try:
        return PAIRS_BY_THEME[theme]
    except KeyError:
        raise KeyError(f"Thème inconnu : {theme!r}") from None


def theme_of(pair_index: int) -> str:
    """Le theme auquel appartient la paire d'indice donne."""
    seen = 0
    for theme, pairs in PAIRS_BY_THEME.items():
        if theme in OPTIONAL_THEMES:
            continue  # hors du tirage général, donc hors des indices
        if pair_index < seen + len(pairs):
            return theme
        seen += len(pairs)
    raise IndexError(pair_index)


class WordGenerator:
    """Tire une des paires du dictionnaire."""

    def __init__(
        self,
        pairs: Sequence[Sequence[str]] = WORD_PAIRS,
        rng: random.Random | None = None,
    ) -> None:
        if not pairs:
            raise ValueError("Il faut au moins une paire de mots")
        invalid = [
            i for i, pair in enumerate(pairs)
            if len(pair) != 2 or pair[0] == pair[1]
        ]
        if invalid:
            raise ValueError(
                f"Ces paires n'ont pas deux mots distincts : {invalid}"
            )
        self._pairs = tuple(tuple(pair) for pair in pairs)
        self._rng = rng or random.Random()

    def pair(self) -> WordPair:
        """Une paire au hasard.

        L'ordre est tire lui aussi : sans cela, le mot de la majorite
        serait toujours le premier ecrit, et un joueur qui connait la
        liste saurait dans quel camp il est.
        """
        first, second = self._rng.choice(self._pairs)
        return (first, second) if self._rng.random() < 0.5 else (second, first)

    def pair_count(self) -> int:
        """Nombre de paires du dictionnaire."""
        return len(self._pairs)
